package parser.sportsmanBag;

import java.util.HashMap;
import java.util.Map;

public class SportsManBagColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		
		COLOR_MAP.put("Name","Color Group");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Tan","Light Brown");
		COLOR_MAP.put("Vista Gray","Medium Gray");
		COLOR_MAP.put("Blaze Orange","CAMOUFLAGE ORANGE");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Mossy Oak Breakup Blaze Orange","CAMOUFLAGE ORANGE");
		COLOR_MAP.put("Realtree All Purpose Blaze Orange","CAMOUFLAGE ORANGE");
		COLOR_MAP.put("Realtree All Purpose Texas Orange","CAMOUFLAGE ORANGE");
		COLOR_MAP.put("Realtree All Purpose Navy","Camouflage Blue");
		COLOR_MAP.put("Realtree All Purpose Black","Camouflage Black");
		COLOR_MAP.put("Realtree All Purpose White","CAMOUFLAGE WHITE");
		COLOR_MAP.put("Realtree All Purpose Pink","Camouflage Pink");
		COLOR_MAP.put("Muddy Girl","Camouflage Pink");
		COLOR_MAP.put("Oilfield Camo","Camouflage Gray");
		COLOR_MAP.put("Realtree Xtra","Camouflage Brown");
		COLOR_MAP.put("Mossy Oak Country","Camouflage Green");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Mossy Oak Breakup","Camouflage Green");
		COLOR_MAP.put("Mossy Oak Shadow Grass Blades","Camouflage Brown");
		COLOR_MAP.put("Realtree Max 5","Camouflage Brown");
		COLOR_MAP.put("Typhon","Medium Gray");
		COLOR_MAP.put("Highlander","Medium Brown");
		COLOR_MAP.put("Safety Orange","Bright Orange");
		COLOR_MAP.put("Safety Yellow","Bright Yellow");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Earth","Medium Brown");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Dark Brown","Dark Brown");
		COLOR_MAP.put("Khaki","Light Brown");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Stone","DARK WHITE");
		COLOR_MAP.put("Realtree Max 4","Camouflage Green");
		COLOR_MAP.put("Realtree All Purpose Green","Camouflage Green");
		COLOR_MAP.put("Realtree Hardwoods","Camouflage Brown");
		COLOR_MAP.put("Realtree Xtra Green","Camouflage Green");
		COLOR_MAP.put("Advantage Classic","Camouflage Green");
		COLOR_MAP.put("Advantage Timber","Camouflage Brown");
		COLOR_MAP.put("Realtree Max 1","Camouflage Brown");
		COLOR_MAP.put("Realtree All Purpose","Camouflage Brown");
		COLOR_MAP.put("Realtree Hardwoods Green","Camouflage Green");
		COLOR_MAP.put("Wheat","Light Brown");
		COLOR_MAP.put("Olive","Dark Green");
		COLOR_MAP.put("Light Tan","Light Brown");
		COLOR_MAP.put("Dark Khaki","Medium Brown");
		COLOR_MAP.put("Realtree All Purpose- Pink","Medium Pink");
		COLOR_MAP.put("Realtree All Purpose-Blaze Orange","Medium Orange");
		COLOR_MAP.put("Realtree All Purpose-White","Medium White");
		COLOR_MAP.put("Dark Navy","Dark Blue");
		COLOR_MAP.put("Pink Ribbon","Medium Pink");
		COLOR_MAP.put("Tangerine","Medium Orange");
		COLOR_MAP.put("Cactus","Medium Green");
		COLOR_MAP.put("Pine","Medium Green");
		COLOR_MAP.put("Light Navy","Dark Blue");
		COLOR_MAP.put("Storm","Medium Gray");
		COLOR_MAP.put("Cool Gray","Medium Gray");
		COLOR_MAP.put("Cardinal","Dark Red");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Loden","Dark Green");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Silver","Light Gray");
		COLOR_MAP.put("Light Pink","Light Pink");
		COLOR_MAP.put("Texas Orange","Dark Orange");
		COLOR_MAP.put("Butter","Light Yellow");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Kelly","Medium Green");
		COLOR_MAP.put("Sky Blue","Light Blue");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Green Digital Camo","Camouflage Green");
		COLOR_MAP.put("Olive Digital Camo","Camouflage Green");
		COLOR_MAP.put("Black Digital Camo","Camouflage Black");
		COLOR_MAP.put("Sand Digital Camo","Camouflage Brown");
		COLOR_MAP.put("Pink Camo","Camouflage Pink");
		COLOR_MAP.put("Green Camo","Camouflage Green");
		COLOR_MAP.put("Royal Camo","Camouflage Blue");
		COLOR_MAP.put("Gray Camo","Camouflage Gray");
		COLOR_MAP.put("Tan Camo","Camouflage Brown");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Silver Camo","Camouflage Gray");
		COLOR_MAP.put("Mossy Oak Infinity","Camouflage Brown");
		COLOR_MAP.put("Neon Fuchsia","Bright Pink");
		COLOR_MAP.put("Pistachio","Light Green");
		COLOR_MAP.put("Oasis Blue","Medium Blue");
		COLOR_MAP.put("Jewel Blue","Medium Blue");
		COLOR_MAP.put("Orchid","Medium Purple");
		COLOR_MAP.put("Grape","Medium Purple");
		COLOR_MAP.put("Camel","Light Brown");
		COLOR_MAP.put("Heather Gray","Medium Gray");
		COLOR_MAP.put("Melon","Medium Pink");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Flamingo","Medium Pink");
		COLOR_MAP.put("Mocha","Medium Brown");
		COLOR_MAP.put("Camo","Camouflage Green");
		COLOR_MAP.put("Realtree Xtra Girl","Medium Green");
		COLOR_MAP.put("Original Mossy Oak Breakup","Camouflage Green");
		COLOR_MAP.put("Realtree All Purpose-Pink","Medium Pink");
		COLOR_MAP.put("Spruce","Dark Green");
		COLOR_MAP.put("Natural","Medium White");
		COLOR_MAP.put("Maize","Medium White");
		COLOR_MAP.put("Oatmeal Heather","Medium Gray");
		COLOR_MAP.put("Ash Heather","Dark Gray");
		COLOR_MAP.put("Dirty Heather","Medium Brown");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Chocolate","Dark Brown");
		COLOR_MAP.put("Taupe","Light Brown");
		COLOR_MAP.put("Game Guard","Camouflage Brown");
		COLOR_MAP.put("Bright Orange","Bright Orange");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Dark Ash","Medium Gray");
		COLOR_MAP.put("Bright Pink","Bright Pink");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Clover","Medium Green");
		COLOR_MAP.put("Turquoise","Bright Blue");
		COLOR_MAP.put("Dark Gray Cool Gray ll","Medium Gray");
		COLOR_MAP.put("Slate","Dark Gray");
		COLOR_MAP.put("Caribbean Blue","Medium Blue");
		COLOR_MAP.put("Dark Heather Gray","Dark Gray");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Tiger Camo","Camouflage Green");
		COLOR_MAP.put("American Ditsy","Medium White");
		COLOR_MAP.put("Polka Dot","Medium Black");
		COLOR_MAP.put("Stars","Dark Blue");
		COLOR_MAP.put("Camo Dreamstate","Medium Green");
		COLOR_MAP.put("Sand","Silver Metal");
		COLOR_MAP.put("Light Wheat","Light Brown");
		COLOR_MAP.put("Gold Canyon","Dark Yellow");
		COLOR_MAP.put("Burnt Olive","Dark Green");
		COLOR_MAP.put("Warm Red","Medium Red");
		COLOR_MAP.put("Cool Blue","Medium Blue");
		COLOR_MAP.put("Hunter Green","Dark Green");
		COLOR_MAP.put("Oatmeal","Light Brown");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Powder Blue","Light Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Mossy Oak Obsession","Camouflage Green");
		COLOR_MAP.put("Mossy Oak Brush","Camouflage Brown");
		COLOR_MAP.put("Olive Green","Medium Green");
		COLOR_MAP.put("Azalea","Medium Pink");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Army","Medium Green");
		COLOR_MAP.put("Sapphire","Medium Blue");
		COLOR_MAP.put("Blueberry","Medium Blue");
		COLOR_MAP.put("Chili","Medium Orange");
		COLOR_MAP.put("Island Green","Light Green");
		COLOR_MAP.put("Saddle","Medium Brown");
		COLOR_MAP.put("Waxy Canvas","Medium Gray");
		COLOR_MAP.put("Realtree Xtra Americana","Medium Brown");
		COLOR_MAP.put("Field Khaki","Medium Brown");
		COLOR_MAP.put("Tobacco","Medium Brown");
		COLOR_MAP.put("Cruising Blue","Medium Blue");
		COLOR_MAP.put("Granite","Medium Gray");
		COLOR_MAP.put("Sunkissed","Medium Red");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Turqoise","Bright Blue");
		COLOR_MAP.put("Mineral Blue","Medium Blue");
		COLOR_MAP.put("Navy Denim","Dark Blue");
		COLOR_MAP.put("Black Denim","Medium Black");
		COLOR_MAP.put("Heather","Medium Gray");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Coal","Dark Gray");
		COLOR_MAP.put("Deep Blue","Dark Blue");
			}
	
	public static String getColorGroup(String colorName){
		String colorGroup = COLOR_MAP.get(colorName);
		return colorGroup == null ?"Other": colorGroup;
	}
	
	
}
