package parser.primeline;

import java.util.Map;
import java.util.TreeMap;

public class PrimeLineConstants {

	public static Map<String, String> PRIMECOLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);//new HashMap<String, String>();
	public static Map<String, StringBuilder> DISCOUNTCODE_MAP =new TreeMap<String, StringBuilder>(String.CASE_INSENSITIVE_ORDER);//new HashMap<String, String>();
	public static Map<String, String> CRITPRICE_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);//new HashMap<String, String>();
	
	static StringBuilder dsic1 = new StringBuilder();
	static StringBuilder dsic2 = new StringBuilder();
	static StringBuilder dsic3 = new StringBuilder();
	static StringBuilder dsic4 = new StringBuilder();
	static StringBuilder dsic5 = new StringBuilder();
	static StringBuilder dsic6 = new StringBuilder();
	static StringBuilder dsic7 = new StringBuilder();
	static StringBuilder dsic8 = new StringBuilder();
	
	//static StringBuilder dsic9 = new StringBuilder();
	
	static {
		dsic1.append("C___C___C___C___D");
		dsic2.append("C___C___C___C___C");
		dsic3.append("C___C___C___C___C");
		dsic4.append("C___C___C___C___C");
		dsic5.append("C___C___C___C___C");
		dsic6.append("A___A___B___C___C");
		dsic7.append("A___A___A___B___C");
		dsic8.append("G___G___G___G___G");
		
		DISCOUNTCODE_MAP.put("4CD",dsic1);
		DISCOUNTCODE_MAP.put("5C",dsic2);
		DISCOUNTCODE_MAP.put("4C",dsic3);
		DISCOUNTCODE_MAP.put("C",dsic4);
		DISCOUNTCODE_MAP.put("3C",dsic5);
		DISCOUNTCODE_MAP.put("2ABC",dsic6);
		DISCOUNTCODE_MAP.put("3ABC",dsic7);
		DISCOUNTCODE_MAP.put("G",dsic8);
		PRIMECOLOR_MAP.put("Name","Color Group");
		PRIMECOLOR_MAP.put("Black","Medium Black");
		PRIMECOLOR_MAP.put("Dark Brown","Dark Brown");
		PRIMECOLOR_MAP.put("Red","Medium Red");
		PRIMECOLOR_MAP.put("Navy","Dark Blue");
		PRIMECOLOR_MAP.put("British Tan","Medium Brown");
		PRIMECOLOR_MAP.put("Brown","Medium Brown");
		PRIMECOLOR_MAP.put("Tan","Light Brown");
		PRIMECOLOR_MAP.put("Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Orange","Medium Orange");
		PRIMECOLOR_MAP.put("Yellow","Medium Yellow");
		PRIMECOLOR_MAP.put("White","Medium White");
		PRIMECOLOR_MAP.put("Multi Color","Multi Color");
		PRIMECOLOR_MAP.put("Translucent Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Medium White","Medium White");
		PRIMECOLOR_MAP.put("Translucent Baby Pink","Light Pink");
		PRIMECOLOR_MAP.put("Translucent Fuchsia","Light Purple");
		PRIMECOLOR_MAP.put("Translucent Red","Clear Red");
		PRIMECOLOR_MAP.put("Translucent Smoke","Clear Gray");
		PRIMECOLOR_MAP.put("Translucent Green","Clear Green");
		PRIMECOLOR_MAP.put("Translucent Orange","Clear Orange");
		PRIMECOLOR_MAP.put("Smoke","Medium Gray");
		PRIMECOLOR_MAP.put("Natural","DARK WHITE");
		PRIMECOLOR_MAP.put("Green","Medium Green");
		PRIMECOLOR_MAP.put("Lime Green","Bright Green");
		PRIMECOLOR_MAP.put("Clear","Clear");
		PRIMECOLOR_MAP.put("Purple","Medium Purple");
		PRIMECOLOR_MAP.put("Sage Green-Cocoa","Multi Color");
		PRIMECOLOR_MAP.put("Brown-Camel","Multi Color");
		PRIMECOLOR_MAP.put("Red-Camel","Multi Color");
		PRIMECOLOR_MAP.put("Black-Blue","Multi Color");
		PRIMECOLOR_MAP.put("Navy Blue","Dark Blue");
		PRIMECOLOR_MAP.put("Royal Blue","Bright Blue");
		PRIMECOLOR_MAP.put("Gray","Medium Gray");
		PRIMECOLOR_MAP.put("Pink","Medium Pink");
		PRIMECOLOR_MAP.put("Custom Colors","Assorted");
		PRIMECOLOR_MAP.put("Gunmetal","Medium Gray");
		PRIMECOLOR_MAP.put("Burgundy","Dark Red");
		PRIMECOLOR_MAP.put("Charcoal","Medium Gray");
		PRIMECOLOR_MAP.put("Medium Black","Medium Black");
		PRIMECOLOR_MAP.put("Translucent Light Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Silver","Silver Metal");
		PRIMECOLOR_MAP.put("Wheat","Light Brown");
		PRIMECOLOR_MAP.put("Mini Dot Black-White","Multi Color");
		PRIMECOLOR_MAP.put("Rust","Medium Orange");
		PRIMECOLOR_MAP.put("Midnight","Dark Blue");
		PRIMECOLOR_MAP.put("Gold","Dark Yellow");
		PRIMECOLOR_MAP.put("Metallic Blue","Metallic Blue");
		PRIMECOLOR_MAP.put("Metallic Lime Green","Metallic Green");
		PRIMECOLOR_MAP.put("Metallic Red","Metallic Red");
		PRIMECOLOR_MAP.put("Dark Green","Dark Green");
		PRIMECOLOR_MAP.put("Light Blue","Light Blue");
		PRIMECOLOR_MAP.put("Built Bold","Multi Color");
		PRIMECOLOR_MAP.put("Mini Dot Navy","Dark Blue");
		PRIMECOLOR_MAP.put("Graphite Grid","Medium Gray");
		PRIMECOLOR_MAP.put("Cocoa","Medium Brown");
		PRIMECOLOR_MAP.put("Cranberry","Dark Red");
		PRIMECOLOR_MAP.put("Natural-Natural","DARK WHITE");
		PRIMECOLOR_MAP.put("Metallic White","Metallic White");
		PRIMECOLOR_MAP.put("Metallic Black","Metallic Black");
		PRIMECOLOR_MAP.put("Metallic Green","Metallic Green");
		PRIMECOLOR_MAP.put("Metallic Stainless","Metallic Gray");
		PRIMECOLOR_MAP.put("Formula One Red","Medium Red");
		PRIMECOLOR_MAP.put("Vine","Medium Green");
		PRIMECOLOR_MAP.put("Lush Flower","Multi Color");
		PRIMECOLOR_MAP.put("Scatter Dot","Assorted");
		PRIMECOLOR_MAP.put("Apple Green","Medium Green");
		PRIMECOLOR_MAP.put("Hot Pink","Medium Pink");
		PRIMECOLOR_MAP.put("Forest Green","Medium Green");
		PRIMECOLOR_MAP.put("Rain Drop","Medium Blue");
		PRIMECOLOR_MAP.put("Fireball","Medium Red");
		PRIMECOLOR_MAP.put("Nickel","Nickel Metal");
		PRIMECOLOR_MAP.put("Translucent Lime Green","Clear Green");
		PRIMECOLOR_MAP.put("Dark Tan","Dark Brown");
		PRIMECOLOR_MAP.put("Black-Clear","Medium Black");
		PRIMECOLOR_MAP.put("City Grid","Other");
		PRIMECOLOR_MAP.put("Big Dot Black-White","Multi Color");
		PRIMECOLOR_MAP.put("Cream","Light Yellow");
		PRIMECOLOR_MAP.put("Chocolate","Medium Brown");
		PRIMECOLOR_MAP.put("Camel","Light Brown");
		PRIMECOLOR_MAP.put("Sage","Medium Green");
		PRIMECOLOR_MAP.put("Khaki Green","Light Green");
		PRIMECOLOR_MAP.put("Heather Gray","Light Gray");
		PRIMECOLOR_MAP.put("Frosted White","Medium White");
		PRIMECOLOR_MAP.put("Frosted Blue","Light Blue");
		PRIMECOLOR_MAP.put("Peach","Light Orange");
		PRIMECOLOR_MAP.put("Translucent Purple","Clear Purple");
		PRIMECOLOR_MAP.put("Cardinal","Medium Red");
		PRIMECOLOR_MAP.put("Light Pink","Light Pink");
		PRIMECOLOR_MAP.put("Maroon","Dark Red");
		PRIMECOLOR_MAP.put("Leopard","Multi Color");
		PRIMECOLOR_MAP.put("Batik Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Bon Bon Stripe","Medium Brown");
		PRIMECOLOR_MAP.put("Lady Bug","Medium Red");
		PRIMECOLOR_MAP.put("Sweet Tart","Assorted");
		PRIMECOLOR_MAP.put("Medium Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Medium Green","Medium Green");
		PRIMECOLOR_MAP.put("Medium Yellow","Medium Yellow");
		PRIMECOLOR_MAP.put("Medium Red","Medium Red");
		PRIMECOLOR_MAP.put("Custom","Assorted");
		PRIMECOLOR_MAP.put("White-Teal","Multi Color");
		PRIMECOLOR_MAP.put("Teal","Medium Green");
		PRIMECOLOR_MAP.put("Off-White","Medium White");
		PRIMECOLOR_MAP.put("Chrome","Chrome Metal");
		PRIMECOLOR_MAP.put("Turquoise","Light Green");
		PRIMECOLOR_MAP.put("Baby Pink","Medium Pink");
		PRIMECOLOR_MAP.put("Translucent Fuchia","Medium Pink");
		PRIMECOLOR_MAP.put("Translucent Black","Clear Black");
		PRIMECOLOR_MAP.put("Translucent Gray","Clear Gray");
		PRIMECOLOR_MAP.put("Translucent Burgundy","Clear Red");
		PRIMECOLOR_MAP.put("Bright Red","Bright Red");
		PRIMECOLOR_MAP.put("Formula 1 Red","Bright Red");
		PRIMECOLOR_MAP.put("Blue-Black","Medium Blue");
		PRIMECOLOR_MAP.put("Translucent Apple Green","Clear Green");
		PRIMECOLOR_MAP.put("Translucent Tangerine","Clear Orange");
		PRIMECOLOR_MAP.put("Translucent Aqua","Clear Blue");
		PRIMECOLOR_MAP.put("Translucent Pink","Clear Pink");
		PRIMECOLOR_MAP.put("Rosewood","Medium Brown");
		PRIMECOLOR_MAP.put("Black-Red","Multi Color");
		PRIMECOLOR_MAP.put("Black-Silver","Multi Color");
		PRIMECOLOR_MAP.put("Black-Bordeaux","Multi Color");
		PRIMECOLOR_MAP.put("Black-Granite","Multi Color");
		PRIMECOLOR_MAP.put("Cherry-Pink Crush","Multi Color");
		PRIMECOLOR_MAP.put("Navy-Cocoa","Multi Color");
		PRIMECOLOR_MAP.put("Cocoa-Blue","Multi Color");
		PRIMECOLOR_MAP.put("Sage-Brown","Multi Color");
		PRIMECOLOR_MAP.put("Summer Bloom","Medium Pink");
		PRIMECOLOR_MAP.put("Scuba Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Maritime","Medium Blue");
		PRIMECOLOR_MAP.put("Micro Dot","Multi Color");
		PRIMECOLOR_MAP.put("Khaki","Medium Brown");
		PRIMECOLOR_MAP.put("Positivity","Other");
		PRIMECOLOR_MAP.put("Jet Black","Medium Black");
		PRIMECOLOR_MAP.put("Lago Blue","Bright Blue");
		PRIMECOLOR_MAP.put("Micro Dot Navy","Dark Blue");
		PRIMECOLOR_MAP.put("Computer Gray","Other");
		PRIMECOLOR_MAP.put("Falling Leaves","Medium Orange");
		PRIMECOLOR_MAP.put("Nolita Stripe","Multi Color");
		PRIMECOLOR_MAP.put("White-Black","White:Combo:Black");
		PRIMECOLOR_MAP.put("Titanium","Titanium Metal");
		PRIMECOLOR_MAP.put("Metallic Dark Red","Metallic Red");
		PRIMECOLOR_MAP.put("Metallic Silver","Silver Metal");
		PRIMECOLOR_MAP.put("Coral","Medium Orange");
		PRIMECOLOR_MAP.put("Rain Drop Mini","Medium Blue");
		PRIMECOLOR_MAP.put("Translucent Yellow","Clear Yellow");
		PRIMECOLOR_MAP.put("Solid Black","Medium Black");
		PRIMECOLOR_MAP.put("Metallic Purple","Metallic Purple");
		PRIMECOLOR_MAP.put("Metallic Cranberry","Metallic Red");
		PRIMECOLOR_MAP.put("Black-Yellow","Medium Black");
		PRIMECOLOR_MAP.put("Red-Silver","Medium Red");
		PRIMECOLOR_MAP.put("Light Green-Lime Green","Medium Green");
		PRIMECOLOR_MAP.put("Neon Orange","Bright Orange");
		PRIMECOLOR_MAP.put("Neon Yellow","Bright Yellow");
		PRIMECOLOR_MAP.put("Hunter Green","Medium Green");
		PRIMECOLOR_MAP.put("Custom Color","Other");
		PRIMECOLOR_MAP.put("Solid Blue","Medium Blue");
		PRIMECOLOR_MAP.put("White/Black","Medium White");
		PRIMECOLOR_MAP.put("Jackolyte","Medium Orange");
		PRIMECOLOR_MAP.put("Dark Gray","Dark Gray");
		PRIMECOLOR_MAP.put("Yellow Green","Light Green");
		PRIMECOLOR_MAP.put("Black-Pink","Medium Black");
		PRIMECOLOR_MAP.put("Black w/ Red Stitching","Other");
		PRIMECOLOR_MAP.put("Black w/ Gray Stitching","Other");
		PRIMECOLOR_MAP.put("Lime","Bright Green");
		PRIMECOLOR_MAP.put("Built (R) Bold","Multi Color");
		PRIMECOLOR_MAP.put("Assorted","Assorted");
		PRIMECOLOR_MAP.put("Dark Red","Dark Red");
		PRIMECOLOR_MAP.put("White-Blue","Multi Color");
		PRIMECOLOR_MAP.put("White-Red","Multi Color");
		PRIMECOLOR_MAP.put("Black-Heather","Multi Color");
		PRIMECOLOR_MAP.put("Black-Black","Multi Color");
		PRIMECOLOR_MAP.put("Black-Burgundy","Multi Color");
		PRIMECOLOR_MAP.put("Black-Forest Green","Multi Color");
		PRIMECOLOR_MAP.put("Neon Green","Bright Green");
		PRIMECOLOR_MAP.put("Matte Black","Medium Black");
		PRIMECOLOR_MAP.put("Process Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Black w/ Silver Barrel","Other");
		PRIMECOLOR_MAP.put("Silver & Black","Other");
		PRIMECOLOR_MAP.put("Reflex Blue","Medium Blue");
		PRIMECOLOR_MAP.put("OtherCustom Color","Other");
		PRIMECOLOR_MAP.put("Stainless Steel","Other");
		PRIMECOLOR_MAP.put("Matte Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Matte Silver","Medium Gray");
		PRIMECOLOR_MAP.put("Clear Bottle/Black Yowie","Other");
		PRIMECOLOR_MAP.put("Clear Bottle/Blue Yowie","Other");
		PRIMECOLOR_MAP.put("Clear Bottle/Lime Green Yowie","Other");
		PRIMECOLOR_MAP.put("Clear Bottle/Red Yowie","Other");
		PRIMECOLOR_MAP.put("Clear Bottle/White Yowie","Other");
		PRIMECOLOR_MAP.put("Translucent Blue Bottle/Blue Yowie","Other");
		PRIMECOLOR_MAP.put("Translucent Red Bottle/Red Yowie","Other");
		PRIMECOLOR_MAP.put("White Yowie/Translucent Blue Bottle","Other");
		PRIMECOLOR_MAP.put("White Yowie/Translucent Green Bottle","Other");
		PRIMECOLOR_MAP.put("White Yowie/Translucent Red Bottle","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Blue Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Aqua Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Apple Green Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Pink Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Orange Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Purple Straw","Other");
		PRIMECOLOR_MAP.put("Clear/Translucent Red Straw","Other");
		PRIMECOLOR_MAP.put("Blue Pouch/Black & Blue Sunglasses","Other");
		PRIMECOLOR_MAP.put("Blue Pouch/Blue Sunglasses","Medium Blue");
		PRIMECOLOR_MAP.put("Clear Pouch/Black & Blue Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Black & Lime Green Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Black & Orange Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Black & Red Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Black & White Sunglasses","Other");
		PRIMECOLOR_MAP.put("Translucent Blue Pouch/Blue Pen/Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Blue Pen/Sunglasses","Other");
		PRIMECOLOR_MAP.put("Clear Pouch/Red Pen/Sunglasses","Other");
		PRIMECOLOR_MAP.put("Translucent Red Pouch/Red Pen/Sunglasses","Other");
		PRIMECOLOR_MAP.put("Tanslucent Red","Medium Red");
		PRIMECOLOR_MAP.put("Denim","Medium Blue");
		PRIMECOLOR_MAP.put("Carolina Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Texas-Orange","Medium Orange");
		PRIMECOLOR_MAP.put("Transparent Black","Clear Black");
		PRIMECOLOR_MAP.put("Transparent White","Clear White");
		PRIMECOLOR_MAP.put("Transparent Pink","Clear Pink");
		PRIMECOLOR_MAP.put("Transparent Red","Clear Red");
		PRIMECOLOR_MAP.put("Transparent Yellow","Clear Yellow");
		PRIMECOLOR_MAP.put("Transparent Orange","Clear Orange");
		PRIMECOLOR_MAP.put("Transparent Seafoam Green","Clear Green");
		PRIMECOLOR_MAP.put("Transparent Hunter Green","Clear Green");
		PRIMECOLOR_MAP.put("Transparent Lime","Clear Green");
		PRIMECOLOR_MAP.put("Transparent Dark Forest Green","Clear Green");
		PRIMECOLOR_MAP.put("Transparent Green","Clear Green");
		PRIMECOLOR_MAP.put("Transparent Powder Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Transparent Baby Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Transparent Light Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Transparent Navy","Clear Blue");
		PRIMECOLOR_MAP.put("Transparent Royal Blue","Clear Blue");
		PRIMECOLOR_MAP.put("Transparent Purple","Clear Purple");
		PRIMECOLOR_MAP.put("Plum","Medium Purple");
		PRIMECOLOR_MAP.put("Light Sand","Light Brown");
		PRIMECOLOR_MAP.put("Dark Sand","Light Brown");
		PRIMECOLOR_MAP.put("Dark Forest Green","Dark Green");
		PRIMECOLOR_MAP.put("Powder Blue","Medium Blue");
		PRIMECOLOR_MAP.put("Four Color","Multi Color");
		PRIMECOLOR_MAP.put("Fushia","Medium Pink");
		PRIMECOLOR_MAP.put("Canery Yellow","Medium Yellow");
		PRIMECOLOR_MAP.put("Lemon Chiffon","Medium Yellow");
		PRIMECOLOR_MAP.put("Peanut","Medium Brown");
		PRIMECOLOR_MAP.put("Seafoam Green","Medium Green");
		PRIMECOLOR_MAP.put("Baby Blue","Light Blue");
		PRIMECOLOR_MAP.put("Sky Blue","Light Blue");
		PRIMECOLOR_MAP.put("Orchid","Medium Purple");
		PRIMECOLOR_MAP.put("Tea Green","Medium Green");
		PRIMECOLOR_MAP.put("Transparent","Clear");
		PRIMECOLOR_MAP.put("Other","Multi Color");
		PRIMECOLOR_MAP.put("Camouflage","Multi color");
		PRIMECOLOR_MAP.put("Yellow Chifton","Medium Yellow");
		PRIMECOLOR_MAP.put("Lemon","Medium Yellow");
		PRIMECOLOR_MAP.put("Tangelo","Medium Orange");
		PRIMECOLOR_MAP.put("Dark Orange","Dark Orange");
		PRIMECOLOR_MAP.put("Light Brown","Light Brown");
		PRIMECOLOR_MAP.put("Light Green","Light Green");
		PRIMECOLOR_MAP.put("Full Color","Multi Color");
		PRIMECOLOR_MAP.put("Bamboo","Medium Brown");
		PRIMECOLOR_MAP.put("Canary Yellow","Medium Yellow");
		PRIMECOLOR_MAP.put("Any PMS color","Assorted");
		PRIMECOLOR_MAP.put("Copper","Metallic Orange");
		
		
		CRITPRICE_MAP.put("LG-900:Fire Island Business Card Case (Sueded Full-Grain Leather)","Material:Leather#####Sueded Full Grain Leather");
		CRITPRICE_MAP.put("LG-900:Fire Island Business Card Case (Cowhide)","Material:Leather#####Cowhide");
		CRITPRICE_MAP.put("LG-907:Helmsley Jotter Pad (Sueded Full-Grain Leather)","Material:Leather#####Sueded Full Grain Leather");
		CRITPRICE_MAP.put("LG-907:Helmsley Jotter Pad (Cowhide)","Material:Leather#####Cowhide");
		CRITPRICE_MAP.put("LG-915-35:Liberty Travel Wallet (Cowhide)","Material:Leather#####Cowhide");
		CRITPRICE_MAP.put("LG-915-35:Liberty Travel Wallet (Sueded Full-Grain Leather)","Material:Leather#####Sueded Full Grain Leather");
		CRITPRICE_MAP.put("PL-018:Retract-A-Badge – Square","Shape#####Square");
		CRITPRICE_MAP.put("PL-018:Retract-A-Badge – Round","Shape#####Round");
		CRITPRICE_MAP.put("PL-02:Basketball Stress Reliever","Shape#####Basketball");
		CRITPRICE_MAP.put("PL-02:Football Stress Reliever","Shape#####Football");
		CRITPRICE_MAP.put("PL-02:Baseball Stress Reliever","Shape#####Baseball");
		CRITPRICE_MAP.put("PL-02:Golf Ball Stress Reliever","Shape#####Golf ball");
		CRITPRICE_MAP.put("PL-02:Soccer Ball Stress Reliever","Shape#####Soccer ball");
		CRITPRICE_MAP.put("PL-041:Happy Mood Dude™ Stress Reliever","Product Option@@@@@Mood Choice#####Happy");
		CRITPRICE_MAP.put("PL-041:Shocked Mood Dude™ Stress Reliever","Product Option@@@@@Mood Choice#####Shocked");
		CRITPRICE_MAP.put("PL-080:Golf Can Holder","Shape#####Golf ball");
		CRITPRICE_MAP.put("PL-080:Soccer Can Holder","Shape#####Soccer ball");
		CRITPRICE_MAP.put("PL-080:Basketball Can Holder","Shape#####Basketball");
		CRITPRICE_MAP.put("PL-080:Baseball Can Holder","Shape#####Baseball");
		CRITPRICE_MAP.put("PL-080:Football Can Holder","Shape#####Football");
		CRITPRICE_MAP.put("PL-1821-20:Lip Balm – Mint Formula","Product Option@@@@@Flavor#####Mint");
		CRITPRICE_MAP.put("PL-1821-20:Lip Balm – Vanilla Formula","Product Option@@@@@Flavor#####Vanilla");
		CRITPRICE_MAP.put("PL-182:Lip Balm – Vanilla Formula w/Goofy™ Head","Product Option@@@@@Flavor#####Vanilla");
		CRITPRICE_MAP.put("PL-182:Lip Balm – Mint Formula w/Goofy™ Head","Product Option@@@@@Flavor#####Mint");
		CRITPRICE_MAP.put("PL-21:SlimFoldable USB Memory Flash Drive - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-21:SlimFoldable USB Memory Flash Drive - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-21:SlimFoldable USB Memory Flash Drive - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-21:SlimFoldable USB Memory Flash Drive - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-21:SlimFoldable USB Memory Flash Drive - 16GB","Size Type Capacity#####16 GB");
		CRITPRICE_MAP.put("PL-214:Flexi-PVC USB Drive 2.0 – 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-214:Flexi-PVC USB Drive 2.0 – 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-214:Flexi-PVC USB Drive 2.0 – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-214:Flexi-PVC USB Drive 2.0 – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-215:Zest USB Drive 2.0 - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-215:Zest USB Drive 2.0 - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-215:Zest USB Drive 2.0 - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-215:Zest USB Drive 2.0 - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-222:Key Chain USB Memory Flash Drive - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-222:Key Chain USB Memory Flash Drive - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-222:Key Chain USB Memory Flash Drive - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-222:Key Chain USB Memory Flash Drive - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-222:Key Chain USB Memory Flash Drive - 16GB","Size Type Capacity#####16 GB");
		CRITPRICE_MAP.put("PL-223:Rubberized USB Memory Flash Drive - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-223:Rubberized USB Memory Flash Drive - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-223:Rubberized USB Memory Flash Drive - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-223:Rubberized USB Memory Flash Drive - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-223:Rubberized USB Memory Flash Drive - 16GB","Size Type Capacity#####16 GB");
		CRITPRICE_MAP.put("PL224:Crystals USB Memory Flash Drive - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL224:Crystals USB Memory Flash Drive - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL224:Crystals USB Memory Flash Drive - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL224:Crystals USB Memory Flash Drive - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL224:Crystals USB Memory Flash Drive - 16GB","Size Type Capacity#####16 GB");
		CRITPRICE_MAP.put("PL-230:Clip USB Memory Flash Drive - 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-230:Clip USB Memory Flash Drive - 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-230:Clip USB Memory Flash Drive - 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-230:Clip USB Memory Flash Drive - 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-230:Clip USB Memory Flash Drive - 16GB","Size Type Capacity#####16 GB");
		CRITPRICE_MAP.put("PL26:Lanyard USB Memory Drive 2.0 – 2GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL26:Lanyard USB Memory Drive 2.0 – 1GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL26:Lanyard USB Memory Drive 2.0 – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL26:Lanyard USB Memory Drive 2.0 – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-266:2-D USB Flexi-Drive 2.0 – 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-266:2-D USB Flexi-Drive 2.0 – 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-266:2-D USB Flexi-Drive 2.0 – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-266:2-D USB Flexi-Drive 2.0 – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-26:3-D USB Flexi-Drive 2.0 – 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-26:3-D USB Flexi-Drive 2.0 – 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-26:3-D USB Flexi-Drive 2.0 – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-26:3-D USB Flexi-Drive 2.0 – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-291:Custom Credit Card Drive USB – 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-291:Custom Credit Card USB Drive – 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-291:Custom Credit Card USB Drive – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-291:Custom Credit Card USB Drive – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-365:Rubik’s® Custom USB Puzzle Drive 2.0 – 1GB","Size Type Capacity#####1 GB");
		CRITPRICE_MAP.put("PL-365:Rubik’s® Custom USB Puzzle Drive 2.0 – 2GB","Size Type Capacity#####2 GB");
		CRITPRICE_MAP.put("PL-365:Rubik’s® Custom USB Puzzle Drive 2.0 – 4GB","Size Type Capacity#####4 GB");
		CRITPRICE_MAP.put("PL-365:Rubik’s® Custom USB Puzzle Drive 2.0 – 8GB","Size Type Capacity#####8 GB");
		CRITPRICE_MAP.put("PL-4363-4364:Nurse 25 oz. Flexi-Bottle","Shape#####Nurse");
		CRITPRICE_MAP.put("PL-4363-4364:Doctor 25 oz. Flexi-Bottle","Shape#####Doctor");
		CRITPRICE_MAP.put("PL-501:Flower Pot Set with Marigold Seeds","Product Option@@@@@Seed Choice#####Marigold");
		CRITPRICE_MAP.put("PL-501:Flower Pot Set with Basil Seeds","Product Option@@@@@Seed Choice#####Basil");
		CRITPRICE_MAP.put("PL-501:Flower Pot Set with Chive Seeds","Product Option@@@@@Seed Choice#####Chive");
	}
	
	
}
