package parser.alfa;

import java.util.HashMap;
import java.util.Map;

public class AlfaColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Clear Orange","Clear Orange");
		COLOR_MAP.put("Bright Orange","Bright Orange");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Clear Black","Clear Black");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Clear Red","Clear Red");
		COLOR_MAP.put("Dark Red","Dark Red");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Bright Red","Bright Red");
		COLOR_MAP.put("Lime Green","Bright Green");
		COLOR_MAP.put("Royal Blue","Medium Blue");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Royal","Medium Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Light Brown","Light Brown");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Clear Green","Clear Green");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Camouflage Green","Camouflage Green");
		COLOR_MAP.put("Bright Green","Bright Green");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Clear Purple","Clear Purple");
		COLOR_MAP.put("Bright Purple","Bright Purple");
		COLOR_MAP.put("Gold","Medium Yellow");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Clear Blue","Clear Blue");
		COLOR_MAP.put("Bright Blue","Bright Blue");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Metallic White","Metallic White");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Smoke","Medium Gray");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Light Camouflage Green","Camouflage Green");
		COLOR_MAP.put("Natural Beige","Light Brown");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Bright Pink","Bright Pink");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Clear Yellow","Clear Yellow");
		COLOR_MAP.put("Bright Yellow","Bright Yellow");
		COLOR_MAP.put("Pearl White-Silver","Medium White");
		COLOR_MAP.put("Frosted White","Medium White");
		COLOR_MAP.put("Gray-Black","Multi Color");
		COLOR_MAP.put("Burgundy Red","Dark Red");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Red-Silver","Medium Red");
		COLOR_MAP.put("Gun Metal Gray","Medium Gray");
		COLOR_MAP.put("Silver","Medium Gray");
		COLOR_MAP.put("Chrome Silver-Silver","Chrome Metal");
		COLOR_MAP.put("Glisten Blue","Medium Blue");
		COLOR_MAP.put("Glisten Black","Medium Black");
		COLOR_MAP.put("Satin Chrome","Chrome Metal");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Satin Chrome Silver","Chrome Metal");
		COLOR_MAP.put("Translucent Burgundy Red","Clear Red");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Metallic Burgundy-Satin Chrome","Multi Color");
		COLOR_MAP.put("Metallic Green-Satin Chrome","Multi Color");
		COLOR_MAP.put("Matte Blue-Satin Chrome","Medium Blue");
		COLOR_MAP.put("Chrome-Gun Metal","Multi Color");
		COLOR_MAP.put("Glisten Burgundy","Dark Red");
		COLOR_MAP.put("Glisten Green","Medium Green");
		COLOR_MAP.put("Baby Pink","Light Pink");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Sky Blue","Light Blue");
		COLOR_MAP.put("Light Copper","Copper Metal");
		COLOR_MAP.put("Gunmetal Gray","Medium Gray");
		COLOR_MAP.put("Charcoal Gray","Dark Gray");
		COLOR_MAP.put("Gun Metal","Medium Gray");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Gunmetal","Medium Gray");
		COLOR_MAP.put("Satin Nickel","Nickel Metal");
		COLOR_MAP.put("Pearl White","Medium White");
		COLOR_MAP.put("Translucent Enamel Red","Clear Red");
		COLOR_MAP.put("Translucent Enamel Blue","Clear Blue");
		COLOR_MAP.put("Translucent Enamel Green","Clear Green");
		COLOR_MAP.put("Translucet Burgundy","Clear Red");
		COLOR_MAP.put("Translucent Burgundy","Clear Red");
		COLOR_MAP.put("Translucent Dark Green","Clear Green");
		COLOR_MAP.put("Natural","Medium White");
		COLOR_MAP.put("Khaki","Light Brown");
		COLOR_MAP.put("Rosewood","Medium Red");
		COLOR_MAP.put("Satin Nickel Silver","Nickel Metal");
		COLOR_MAP.put("Translucent Black","Clear Black");
		COLOR_MAP.put("Titanium Blue","Medium Blue");
		COLOR_MAP.put("Titanium Red","Medium Red");
		COLOR_MAP.put("Titanium Green","Medium Green");
		COLOR_MAP.put("Chrome Silver-Black","Chrome Metal");
		COLOR_MAP.put("Satin Gold","Medium Yellow");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Digital Gray Camouflage","Camouflage Gray");
		COLOR_MAP.put("Digital Camouflage Green","Camouflage Green");
		COLOR_MAP.put("Digital Gray","Camouflage Gray");
		COLOR_MAP.put("Gray Pixel Camouflage","Camouflage Gray");
		COLOR_MAP.put("Gray Pixel","Camouflage Gray");
		COLOR_MAP.put("Royal-Black","Multi Color");
		COLOR_MAP.put("Red-Black","Multi Color");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Olive Green","Medium Green");
		COLOR_MAP.put("Matte Blue-Silver","Medium Blue");
		COLOR_MAP.put("Translucent Red/Silver","Clear Red");
		COLOR_MAP.put("Matte Red","Medium Red");
		COLOR_MAP.put("Matte Blue","Medium Blue");
		COLOR_MAP.put("Matte Green","Medium Green");
		COLOR_MAP.put("Gray Digital Camouflage","Camouflage Gray");
		COLOR_MAP.put("Matte Black","Medium Black");
		COLOR_MAP.put("Black-Gold","Dark Yellow");
		COLOR_MAP.put("Tan Digital Camo","Camouflage Brown");
		COLOR_MAP.put("Tan Digital Camouflage","Camouflage Brown");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Canary Red","Medium Red");
		COLOR_MAP.put("Digital Camo","Multi Color");
		COLOR_MAP.put("Royal-White","Multi Color");
		COLOR_MAP.put("Green-White","Multi Color");
		COLOR_MAP.put("Red-White","Multi Color");
		COLOR_MAP.put("Navy-White","Multi Color");
		COLOR_MAP.put("Black-White","Multi Color");
		COLOR_MAP.put("Red-White-Navy","Multi Color");
		COLOR_MAP.put("Jade Green","Medium Green");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Lite Blue","Light Blue");
		COLOR_MAP.put("Metallic Pink","Metallic Pink");
		COLOR_MAP.put("Metallic Light Blue","Metallic Blue");
		COLOR_MAP.put("Dark Turquoise","Medium Blue");
		COLOR_MAP.put("Glisten Pink","Light Pink");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Glisten Purple","Medium Purple");
		COLOR_MAP.put("Matte Burgundy","Dark Red");
		COLOR_MAP.put("Digital Camo Tan Beige","Camouflage Brown");
		COLOR_MAP.put("Forest Green-Black","Medium Green");
		COLOR_MAP.put("Chrome Silver","Chrome Metal");
		COLOR_MAP.put("Matte Silver","Medium Gray");
		COLOR_MAP.put("Digital Camouflage Gray","Camouflage Gray");
		COLOR_MAP.put("Lime Green-Black","Light Green");
		COLOR_MAP.put("Satin Chrome  Silver","Chrome Metal");
		COLOR_MAP.put("Lacquered Black","Medium Black");
		COLOR_MAP.put("Glisten Baby Pink","Medium Pink");
		COLOR_MAP.put("Gun Metal Gray-Silver","Medium Gray");
		COLOR_MAP.put("Maroon Red","Dark Red");
		COLOR_MAP.put("Solid Black","Medium Black");
		COLOR_MAP.put("Black-Silver","Medium Black");
		COLOR_MAP.put("Metallic Blue/Silver","Metallic Blue");
		COLOR_MAP.put("Glisten Red","Medium Red");
		COLOR_MAP.put("Translucent Teal","Clear Blue");
		COLOR_MAP.put("Dk Green","Medium Green");
		COLOR_MAP.put("Yellow-Black","Multi Color");
		COLOR_MAP.put("Royal-Dark Gray","Multi Color");
		COLOR_MAP.put("Red-Dark Gray","Multi Color");
		COLOR_MAP.put("Dark Gray-Black","Multi Color");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Natural-Black","Multi Color");
		COLOR_MAP.put("Natural-Pink","Multi Color");
		COLOR_MAP.put("Natural-Red","Multi Color");
		COLOR_MAP.put("Natural-Blue","Multi Color");
		COLOR_MAP.put("Kelly","Medium Green");
		COLOR_MAP.put("Navy-Black","Multi Color");
		COLOR_MAP.put("Medium Black","Medium Black");
		COLOR_MAP.put("Glistent Black","Medium Black");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Medium Blue","Medium Blue");
		COLOR_MAP.put("Pearl","Medium White");
		COLOR_MAP.put("Tan","Light Brown");
		COLOR_MAP.put("Fuchsia","Medium Purple");
		COLOR_MAP.put("Camo 1","Camouflage Brown");
		COLOR_MAP.put("Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Texas Orange","Dark Orange");
		COLOR_MAP.put("Turquoise","Light Blue");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Camo 2","Other");
		COLOR_MAP.put("Camo 4","Other");
		COLOR_MAP.put("Camo1","Multi Color");
		COLOR_MAP.put("Camo2","Multi Color");
		COLOR_MAP.put("Camo3","Multi Color");
		COLOR_MAP.put("Coral","Medium Pink");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("Robbins Egg Blue","Light Blue");
		COLOR_MAP.put("White-Blue","Multi Color");
		COLOR_MAP.put("Apple Green","Light Green");
		COLOR_MAP.put("Black-Red","Multi Color");
		COLOR_MAP.put("Gray-Yellow","Multi Color");
		COLOR_MAP.put("Royal-Lime Green","Multi Color");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Magenta","Bright Pink");
		COLOR_MAP.put("Assorted Colors","Assorted");
		COLOR_MAP.put("Camo4","Multi Color");
		COLOR_MAP.put("Camo","Camouflage Brown");
		COLOR_MAP.put("Khaki Beige","Light Brown");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Ice Blue","Light Blue");
		COLOR_MAP.put("Spring Green","Bright Green");
		COLOR_MAP.put("Stainless Steel","Medium Gray");
		COLOR_MAP.put("Army Green","Dark Green");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Khaki Brown","Light Brown");
		COLOR_MAP.put("French Rose Pink","Medium Pink");
		COLOR_MAP.put("Transparent Blue","Clear Blue");
		COLOR_MAP.put("Transparent Green","Clear Green");
		COLOR_MAP.put("Transparent Orange","Clear Orange");
		COLOR_MAP.put("Transparent Red","Clear Red");
		COLOR_MAP.put("Transparent Yellow","Clear Yellow");
		COLOR_MAP.put("Glow","Other");
		COLOR_MAP.put("Polished Chrome","Chrome Metal");
		COLOR_MAP.put("Transparent Purple","Clear Purple");
		COLOR_MAP.put("MetBlue","Medium Blue");
		COLOR_MAP.put("MetBlack","Medium Black");
		COLOR_MAP.put("Metcharcoal","Medium Gray");
		COLOR_MAP.put("MetRed","Medium Red");
		COLOR_MAP.put("Granite","Medium Gray");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Frosted","Medium White");
		COLOR_MAP.put("Electric Blue","Bright Blue");
		COLOR_MAP.put("Champagne","Light Brown");
		COLOR_MAP.put("Hunter Green","Dark Green");
		COLOR_MAP.put("Metallic Silver","Metallic Gray");
		COLOR_MAP.put("Process Blue","Medium Blue");
		COLOR_MAP.put("Stainless Steel Silver","Medium Gray");
		COLOR_MAP.put("Wood","Medium Brown");
		COLOR_MAP.put("Fuchsia (Hot Pink)","Medium Pink");
		COLOR_MAP.put("Forrest Green","Medium Green");
		COLOR_MAP.put("Khaki Lime","Medium Green");
		COLOR_MAP.put("Forest","Medium Green");
		COLOR_MAP.put("Teal Green","Medium Green");
		COLOR_MAP.put("Tangerine","Medium Orange");
		COLOR_MAP.put("Red Plaid","Medium Red");
		COLOR_MAP.put("Blue Plaid","Medium Blue");
		COLOR_MAP.put("Gray Plaid","Medium Gray");
		COLOR_MAP.put("Zebra","Multi Color");
		COLOR_MAP.put("Smoke Gray","Medium Gray");
		COLOR_MAP.put("Aqua Blue","Medium Blue");
		COLOR_MAP.put("White Stripe","Medium White");
		COLOR_MAP.put("Red Stripes","Medium Red");
		COLOR_MAP.put("Blue Stripes","Medium Blue");
		COLOR_MAP.put("Pink Stripes","Medium Pink");
		COLOR_MAP.put("Orange Stripes","Medium Orange");
		COLOR_MAP.put("Purple Stripes","Medium Purple");
		COLOR_MAP.put("Cobalt Blue","Medium Blue");
		COLOR_MAP.put("Cream","Light Yellow");
		COLOR_MAP.put("White Opaque","Medium White");
		COLOR_MAP.put("Almond","Light Brown");
		COLOR_MAP.put("Bamboo","Light Brown");
		COLOR_MAP.put("Champagne Silver","Medium Gray");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Sea Glass","Light Green");
		COLOR_MAP.put("Gradient Black","Dark Black");
		COLOR_MAP.put("Gradient Blue","Dark Blue");
		COLOR_MAP.put("Gradient Green","Dark Green");
		COLOR_MAP.put("Gradient Orange","Dark Orange");
		COLOR_MAP.put("Gradient Pink","Dark Pink");
		COLOR_MAP.put("Gradient Purple","Dark Purple");
		COLOR_MAP.put("Gradient Red","Dark Red");
		COLOR_MAP.put("Gradient Yellow","Dark Yellow");
		COLOR_MAP.put("Metallic Orange","Metallic Orange");
		COLOR_MAP.put("Metallic Purple","Metallic Purple");
		COLOR_MAP.put("Metallic Royal Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("Olive","Dark Green");
		COLOR_MAP.put("Neon Lime Green","Bright Green");
		COLOR_MAP.put("Translucent Aqua","Clear Blue");
		COLOR_MAP.put("Trans Green","Clear Green");
		COLOR_MAP.put("Trans Blue","Clear Blue");
		COLOR_MAP.put("Trans Red","Clear Red");
		COLOR_MAP.put("Trans Smoke","Clear Gray");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Cyan","Light Blue");
		COLOR_MAP.put("Trans Purple","Clear Purple");
		COLOR_MAP.put("Neon Aqua","Bright Blue");
		COLOR_MAP.put("Milky White","Medium White");
		COLOR_MAP.put("Matte Royal Blue","Dark Blue");
		COLOR_MAP.put("Reflux Blue","Medium Blue");
		COLOR_MAP.put("Burnt Red","Dark Red");
		COLOR_MAP.put("Mustard Yellow","Dark Yellow");
		COLOR_MAP.put("Amber","Medium Brown");
		COLOR_MAP.put("Sand","Light Brown");
		COLOR_MAP.put("Translucent Gray","Medium Gray");
		COLOR_MAP.put("Wine","Dark Red");
		COLOR_MAP.put("Almond Brown","Medium Brown");
		COLOR_MAP.put("Ivory","Medium White");
		COLOR_MAP.put("Beige","Light Brown");
	}
	public static String getColorGroup(String colorName){
		return COLOR_MAP.get(colorName);// this is used to Ball Pro supplier
	}
}
