package parser.sageRMKWorldwide;

import java.util.HashMap;
import java.util.Map;

public class SageRMKWorldwideColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Army Green","Medium Green");
		COLOR_MAP.put("Aruba Bay","Medium Blue");
		COLOR_MAP.put("Ash Gray","Light Gray");
		COLOR_MAP.put("Asphalt Gray","Medium Gray");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Assorted Colors","Assorted");
		COLOR_MAP.put("Athletic Blue","Medium Blue");
		COLOR_MAP.put("Athletic Gray","Medium Gray");
		COLOR_MAP.put("Atlantis Green","Medium Green");
		COLOR_MAP.put("Avocado Green","Light Green");
		COLOR_MAP.put("Azalea Pink","Medium Pink");
		COLOR_MAP.put("Azure Blue","Medium Blue");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Baltic Blue","Medium Blue");
		COLOR_MAP.put("Basil","Medium Green");
		COLOR_MAP.put("Beetle Blue","Medium Blue");
		COLOR_MAP.put("Beige","Light Brown");
		COLOR_MAP.put("Beryllium","Other");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Blue Dusk","Medium Blue");
		COLOR_MAP.put("Blue Silver","Silver Metal");
		COLOR_MAP.put("Cream","Light Yellow");
		COLOR_MAP.put("Breaker Blue","Medium Blue");
		COLOR_MAP.put("Bright Azure Blue","Bright Blue");
		COLOR_MAP.put("Bright Blue","Bright Blue");
		COLOR_MAP.put("Bright Red","Bright Red");
		COLOR_MAP.put("Bright Yellow","Bright Yellow");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Brown Camouflage","Camouflage Brown");
		COLOR_MAP.put("Nude","Light Brown");
		COLOR_MAP.put("Bud Green","Medium Green");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Butter Yellow","Medium Yellow");
		COLOR_MAP.put("Camel Brown","Medium Brown");
		COLOR_MAP.put("Camouflage","Camouflage Brown");
		COLOR_MAP.put("Candy Apple Red","Medium Red");
		COLOR_MAP.put("Cardinal","Medium Red");
		COLOR_MAP.put("Cardinal Red","Medium Red");
		COLOR_MAP.put("Carmine Red","Medium Red");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Cedar Red","Medium Brown");
		COLOR_MAP.put("Charcoal Gray","Dark Gray");
		COLOR_MAP.put("Cherry Red","Medium Red");
		COLOR_MAP.put("Chianti","Medium Red");
		COLOR_MAP.put("Chili Pepper Red","Medium Red");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Chrome Blue","Metallic Blue");
		COLOR_MAP.put("Clam","DARK WHITE");
		COLOR_MAP.put("Coastal Blue","Medium Blue");
		COLOR_MAP.put("Columbia Blue","Medium Blue");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Cranberry Red","Medium Red");
		COLOR_MAP.put("Daisy","Medium Yellow");
		COLOR_MAP.put("Daisy Yellow","Medium Yellow");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Dark Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Dark Green","Medium Green");
		COLOR_MAP.put("Dark Heather Gray","Dark Gray");
		COLOR_MAP.put("Deep Forest Green","Dark Green");
		COLOR_MAP.put("Deep Navy Blue","Dark Blue");
		COLOR_MAP.put("Deep Red","Medium Red");
		COLOR_MAP.put("Deep Royal Blue","Medium Blue");
		COLOR_MAP.put("Denim Blue","Silver Metal");
		COLOR_MAP.put("Dull Blue","Medium Blue");
		COLOR_MAP.put("Emerald","Medium Green");
		COLOR_MAP.put("Ensemble Red","Medium Red");
		COLOR_MAP.put("Evergreen Green","Medium Green");
		COLOR_MAP.put("Fatigue Green","Medium Green");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Fresh Pink","Light Pink");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("Granite Gray","Light Gray");
		COLOR_MAP.put("Grass Green","Medium Green");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Heather Gray","Light Gray");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Heliconia","Other");
		COLOR_MAP.put("Heliconia Pink","Bright Pink");
		COLOR_MAP.put("Hemi Orange","Medium Orange");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Inboard Blue","Medium Blue");
		COLOR_MAP.put("Indigo Blue","Medium Blue");
		COLOR_MAP.put("Irish Green","Medium Green");
		COLOR_MAP.put("Jade Dome","Medium Green");
		COLOR_MAP.put("Jade Green","Medium Green");
		COLOR_MAP.put("Jade Vine","Light Green");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Kiwi Green","Light Green");
		COLOR_MAP.put("Lapis Blue","Medium Blue");
		COLOR_MAP.put("Lava Red","Medium Red");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Light Pink","Light Pink");
		COLOR_MAP.put("Light Steel Gray","Light Gray");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Magenta","Bright Pink");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Maroon Red","Medium Red");
		COLOR_MAP.put("Metallic","Assorted");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Deep Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Deep Green","Metallic Green");
		COLOR_MAP.put("Metallic Gray","Metallic Gray");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Metallic White","Metallic White");
		COLOR_MAP.put("Metallic Yellow","Metallic Yellow");
		COLOR_MAP.put("Midnight Blue","Medium Blue");
		COLOR_MAP.put("Monaco Blue","Medium Blue");
		COLOR_MAP.put("Mountain Sky Blue","Medium Blue");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Natural Beige","Light Brown");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Neon Red","Bright Red");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Olive Green","Medium Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Orchid Purple","Medium Purple");
		COLOR_MAP.put("Organic Black","Medium Black");
		COLOR_MAP.put("Organic Cinder","Light Brown");
		COLOR_MAP.put("Organic Cinder Gray","Medium Gray");
		COLOR_MAP.put("Organic Dijon Yellow","Medium Yellow");
		COLOR_MAP.put("Organic Galaxy Blue","Medium Blue");
		COLOR_MAP.put("Organic Natural Beige","Medium White");
		COLOR_MAP.put("Organic Ultraviolet Purple","Medium Purple");
		COLOR_MAP.put("Organic White","Medium White");
		COLOR_MAP.put("Oyster White","Medium White");
		COLOR_MAP.put("Papaya Orange","Light Orange");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Platinum","Platinum Metal");
		COLOR_MAP.put("Plum Purple","Medium Purple");
		COLOR_MAP.put("Pomegranate Red","Medium Red");
		COLOR_MAP.put("Powder Blue","Light Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Rainbow","Multi Color");
		COLOR_MAP.put("Raspberry","Medium Red");
		COLOR_MAP.put("Real Red","Medium Red");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Resort Red","Medium Red");
		COLOR_MAP.put("Rose","Medium Red");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Safety Green","Medium Green");
		COLOR_MAP.put("Safety Orange","Bright Orange");
		COLOR_MAP.put("Safety Yellow","Bright Yellow");
		COLOR_MAP.put("Sage Green","Medium Green");
		COLOR_MAP.put("Sailor Blue","Medium Blue");
		COLOR_MAP.put("Sand Beige","Light Brown");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Silver Aluminum","Silver Metal");
		COLOR_MAP.put("Sky Blue","Light Blue");
		COLOR_MAP.put("Slate Gray","Medium Gray");
		COLOR_MAP.put("Sports Gray","Medium Gray");
		COLOR_MAP.put("Stainless","Medium Gray");
		COLOR_MAP.put("Stainless Steel","Silver Metal");
		COLOR_MAP.put("Steel Gray","Medium Gray");
		COLOR_MAP.put("Stone Dust","Other");
		COLOR_MAP.put("Stonedust","Other");
		COLOR_MAP.put("Sunburst Yellow","Medium Yellow");
		COLOR_MAP.put("Sunglow Yellow","Medium Yellow");
		COLOR_MAP.put("Tangy Orange","Medium Orange");
		COLOR_MAP.put("Taupe Heather","Light Brown");
		COLOR_MAP.put("Teal Blue","Medium Blue");
		COLOR_MAP.put("Tech Gray","Medium Gray");
		COLOR_MAP.put("Texas Orange","Medium Orange");
		COLOR_MAP.put("Translucent","Clear");
		COLOR_MAP.put("Translucent Aqua","Light Blue");
		COLOR_MAP.put("Translucent Black","Medium Black");
		COLOR_MAP.put("Translucent Blue","Light Blue");
		COLOR_MAP.put("Translucent Brown","Medium Brown");
		COLOR_MAP.put("Translucent Clear","Clear");
		COLOR_MAP.put("Translucent Green","Light Green");
		COLOR_MAP.put("Translucent Orange","Light Orange");
		COLOR_MAP.put("Translucent Pink","Light Pink");
		COLOR_MAP.put("Translucent Purple","Light Purple");
		COLOR_MAP.put("Translucent Red","Medium Red");
		COLOR_MAP.put("Transparent Blue","Medium Blue");
		COLOR_MAP.put("Transparent Clear","Clear");
		COLOR_MAP.put("Transparent Orange","Light Orange");
		COLOR_MAP.put("Tudor Brown","Medium Brown");
		COLOR_MAP.put("Turquoise Blue","Light Blue");
		COLOR_MAP.put("Uniform Navy","Dark Blue");
		COLOR_MAP.put("Vegas Gold","Gold Metal");
		COLOR_MAP.put("Wasabi Green","Medium Green");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("","");


	}
	public static String getColorGroup(String colorName){
		String colorGroup = COLOR_MAP.get(colorName);
		return colorGroup == null?"Other":colorGroup;
	}
}
