package parser.towelSpecialties;

import java.util.HashMap;
import java.util.Map;

public class TowelSpecQtyAndColorMapping {
	public static Map<Integer, String> priceQuantityMap = new HashMap<>();
	public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	static{
		priceQuantityMap.put(5, "1");
		priceQuantityMap.put(6, "18");
		priceQuantityMap.put(7, "50");
		priceQuantityMap.put(8, "36");
		priceQuantityMap.put(9, "72");
		priceQuantityMap.put(10, "100");
		priceQuantityMap.put(11, "144");
		priceQuantityMap.put(12, "288");
		priceQuantityMap.put(13, "600");
		priceQuantityMap.put(14, "800");
		priceQuantityMap.put(15, "1000");
		priceQuantityMap.put(16, "1500");
		priceQuantityMap.put(17, "3000");
		priceQuantityMap.put(18, "4800");
		priceQuantityMap.put(19, "5000");
		priceQuantityMap.put(20, "8000");
		priceQuantityMap.put(21, "20000");
        
		COLOR_MAP.put("NAME","Color Group");
		COLOR_MAP.put("MULTI COLOR","Multi Color");
		COLOR_MAP.put("WHITE","Medium White");
		COLOR_MAP.put("TURQUOISE STRIPES","Medium Green");
		COLOR_MAP.put("ORANGE STRIPES","Medium Orange");
		COLOR_MAP.put("LIME STRIPES","Bright Green");
		COLOR_MAP.put("ROYAL BLUE STRIPES","Bright Blue");
		COLOR_MAP.put("RED STRIPES","Medium Red");
		COLOR_MAP.put("BROWN","Medium Brown");
		COLOR_MAP.put("LIME GREEN","Bright Green");
		COLOR_MAP.put("ORANGE","Medium Orange");
		COLOR_MAP.put("NATURAL","LIGHT WHITE");
		COLOR_MAP.put("ROYAL BLUE","Bright Blue");
		COLOR_MAP.put("TURQUOISE","Bright Blue");
		COLOR_MAP.put("TURQUOISE","Bright Blue");
		COLOR_MAP.put("YELLOW","Medium Yellow");
		COLOR_MAP.put("RED","Medium Red");
		COLOR_MAP.put("GRAY","Medium Gray");
		COLOR_MAP.put("GREY","Medium Gray");
		COLOR_MAP.put("BLACK","Medium Black");
		COLOR_MAP.put("NAVY BLUE","Dark Blue");
		COLOR_MAP.put("SUNSHINE YELLOW","Medium Yellow");
		COLOR_MAP.put("NAVY","Dark Blue");
		COLOR_MAP.put("TANGERINE","Medium Orange");
		COLOR_MAP.put("FUCHSIA","Medium Pink");
		COLOR_MAP.put("LEMON","Medium Yellow");
		COLOR_MAP.put("PINK","Medium Pink");
		COLOR_MAP.put("FUSCHIA","Medium Pink");
		COLOR_MAP.put("MAROON","Dark Red");
		COLOR_MAP.put("CHOCOLATE","Medium Brown");
		COLOR_MAP.put("FOREST GREEN","Medium Green");
		COLOR_MAP.put("PURPLE","Medium Purple");
		COLOR_MAP.put("ATHLETIC GOLD","Dark Yellow");
		COLOR_MAP.put("CHARCOAL GRAY","Medium Gray");
		COLOR_MAP.put("COASTAL SKY","Medium Blue");
		COLOR_MAP.put("COASTAL NECTARINE","Light Orange");
		COLOR_MAP.put("COASTAL MINT JULEP","Medium Green");
		COLOR_MAP.put("COASTAL PINK","Medium Pink");
		COLOR_MAP.put("COASTAL LILAC","Medium Purple");
		COLOR_MAP.put("ATHLETIC ORANGE","Medium Orange");
		COLOR_MAP.put("CAMEL","Medium Brown");
		COLOR_MAP.put("SILVER GRAY","Medium Gray");
		COLOR_MAP.put("RED-WHITE","Multi Color");
		COLOR_MAP.put("YELLOW-WHITE","Multi Color");
		COLOR_MAP.put("LIME-WHITE","Multi Color");
		COLOR_MAP.put("NAVY-WHITE","Multi Color");
		COLOR_MAP.put("BROWN-TAN","Multi Color");
		COLOR_MAP.put("TANGERINE ORANGE","Medium Orange");
		COLOR_MAP.put("CHOCOLATE BROWN","Dark Brown");
		COLOR_MAP.put("EVERGREEN","Medium Green");
		COLOR_MAP.put("LIGHT BLUE","Light Blue");
		COLOR_MAP.put("BEIGE","IRIDESCENT BROWN");
		COLOR_MAP.put("LIME","Medium Green");
		COLOR_MAP.put("GOLD","Dark Yellow");
		COLOR_MAP.put("JADE","Medium Green");
		COLOR_MAP.put("HUNTER GREEN","Medium Green");
		COLOR_MAP.put("SILVER","Medium Gray");
		COLOR_MAP.put("KELLY GREEN","Medium Green");
		COLOR_MAP.put("BURGUNDY","Dark Red");
		COLOR_MAP.put("RED BACKING","Medium Red");
		COLOR_MAP.put("GRAY BACKING","Medium Gray");
		COLOR_MAP.put("CHARCOAL BACKING","Medium Gray");
		COLOR_MAP.put("SAGE","Medium Green");
		COLOR_MAP.put("ROYAL","Bright Blue");
		COLOR_MAP.put("ATHLETIC GRAY","Medium Gray");
		COLOR_MAP.put("DOVE GRAY","Medium Gray");
		COLOR_MAP.put("MIDNIGHT BLUE","Medium Blue");
		COLOR_MAP.put("SLATE","Medium Gray");
		COLOR_MAP.put("WHITE STRIPE","Medium White");
		COLOR_MAP.put("NAME","group");
		COLOR_MAP.put("CHAMPAGNE","Light Yellow");
		COLOR_MAP.put("EMPIRE BLUE","Blue");
		COLOR_MAP.put("ROYAL BLUE SCRUBBER BORDER","Bright Blue");
		COLOR_MAP.put("FUCSHIA","Pink");
		COLOR_MAP.put("LEMON YELLOW","yellow");
		COLOR_MAP.put("WHITE WITH BEIGE STRIPES","White:Combo:Light Brown");
		COLOR_MAP.put("WHITE WITH NAVY STRIPES","White:Combo:Dark Blue");
		COLOR_MAP.put("EACH WITH BLACK OUTER MESH","Black");
		COLOR_MAP.put("TOWELLIME","Bright Green");
		COLOR_MAP.put("BEIGE/WHITE","Light Brown:Combo:White");
		COLOR_MAP.put("NATURAL WITH POCKETS IN LIME GREEN","White:Combo:Bright Green");
		COLOR_MAP.put("VERTICAL FASHION STRIPES IN NAVY/GREY/WHITE","Dark Blue:Combo:Gray:Secondary:White");
		COLOR_MAP.put("COLORSTURQUOISE/WHITE","Blue:Combo:White");
		COLOR_MAP.put("BAGNATURAL CANVAS OR NAVY CANVAS (SAILCLOTH IS JUTE)","White:Combo:Dark Blue");
		COLOR_MAP.put("NATURAL CANVAS OR NAVY CANVAS (SAILCLOTH IS JUTE)","White:Combo:Dark Blue");
		COLOR_MAP.put("CREAM CARD","White");
		COLOR_MAP.put("LIME GREEN OR ROYAL BLUE TRIM","Bright Green:Combo:Bright Blue");
		COLOR_MAP.put("ORANGE OR ROYAL WITH BLACK BORDER","Orange:Combo:Black=orange with black border,Bright Blue:Combo:Black=royal with black border");
		COLOR_MAP.put("BLACK OR ROYAL BLUE SCRUBBER BORDER","Black:Combo:Blue=orange with black border,Bright Blue:Combo:Blue=royal with black border");
		COLOR_MAP.put("BLUE/WHITE STRIPE OR YELLOW/WHITE STRIPE","Blue:Combo:White=blue/white stripe,Yellow:Combo:White=yellow/white stripe");
		COLOR_MAP.put("ORANGE OR LIME STRIPES","Orange=orange Stripes, Bright Green=lime stripes");
		COLOR_MAP.put("CAMEL OR SILVER GREY","Light Brown=camel, Gray=silver grey");
		COLOR_MAP.put("TURQUOISE OR ORANGE HEMS ON BOTH EDGES OF THE TOWEL","Blue=turquoise hems,Orange=orange hems");
		COLOR_MAP.put("NAVY/WHITE OR BEIGE/WHITE","Dark Blue:Combo:White=navy/white, Light Brown:Combo:White=beige/white");
		COLOR_MAP.put("WHITE WITH RED","White:Combo:Red");
	}
	public static String getPriceQty(int priceIndex){
		return priceQuantityMap.get(priceIndex);
	}
	public static String getColorGroup(String colorName){
		String colorGroup = COLOR_MAP.get(colorName);
		return colorGroup == null ?"Other":colorGroup;
	}

}
