package parser.radious;
import java.util.Map;
import java.util.TreeMap;

public  class RadiousLookupData {
	

	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);

	static{
		
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("White-Aluminum","Multi Color");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Silver Cloud","Medium Gray");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Peach","Medium Orange");
		COLOR_MAP.put("Carnation","Medium Pink");
		COLOR_MAP.put("Blush","Medium Pink");
		COLOR_MAP.put("Rosewood","Medium Pink");
		COLOR_MAP.put("Dusty Rose","Medium Pink");
		COLOR_MAP.put("Bone","Light Brown");
		COLOR_MAP.put("Beige","Light Brown");
		COLOR_MAP.put("Sable","Light Brown");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Walnut","Medium Brown");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Wine","Dark Red");
		COLOR_MAP.put("Bordeaux","Dark Red");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Magenta","Dark Pink");
		COLOR_MAP.put("Hot Pink","Dark Pink");
		COLOR_MAP.put("Raspberry","Dark Pink");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Blueberry","Medium Blue");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Imperial Blue","Medium Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Neo Blue","Medium Blue");
		COLOR_MAP.put("Olive","Medium Green");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Green Apple","Medium Green");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Basil","Medium Green");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Lilac","Light Purple");
		COLOR_MAP.put("Amethyst","Medium Purple");
		COLOR_MAP.put("Plum","Medium Purple");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Grape","Dark Purple");
		COLOR_MAP.put("Cognac","Medium Yellow");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Canary","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Terra Cotta","Dark Orange");
		COLOR_MAP.put("Pumpkin","Dark Orange");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("Hunter","Dark Green");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("New Gray","Medium Gray");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Beige","Medium Brown");
		COLOR_MAP.put("Taupe","Medium Brown");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Rose","Medium Red");
		COLOR_MAP.put("Beige","Medium Brown");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Chablis","Medium Pink");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Beige","Medium Brown");
		COLOR_MAP.put("Silver Gray","Medium Gray");
		COLOR_MAP.put("Cadet Blue","Medium Blue");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Silver Cloud","Silver Metal");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Magenta","Bright Pink");
		COLOR_MAP.put("Silver Gray","Medium Gray");
		COLOR_MAP.put("Lava","Medium Red");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Steel","Silver Metal");
		COLOR_MAP.put("Nebula","Dark Blue");
		COLOR_MAP.put("Monarch","Medium Blue");
		COLOR_MAP.put("Persian Blue","Medium Blue");
		COLOR_MAP.put("Electric Red","Bright Red");
		COLOR_MAP.put("Maroon","Medium Red");
		COLOR_MAP.put("Beach","Light Brown");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Carbon","Medium Black");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Storm","Medium Gray");
		COLOR_MAP.put("Azure Blue","Medium Blue");
		COLOR_MAP.put("Chili Pepper","Medium Red");
		COLOR_MAP.put("Sapphire","Dark Blue");
		COLOR_MAP.put("Maroon","Medium Red");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Steel","Silver Metal");
		COLOR_MAP.put("Nebula","Dark Blue");
		COLOR_MAP.put("Monarch","Medium Blue");
		COLOR_MAP.put("Persian Blue","Medium Blue");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Electric Red","Bright Red");
		COLOR_MAP.put("Maroon","Medium Red");
		COLOR_MAP.put("Beach","Light Brown");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Storm","Medium Gray");
		COLOR_MAP.put("Azure Blue","Medium Blue");
		COLOR_MAP.put("Chili Pepper","Medium Red");
		COLOR_MAP.put("Sapphire","Dark Blue");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Canary","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Flame Red","Medium Red");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Periwinkle","Medium Blue");
		COLOR_MAP.put("Curry","Dark Yellow");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Dusty Rose","Medium Pink");
		COLOR_MAP.put("Canary","Medium Yellow");
		COLOR_MAP.put("Curry","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Dusty Rose","Medium Red");
		COLOR_MAP.put("Flame Red","Medium Red");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Periwinkle","Medium Blue");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Silver","Medium Gray");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("New Gray","Medium Gray");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Gray","Metallic Gray");
		COLOR_MAP.put("Beige","Medium Brown");
		COLOR_MAP.put("Bermuda","Medium Blue");
		COLOR_MAP.put("Ivory","Medium White");
		COLOR_MAP.put("Sand","Medium Brown");
		COLOR_MAP.put("Sandal","Medium Brown");
		COLOR_MAP.put("Bronze","Bronze Metal");
		COLOR_MAP.put("Chocolate","Dark Brown");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Light Forest Green","Light Green");
		COLOR_MAP.put("Light Olive","Light Green");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Flag Red","Medium Red");
		COLOR_MAP.put("Flag Blue","Medium Blue");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Rust","Medium Brown");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Seafoam","Medium Green");
		COLOR_MAP.put("Silver Cloud","Medium Gray");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Peach","Light Orange");
		COLOR_MAP.put("Carnation ","Light Pink");
		COLOR_MAP.put("Bone","Light Yellow");
		COLOR_MAP.put("Beige","Light Brown");
		COLOR_MAP.put("Sable","Light Brown");
		COLOR_MAP.put("Terra Cotta ","Medium Brown");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Blush","Medium Pink");
		COLOR_MAP.put("Dusty Rose","Medium Pink");
		COLOR_MAP.put("Rosewood","Medium Pink");
		COLOR_MAP.put("Raspberry","Dark Pink");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Wine","Dark Red");
		COLOR_MAP.put("Bordeaux","Medium Red");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Magenta","Dark Pink");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Blueberry","Medium Blue");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Navy","Bright Blue");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Imperial Blue","Dark Blue");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Olive","Light Green");
		COLOR_MAP.put("Sage","Light Green");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Basil","Medium Green");
		COLOR_MAP.put("Jade","Dark Green");
		COLOR_MAP.put("Grape","Dark Purple");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Plum","Dark Purple");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Cognac","Dark Yellow");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Canary","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Walnut","Medium Brown");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Neo Blue","Bright Blue");
		COLOR_MAP.put("Green Apple","Medium Green");
		COLOR_MAP.put("Amethyst","Medium Purple");
		COLOR_MAP.put("Pumpkin","Medium Orange");
		COLOR_MAP.put("Lilac","Light Purple");

		
	}
	
	public static Map<String, String> getCOLOR_MAP() {
		return COLOR_MAP;
	}

	
	

}

