package parser.radious;
import java.util.Map;
import java.util.TreeMap;

public  class RadiousLookupData {
	

	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);

	static{
		
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("White-Aluminum","Multi Color");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Silver Cloud 5315u","Medium Gray");
		COLOR_MAP.put("Graphite 5473u","Medium Gray");
		COLOR_MAP.put("Charcoal 11","Medium Gray");
		COLOR_MAP.put("Gray 423u","Medium Gray");
		COLOR_MAP.put("Peach 162u","Medium Orange");
		COLOR_MAP.put("Carnation 487c","Medium Pink");
		COLOR_MAP.put("Blush 501c","Medium Pink");
		COLOR_MAP.put("Rosewood 4995c","Medium Pink");
		COLOR_MAP.put("Dusty Rose 702u","Medium Pink");
		COLOR_MAP.put("Bone 7506u","Light Brown");
		COLOR_MAP.put("Beige 7502u","Light Brown");
		COLOR_MAP.put("Sable 466u","Light Brown");
		COLOR_MAP.put("Brown 476c","Medium Brown");
		COLOR_MAP.put("Walnut 464c","Medium Brown");
		COLOR_MAP.put("Gold 138u","Dark Yellow");
		COLOR_MAP.put("Burgundy 209c","Dark Red");
		COLOR_MAP.put("Wine 7421c","Dark Red");
		COLOR_MAP.put("Bordeaux 202c","Dark Red");
		COLOR_MAP.put("Red 200c","Medium Red");
		COLOR_MAP.put("Magenta 213u","Dark Pink");
		COLOR_MAP.put("Hot Pink 806c","Dark Pink");
		COLOR_MAP.put("Raspberry 7432c","Dark Pink");
		COLOR_MAP.put("Light Blue 629c","Light Blue");
		COLOR_MAP.put("Blueberry 301u","Medium Blue");
		COLOR_MAP.put("Dark Blue 2935u","Dark Blue");
		COLOR_MAP.put("Royal Blue 661c","Bright Blue");
		COLOR_MAP.put("Imperial Blue 280c","Medium Blue");
		COLOR_MAP.put("Navy 295u","Dark Blue");
		COLOR_MAP.put("Teal 321u","Medium Green");
		COLOR_MAP.put("Neo Blue 801c","Medium Blue");
		COLOR_MAP.put("Olive 7493c","Medium Green");
		COLOR_MAP.put("Sage 556u","Medium Green");
		COLOR_MAP.put("Green Apple 369c","Medium Green");
		COLOR_MAP.put("Kelly Green 356c","Medium Green");
		COLOR_MAP.put("Basil 5545c","Medium Green");
		COLOR_MAP.put("Jade 350c","Medium Green");
		COLOR_MAP.put("Purple 2597c","Medium Purple");
		COLOR_MAP.put("Lilac 2635c","Light Purple");
		COLOR_MAP.put("Amethyst 2592c","Medium Purple");
		COLOR_MAP.put("Plum 229u","Medium Purple");
		COLOR_MAP.put("Lavender 516c","Light Purple");
		COLOR_MAP.put("Grape 2627c","Dark Purple");
		COLOR_MAP.put("Cognac 143c","Medium Yellow");
		COLOR_MAP.put("Yellow 7403u","Medium Yellow");
		COLOR_MAP.put("Canary 115c","Medium Yellow");
		COLOR_MAP.put("Orange 172c","Medium Orange");
		COLOR_MAP.put("Terra Cotta 174c","Dark Orange");
		COLOR_MAP.put("Pumpkin 167c","Dark Orange");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Red 186c","Medium Red");
		COLOR_MAP.put("Wine 202c","Medium Red");
		COLOR_MAP.put("Hunter 3305c","Dark Green");
		COLOR_MAP.put("Royal Blue 2935u","Bright Blue");
		COLOR_MAP.put("Gray 423c","Medium Gray");
		COLOR_MAP.put("Neon Blue 801c","Bright Blue");
		COLOR_MAP.put("New Gray 9C","Medium Gray");
		COLOR_MAP.put("Red 201c","Medium Red");
		COLOR_MAP.put("Forest Green 554c","Medium Green");
		COLOR_MAP.put("Beige 726u","Medium Brown");
		COLOR_MAP.put("Taupe 7505u","Medium Brown");
		COLOR_MAP.put("Burgundy 7428c","Dark Red");
		COLOR_MAP.put("Rose 696c","Medium Red");
		COLOR_MAP.put("Beige 7506c","Medium Brown");
		COLOR_MAP.put("Blue 2955c","Medium Blue");
		COLOR_MAP.put("Chablis 693c","Medium Pink");
		COLOR_MAP.put("Gold 142c","Dark Yellow");
		COLOR_MAP.put("Beige 426u","Medium Brown");
		COLOR_MAP.put("Silver Gray 1u","Medium Gray");
		COLOR_MAP.put("Cadet Blue 294c","Medium Blue");
		COLOR_MAP.put("Burgundy 7435c","Dark Red");
		COLOR_MAP.put("Navy 295c","Dark Blue");
		COLOR_MAP.put("Silver Cloud 55315u","Silver Metal");
		COLOR_MAP.put("Charcoal 11c","Medium Gray");
		COLOR_MAP.put("Magenta 231u","Bright Pink");
		COLOR_MAP.put("Silver Gray 1c","Medium Gray");
		COLOR_MAP.put("Lava","Medium Red");
		COLOR_MAP.put("Cinder 11c","Medium Gray");
		COLOR_MAP.put("Charcoal 9c","Medium Gray");
		COLOR_MAP.put("Steel 7c","Silver Metal");
		COLOR_MAP.put("Nebula 282c","Dark Blue");
		COLOR_MAP.put("Monarch 280c","Medium Blue");
		COLOR_MAP.put("Persian Blue 287c","Medium Blue");
		COLOR_MAP.put("Electric Red 200c","Bright Red");
		COLOR_MAP.put("Maroon 202c","Medium Red");
		COLOR_MAP.put("Beach 647c","Light Brown");
		COLOR_MAP.put("Kelly Green 3435c","Bright Green");
		COLOR_MAP.put("Carbon","Medium Black");
		COLOR_MAP.put("Chrome 429c","Chrome Metal");
		COLOR_MAP.put("Storm 424c","Medium Gray");
		COLOR_MAP.put("Azure Blue 287c","Medium Blue");
		COLOR_MAP.put("Chili Pepper 200c","Medium Red");
		COLOR_MAP.put("Sapphire 2757c","Dark Blue");
		COLOR_MAP.put("Maroon202c","Medium Red");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Steel","Silver Metal");
		COLOR_MAP.put("Nebula","Dark Blue");
		COLOR_MAP.put("Monarch","Medium Blue");
		COLOR_MAP.put("Persian Blue","Medium Blue");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Electric Red","Bright Red");
		COLOR_MAP.put("Maroon","Medium Red");
		COLOR_MAP.put("Beach","Light Brown");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Storm","Medium Gray");
		COLOR_MAP.put("Azure Blue","Medium Blue");
		COLOR_MAP.put("Chili Pepper","Medium Red");
		COLOR_MAP.put("Sapphire","Dark Blue");
		COLOR_MAP.put("Charcoal 437u","Medium Gray");
		COLOR_MAP.put("Canary 108c","Medium Yellow");
		COLOR_MAP.put("Orange 173c","Medium Orange");
		COLOR_MAP.put("Flame Red 201c","Medium Red");
		COLOR_MAP.put("Wine 195c","Medium Red");
		COLOR_MAP.put("Indigo 542u","Medium Blue");
		COLOR_MAP.put("Blue 2935u","Medium Blue");
		COLOR_MAP.put("Navy 2965u","Dark Blue");
		COLOR_MAP.put("Kelly Green 341u","Bright Green");
		COLOR_MAP.put("Jade 343u","Medium Green");
		COLOR_MAP.put("Natural 7500u","DARK WHITE");
		COLOR_MAP.put("Brown 1545c","Medium Brown");
		COLOR_MAP.put("Periwinkle 284u","Medium Blue");
		COLOR_MAP.put("Curry 1245u","Dark Yellow");
		COLOR_MAP.put("Moss 555u","Medium Green");
		COLOR_MAP.put("Dusty Rose 493u","Medium Pink");
		COLOR_MAP.put("Canary","Medium Yellow");
		COLOR_MAP.put("Curry","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Dusty Rose","Medium Red");
		COLOR_MAP.put("Flame Red","Medium Red");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Periwinkle","Medium Blue");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Blue 7686c","Medium Blue");
		COLOR_MAP.put("Red 1945c","Medium Red");
		COLOR_MAP.put("Silver","Medium Gray");
		COLOR_MAP.put("Gray 11c","Medium Gray");
		COLOR_MAP.put("Royal 295c","Bright Blue");
		COLOR_MAP.put("New Gray 423u","Medium Gray");
		COLOR_MAP.put("Gray 9c","Medium Gray");
		COLOR_MAP.put("Royal 2935c","Bright Blue");
		COLOR_MAP.put("Royal Blue 295c","Bright Blue");
		COLOR_MAP.put("Royal Blue 295u","Bright Blue");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Gray","Metallic Gray");
		COLOR_MAP.put("Beige","Medium Brown");
		COLOR_MAP.put("Bermuda","Medium Blue");
		COLOR_MAP.put("Ivory","Medium White");
		COLOR_MAP.put("Sand","Medium Brown");
		COLOR_MAP.put("Sandal","Medium Brown");
		COLOR_MAP.put("Bronze","Bronze Metal");
		COLOR_MAP.put("Chocolate","Dark Brown");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Light Forest Green","Light Green");
		COLOR_MAP.put("Light Olive","Light Green");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Flag Red","Medium Red");
		COLOR_MAP.put("Flag Blue","Medium Blue");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Rust","Medium Brown");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Seafoam","Medium Green");
		COLOR_MAP.put("Silver Cloud PMS 5315u","Medium Gray");
		COLOR_MAP.put("Graphite PMS 5473u","Medium Gray");
		COLOR_MAP.put("Charcoal PMS C Gray 11","Dark Gray");
		COLOR_MAP.put("Gray PMS 423c","Medium Gray");
		COLOR_MAP.put("Peach PMS 162u","Light Orange");
		COLOR_MAP.put("Carnation PMS 487c","Light Pink");
		COLOR_MAP.put("Bone PMS 7506u","Light Yellow");
		COLOR_MAP.put("Beige PMS 7502u","Light Brown");
		COLOR_MAP.put("Sable PMS 466u","Light Brown");
		COLOR_MAP.put("Terra Cotta PMS 174c","Medium Brown");
		COLOR_MAP.put("Brown PMS 476c","Medium Brown");
		COLOR_MAP.put("Blush PMS 501c","Medium Pink");
		COLOR_MAP.put("Dusty Rose PMS 702u","Medium Pink");
		COLOR_MAP.put("Rosewood PMS 4995c","Medium Pink");
		COLOR_MAP.put("Raspberry PMS 7432c","Dark Pink");
		COLOR_MAP.put("Burgundy PMS 209c","Dark Red");
		COLOR_MAP.put("Wine PMS 7421c","Dark Red");
		COLOR_MAP.put("Bordeaux PMS 202c","Medium Red");
		COLOR_MAP.put("Red PMS 200c","Medium Red");
		COLOR_MAP.put("Magenta PMS 213u","Dark Pink");
		COLOR_MAP.put("Light Blue PMS 629c","Light Blue");
		COLOR_MAP.put("Blueberry PMS 301u","Medium Blue");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Navy PMS 295u","Bright Blue");
		COLOR_MAP.put("Dark Blue PMS 2935u","Dark Blue");
		COLOR_MAP.put("Imperial Blue PMS 280c","Dark Blue");
		COLOR_MAP.put("Teal PMS 321u","Medium Green");
		COLOR_MAP.put("Olive PMS 7493c","Light Green");
		COLOR_MAP.put("Sage PMS 556u","Light Green");
		COLOR_MAP.put("Kelly Green PMS 356c","Medium Green");
		COLOR_MAP.put("Basil PMS 5545c","Medium Green");
		COLOR_MAP.put("Jade PMS 350c","Dark Green");
		COLOR_MAP.put("Grape PMS 2627c","Dark Purple");
		COLOR_MAP.put("Purple PMS 2597c","Medium Purple");
		COLOR_MAP.put("Plum PMS 229u","Dark Purple");
		COLOR_MAP.put("Lavender PMS 516c","Light Purple");
		COLOR_MAP.put("Cognac PMS 143c","Dark Yellow");
		COLOR_MAP.put("Yellow PMS 7403u","Medium Yellow");
		COLOR_MAP.put("Canary PMS 115c","Medium Yellow");
		COLOR_MAP.put("Orange PMS 172c","Medium Orange");
		COLOR_MAP.put("Walnut PMS 464c","Medium Brown");
		COLOR_MAP.put("Hot Pink PMS 806c","Bright Pink");
		COLOR_MAP.put("Neo Blue PMS 801c","Bright Blue");
		COLOR_MAP.put("Green Apple PMS 369c","Medium Green");
		COLOR_MAP.put("Amethyst PMS 2592c","Medium Purple");
		COLOR_MAP.put("Pumpkin PMS 167c","Medium Orange");
		COLOR_MAP.put("Lilac PMS 2635c","Light Purple");

		
	}
	
	public static Map<String, String> getCOLOR_MAP() {
		return COLOR_MAP;
	}

	
	

}

