package parser.bambam;

import java.util.HashMap;
import java.util.Map;

public class BamBamColorMapping {
  
	public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Any Pantone Color","Assorted");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Cream","Light Yellow");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Royal","Medium Blue");
		COLOR_MAP.put("Any Color","Assorted");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Royal Blue","Medium Blue");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Forest Green","Dark Green");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Light Pink","Light Pink");
		COLOR_MAP.put("Bright Gold","Bright Yellow");
		COLOR_MAP.put("Bright Silver","Bright Gray");
		COLOR_MAP.put("Bright Bronze","Bright Brown");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Any PMS Color","Assorted");
		COLOR_MAP.put("Base Material- White","Medium White");
		COLOR_MAP.put("Base Material - Light Gray","Medium Gray");
		COLOR_MAP.put("Lime Green","Bright Green");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Dark Orange","Dark Orange");
		COLOR_MAP.put("Dark Red","Dark Red");
		COLOR_MAP.put("Sky Blue","Medium Blue");
		COLOR_MAP.put("Bright Orange","Bright Orange");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Lilac","Light Purple");
		COLOR_MAP.put("Base Material - White","Medium White");
		COLOR_MAP.put("Full Color","Assorted");
		COLOR_MAP.put("Antique Silver","Silver Metal");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Black Nickel","Nickel Metal");
		COLOR_MAP.put("Antique Gold","Gold Metal");
		COLOR_MAP.put("Antique Bronze","Bronze Metal");
		COLOR_MAP.put("Metallic Silver","Metallic Gray");
		COLOR_MAP.put("Black Glitter","Medium Black");
		COLOR_MAP.put("Pink Glitter","Medium Pink");
		COLOR_MAP.put("Bronze","Bronze Metal");
		COLOR_MAP.put("Orange-021","Medium Orange");
		COLOR_MAP.put("Red-185","Medium Red");
		COLOR_MAP.put("Purple-2607","Medium Purple");
		COLOR_MAP.put("Maroon-209","Dark Red");
		COLOR_MAP.put("Gray-421","Medium Gray");
		COLOR_MAP.put("Gold-123","Dark Yellow");
		COLOR_MAP.put("Pantone Yellow","Medium Yellow");
		COLOR_MAP.put("Green-363","Medium Green");
		COLOR_MAP.put("Forest Green-560","Dark Green");
		COLOR_MAP.put("Lime Green-375","Bright Green");
		COLOR_MAP.put("Kelly Green-347","Medium Green");
		COLOR_MAP.put("Navy Blue-282","Dark Blue");
		COLOR_MAP.put("Royal Blue-662","Bright Blue");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Light Blue-298","Light Blue");
		COLOR_MAP.put("Brown-469","Medium Brown");
		COLOR_MAP.put("Teal-465","Medium Green");
		COLOR_MAP.put("Pink-230","Medium Pink");
		COLOR_MAP.put("Hot Pink-232","Medium Pink");
		COLOR_MAP.put("Lavender-2415","Medium Purple");
		COLOR_MAP.put("Tan-465","Light Brown");
		COLOR_MAP.put("Turquoise-320","Light Blue");
		COLOR_MAP.put("Olive-371","Dark Green");
		COLOR_MAP.put("Teal-321","Medium Green");
		COLOR_MAP.put("Blue 072","Medium Blue");
		COLOR_MAP.put("Forest Green 350","Dark Green");
		COLOR_MAP.put("Kelly Green 355","Medium Green");
		COLOR_MAP.put("Maroon 202","Dark Red");
		COLOR_MAP.put("Navy Blue 289","Dark Blue");
		COLOR_MAP.put("Orange 021","Medium Orange");
		COLOR_MAP.put("Purple 259","Medium Purple");
		COLOR_MAP.put("Pink 1767","Medium Pink");
		COLOR_MAP.put("Red 186","Medium Red");
		COLOR_MAP.put("Royal Blue 300","Bright Blue");
		COLOR_MAP.put("Silver 877","Medium Gray");
		COLOR_MAP.put("Vegas Gold 872","Dark Yellow");
		COLOR_MAP.put("Yellow 012","Medium Yellow");
		COLOR_MAP.put("Athletic Gold 123","Dark Yellow");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Fuschia","Medium Pink");
		COLOR_MAP.put("Standard PMS Colors","Assorted");
		COLOR_MAP.put("Clear Gold","Clear Yellow");
		COLOR_MAP.put("Clear Silver","Clear Gray");
		COLOR_MAP.put("Clear Glitter","Clear");
		COLOR_MAP.put("Metallic","Silver Metal");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Strawberry","Medium Red");
		COLOR_MAP.put("Blueberry","Medium Blue");
		COLOR_MAP.put("Grape","Medium Purple");
		COLOR_MAP.put("Flag Blue","Medium Blue");
		COLOR_MAP.put("Emerald Green","Medium Green");
		COLOR_MAP.put("Hunter Green","Medium Green");
		COLOR_MAP.put("Spring Green","Medium Green");
		COLOR_MAP.put("Deep Wine","Medium Red");
		COLOR_MAP.put("Yellow Gold","Gold Metal");
		COLOR_MAP.put("Light Purple","Light Purple");
		COLOR_MAP.put("Fuschia Pink","Medium Pink");
		COLOR_MAP.put("Clear Transparent","Clear");
		COLOR_MAP.put("Charcoal","Medium Black");
		COLOR_MAP.put("Woody Camo","Camouflage Brown");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Camel","Light Brown");
		COLOR_MAP.put("Sage Green","Medium Green");
		COLOR_MAP.put("Plum","Medium Purple");
		COLOR_MAP.put("Sienna","Medium Brown");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Gold Metallic","Metallic Yellow");
		COLOR_MAP.put("Grey","Medium Gray");
		COLOR_MAP.put("Factory Off White","Medium White");
		COLOR_MAP.put("Pink 1895","Light Pink");
		COLOR_MAP.put("Pink 212","Medium Pink");
		COLOR_MAP.put("Red 200","Medium Red");
		COLOR_MAP.put("Orange 165","Medium Orange");
		COLOR_MAP.put("Sunny Yellow 106","Medium Yellow");
		COLOR_MAP.put("Yellow 116","Medium Yellow");
		COLOR_MAP.put("Lime Green 375","Light Green");
		COLOR_MAP.put("Kelly Green 347","Medium Green");
		COLOR_MAP.put("Cyan","Medium Blue");
		COLOR_MAP.put("Navy Blue 302","Dark Blue");
		COLOR_MAP.put("Purple 2745","Medium Purple");
		COLOR_MAP.put("Army Green","Medium Green");
		COLOR_MAP.put("Beige","Light Brown");
		COLOR_MAP.put("Coffee","Medium Brown");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Baby Pink","Medium Pink");
		COLOR_MAP.put("Light Lilac","Light Purple");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Fuchsia","Medium Purple");
		COLOR_MAP.put("Athletic Gold","Dark Yellow");
		COLOR_MAP.put("Turquoise","Light Blue");
		COLOR_MAP.put("Nickel","Nickel Metal");
		COLOR_MAP.put("Natural","Medium White");
		COLOR_MAP.put("Army","Medium Green");
		COLOR_MAP.put("Azalea","Light Pink");
		COLOR_MAP.put("Carolina Blue","Medium Blue");
		COLOR_MAP.put("Chocolate","Medium Brown");
		COLOR_MAP.put("Lavender","Medium Purple");
		COLOR_MAP.put("Light Pink","Light Pink");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Sapphire","Medium Blue");
		COLOR_MAP.put("Texas Orange","Medium Orange");
		COLOR_MAP.put("Metallic Gold","Dark Yellow");
		COLOR_MAP.put("Heather","Medium Gray");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Yellow 106","Medium Yellow");
		COLOR_MAP.put("Full Color-CMYK","Other");
		COLOR_MAP.put("Metallic Chrome","Chrome Metal");
		COLOR_MAP.put("Metallic Green","Medium Green");
		COLOR_MAP.put("Metallic Blue","Medium Blue");
		COLOR_MAP.put("Metallic Black","Medium Black");
		COLOR_MAP.put("Metallic Red","Medium Red");
		COLOR_MAP.put("Medium Blue","Medium Blue");
		COLOR_MAP.put("Medium Red","Medium Red");
		COLOR_MAP.put("Medium Green","Medium Green");
		COLOR_MAP.put("Multi Color","Multi Color");
		COLOR_MAP.put("Medium Black","Medium Black");
		COLOR_MAP.put("Solid Gold","Dark Yellow");
		COLOR_MAP.put("Solid Maroon","Dark Red");
		COLOR_MAP.put("Solid Navy Blue","Dark Blue");
		COLOR_MAP.put("Solid Orange","Medium Orange");
		COLOR_MAP.put("Solid Pink","Medium Pink");
		COLOR_MAP.put("Solid Purple","Medium Purple");
		COLOR_MAP.put("Solid Yellow","Medium Yellow");
		COLOR_MAP.put("Sun Yellow","Medium Yellow");
		COLOR_MAP.put("Custom Color","Other");
		COLOR_MAP.put("Army Green - 5767C","Dark Green");
		COLOR_MAP.put("Beige 7506C","Light Brown");
		COLOR_MAP.put("Coffee 439C","Medium Brown");
		COLOR_MAP.put("Dark Gray 11C","Dark Gray");
		COLOR_MAP.put("Green 356C","Medium Green");
		COLOR_MAP.put("Light Gray 877C","Light Gray");
		COLOR_MAP.put("Navy Blue 276C","Dark Blue");
		COLOR_MAP.put("Orange 1575C","Medium Orange");
		COLOR_MAP.put("Purple 2685C","Medium Purple");
		COLOR_MAP.put("Red 186C","Medium Red");
		COLOR_MAP.put("Reflex BlueC","Medium Blue");
		COLOR_MAP.put("Yellow 109C","Medium Yellow");
		COLOR_MAP.put("Red 186U","Medium Red");
		COLOR_MAP.put("Orange 1505U","Medium Orange");
		COLOR_MAP.put("Yellow 102U","Medium Yellow");
		COLOR_MAP.put("Athletic Gold 115U","Dark Yellow");
		COLOR_MAP.put("Dark Green 567","Medium Green");
		COLOR_MAP.put("Purple 2755","Medium Purple");
		COLOR_MAP.put("Maroon 201","Dark Red");
		COLOR_MAP.put("Brown 4695","Medium Brown");
		COLOR_MAP.put("Charcoal 426","Other");
		COLOR_MAP.put("Pink 189U","Medium Pink");
		COLOR_MAP.put("Army Green 5767C","Medium Green");
		COLOR_MAP.put("Beige 756C","Medium White");
		COLOR_MAP.put("Sunny Yellow","Medium Yellow");
		COLOR_MAP.put("Blue Translucent","Medium Blue");
		COLOR_MAP.put("Shiny Nickel","Nickel Metal");
		COLOR_MAP.put("Shiny Gold","Gold Metal");
		COLOR_MAP.put("Translucent","Clear");
		COLOR_MAP.put("Vanilla","Other");
		COLOR_MAP.put("Evergreen","Other");
		COLOR_MAP.put("Royal 286","Bright Blue");
		COLOR_MAP.put("Blue 300","Medium Blue");
		COLOR_MAP.put("Blue 282","Medium Blue");
		COLOR_MAP.put("Blue 285","Medium Blue");
		COLOR_MAP.put("Blue 293","Medium Blue");
		COLOR_MAP.put("Purple 2595","Medium Purple");
		COLOR_MAP.put("Athletic Gold 1235","Dark Yellow");
		COLOR_MAP.put("Teal 3145","Medium Green");
		COLOR_MAP.put("Stock Yarn Colors","Assorted");
		COLOR_MAP.put("Transparent","Clear");
		COLOR_MAP.put("Factory Stock Options","Other");
		COLOR_MAP.put("CMYK-Full Color-Cyan","Light Blue");
		COLOR_MAP.put("CMYK-Full Color-Magenta","Medium Purple");
		COLOR_MAP.put("CMYK-Full Color-Yellow","Medium Yellow");
		COLOR_MAP.put("CMYK-Full Color-Black","Medium Black");
		COLOR_MAP.put("Digital Full Color","Other");
		COLOR_MAP.put("Refex BlueC","Medium Blue");
		COLOR_MAP.put("Medium Gray","Medium Gray");
		COLOR_MAP.put("Base Material - White; Handle/Binding - Natural*","Medium White");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Rainbow Colors","Assorted");
		COLOR_MAP.put("Ever Green","Medium Green");
		COLOR_MAP.put("Kiwi Green","Medium Green");
		COLOR_MAP.put("Peacock Blue","Medium Blue");
		COLOR_MAP.put("Pink Flamingo","Medium Pink");
		COLOR_MAP.put("Sunlight Yellow","Light Yellow");
		COLOR_MAP.put("Tangerine Orange","Medium Orange");
		COLOR_MAP.put("Blue 292", "Medium Blue");
		COLOR_MAP.put("Pink 203", "Medium Pink");
	}
	
	public static String getColorGroup(String colorName){
		return COLOR_MAP.get(colorName);
	}
}
