package parser.goldbond;

import java.util.HashMap;
import java.util.Map;

public class GoldbondColorMapping {
	public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		// NEW COLOR MAPPING
		COLOR_MAP.put("Name","Color Group");
		COLOR_MAP.put("White 100% Recycled Content","Medium White");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Smoke","Medium Gray");
		COLOR_MAP.put("Stainless","Medium Gray");
		COLOR_MAP.put("Lavender","Medium Purple");
		COLOR_MAP.put("Peach","Medium Orange");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Seafoam","Medium Green");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Cream","LIGHT WHITE");
		COLOR_MAP.put("Natural","LIGHT WHITE");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Translucent Chartreuse","Clear Green");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Translucent Pink","Clear Pink");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Green-Pearl","Medium Green");
		COLOR_MAP.put("Translucent Teal","Clear Green");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Lime Green","Metallic Green");
		COLOR_MAP.put("Metallic Purple","Metallic Purple");
		COLOR_MAP.put("Metallic Rose","Metallic Red");
		COLOR_MAP.put("Metallic Silver","Metallic Gray");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Rainbow Color","Multi Color");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Chartreuse","Light Green");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Solid Blue","Medium Blue");
		COLOR_MAP.put("Solid Green","Medium Green");
		COLOR_MAP.put("Solid Red","Medium Red");
		COLOR_MAP.put("Solid Yellow","Medium Yellow");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Gun Metal","Medium Gray");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("White-Black","Medium Black");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Fuchsia","Dark Pink");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Sunshine Red","Medium Red");
		COLOR_MAP.put("Blue with Blue Refill","Medium Blue");
		COLOR_MAP.put("Pearl White","Medium White");
		COLOR_MAP.put("Corporate Blue","Medium Blue");
		COLOR_MAP.put("Lime Green","Bright Green");
		COLOR_MAP.put("4 Color Assorted Pack","Assorted");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Sapphire Blue","Dark Blue");
		COLOR_MAP.put("Ice Clear","Medium White");
		COLOR_MAP.put("Purple Violet","Medium Purple");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Smokey Quartz","Dark Gray");
		COLOR_MAP.put("Granite","Medium Gray");
		COLOR_MAP.put("Arctic Blue","Medium Blue");
		COLOR_MAP.put("Hope Pink","Medium Pink");
		COLOR_MAP.put("Hot Lime","Bright Green");
		COLOR_MAP.put("Ice Blue","Light Blue");
		COLOR_MAP.put("Meadow Green","Medium Green");
		COLOR_MAP.put("Orange Flame","Medium Orange");
		COLOR_MAP.put("Polar White","Medium White");
		COLOR_MAP.put("Corporate Red","Medium Red");
		COLOR_MAP.put("Royal Purple","Medium Purple");
		COLOR_MAP.put("Sandstone","Light Brown");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Sunburst Orange","Dark Orange");
		COLOR_MAP.put("Camouflage","Camouflage Green");
		COLOR_MAP.put("Frosty","Clear");
		COLOR_MAP.put("Camo","Multi Color");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Baseball","Multi Color");
		COLOR_MAP.put("Globe","Medium Blue");
		COLOR_MAP.put("Thunderbolt Blue","Medium Blue");
		COLOR_MAP.put("Neon Blue","Medium Blue");
		COLOR_MAP.put("Neon Purple","Medium Purple");
		COLOR_MAP.put("Neon Rhodamine Red","Medium Red");
		COLOR_MAP.put("Mix-n-Match Colors","Assorted");
		COLOR_MAP.put("Metallic Lime","Metallic Green");
		COLOR_MAP.put("Metallic Orange","Metallic Orange");
		COLOR_MAP.put("Metallic Light Blue","Metallic Blue");
		COLOR_MAP.put("White without Grommet","Medium White");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("No Grommet Black","Medium Black");
		COLOR_MAP.put("No Grommet Dk Green","Dark Green");
		COLOR_MAP.put("No Grommet Gray","Medium Gray");
		COLOR_MAP.put("No Grommet Navy Blue","Dark Blue");
		COLOR_MAP.put("No Grommet Red","Medium Red");
		COLOR_MAP.put("No Grommet Royal Blue","Bright Blue");
		COLOR_MAP.put("Black without Grommet","Medium Black");
		COLOR_MAP.put("Dark Green without Grommet","Dark Green");
		COLOR_MAP.put("Navy Blue without Grommet","Dark Blue");
		COLOR_MAP.put("Red without Grommet (close to PMS 200)","Medium Red");
		COLOR_MAP.put("Royal Blue without Grommet (close to PMS 2146)","Bright Blue");
		COLOR_MAP.put("Build Your Own Kit","Other");
		COLOR_MAP.put("Stainless Steel","Medium Gray");
		COLOR_MAP.put("CUSTOM","Other");
		COLOR_MAP.put("Antique Brass","Brass Metal");
		COLOR_MAP.put("Antique Gold","Gold Metal");
		COLOR_MAP.put("Matte Nickel","Nickel Metal");
		COLOR_MAP.put("Titleist Presentation Box","Other");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Gunmetal","Medium Gray");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Tangerine","Medium Orange");
		COLOR_MAP.put("Frosted","Medium White");
		COLOR_MAP.put("Cobalt Blue","Medium Blue");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Columbia Blue","Medium Blue");
		COLOR_MAP.put("Bright Green","Bright Green");
		COLOR_MAP.put("Bright Pink","Bright Pink");
		COLOR_MAP.put("Corporate Green","Medium Green");
		COLOR_MAP.put("Black Gradient","Medium Black");
		COLOR_MAP.put("Blue Gradient","Medium Blue");
		COLOR_MAP.put("Red Gradient","Medium Red");
		COLOR_MAP.put("Copper","Medium Orange");
		COLOR_MAP.put("Translucent Lime","Clear Green");
		COLOR_MAP.put("Process Blue","Light Blue");
		COLOR_MAP.put("Matte Black","Medium Black");
		COLOR_MAP.put("Multi Color-Camouflage","Multi Color");
		COLOR_MAP.put("Clear Label","Clear");
		COLOR_MAP.put("White Label","Medium White");
		COLOR_MAP.put("Sky Blue","Bright Green");
		COLOR_MAP.put("Cherry","Medium Red");
		COLOR_MAP.put("Citrus","Medium Orange");
		COLOR_MAP.put("Grape","Medium Purple");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("Pomegranate","Dark Red");
		COLOR_MAP.put("Strawberry","Medium Red");
		COLOR_MAP.put("Tropical","Other");
		COLOR_MAP.put("Vanilla","Medium White");
		COLOR_MAP.put("Watermelon","Light Red");
		COLOR_MAP.put("Wild Berry","Medium Red");
		COLOR_MAP.put("Rubine Red","Medium Red");
		COLOR_MAP.put("Red Metallic","Metallic Red");
		COLOR_MAP.put("Space Gray","Dark Gray");
		COLOR_MAP.put("Rose Gold","Medium Pink");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Wood Grain","Medium Brown");
		COLOR_MAP.put("Jacaranda","Medium Purple");
		COLOR_MAP.put("Marina","Medium Blue");
		COLOR_MAP.put("Raspberry","Light Red");
		COLOR_MAP.put("Neon Lime","Bright Green");
		COLOR_MAP.put("Hunter Green","Dark Green");
		COLOR_MAP.put("Polished Gold","Dark Yellow");
		COLOR_MAP.put("Polished Silver","Medium Gray");
		COLOR_MAP.put("Antique Silver","Medium Gray");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Satin Chrome","Chrome Metal");
		COLOR_MAP.put("Steel","Steel Metal");
		COLOR_MAP.put("Black Silver Red","Multi Color");
		COLOR_MAP.put("Black Polkadot","Medium Black");
		COLOR_MAP.put("Black White","Multi Color");
		COLOR_MAP.put("Black/Polka Dot","Medium Black");
		COLOR_MAP.put("Purpe","Medium Purple");
		COLOR_MAP.put("Black/Black","Medium Black");
		COLOR_MAP.put("Gym Red","Medium Red");
		COLOR_MAP.put("Black (001)","Medium Black");
		COLOR_MAP.put("White w/ Pink Packaging","Multi Color");
		COLOR_MAP.put("Brown & White","Multi Color");
		COLOR_MAP.put("Black White Red","Multi Color");
		COLOR_MAP.put("Black Camo","Camouflage Black");
		COLOR_MAP.put("Grey","Medium Gray");
		COLOR_MAP.put("Polka Dot","Other");
		COLOR_MAP.put("White Black Red","Multi Color");
		COLOR_MAP.put("Blue (285)","Medium Blue");
		COLOR_MAP.put("Green (2272)","Medium Green");
		COLOR_MAP.put("Gunmetal (444)","Medium Gray");
		COLOR_MAP.put("Red (200)","Medium Red");
		COLOR_MAP.put("Silver (877)","Silver Metal");
		COLOR_MAP.put("Black w/ Silver Trim (877)","Multi Color");
		COLOR_MAP.put("Green w/ Silver Trim (2265)","Multi Color");
		COLOR_MAP.put("Gunmetal w/ Green Trim (2258)","Multi Color");
		COLOR_MAP.put("Gunmetal w/ Red Trim (187)","Multi Color");
		COLOR_MAP.put("Gunmetal w/ Royal Blue Trim (2144)","Multi Color");
		COLOR_MAP.put("Gunmetal w/ Silver Trim (877)","Multi Color");
		COLOR_MAP.put("Orange w/ Silver Trim (2026)","Multi Color");
		COLOR_MAP.put("Red w/ Silver Trim (200)","Multi Color");
		COLOR_MAP.put("Royal Blue w/ Silver Trim (7685)","Multi Color");
		COLOR_MAP.put("White & Blue w/ Red Trim (187)","Multi Color");
		COLOR_MAP.put("White w/ Black Trim","Multi Color");
		COLOR_MAP.put("Yellow w/ Silver Trim (1225)","Multi Color");
		COLOR_MAP.put("Blue (7686)","Medium Blue");
		COLOR_MAP.put("Green (7743)","Medium Green");
		COLOR_MAP.put("Gunmetal (431)","Medium Gray");
		COLOR_MAP.put("Light Blue (2915)","Light Blue");
		COLOR_MAP.put("Orange (2026)","Medium Orange");
		COLOR_MAP.put("Pink (7424)","Medium Pink");
		COLOR_MAP.put("Red (1795)","Medium Red");
		COLOR_MAP.put("Yellow (115)","Medium Yellow");
		COLOR_MAP.put("Black w/ Silver Trim","Multi Color");
		COLOR_MAP.put("Blue w/ Silver Trim (7685)","Multi Color");
		COLOR_MAP.put("Dark Yellow","Dark Yellow");
		COLOR_MAP.put("Hunter","Dark Green");
		COLOR_MAP.put("Ivory","Medium white");
		COLOR_MAP.put("Khaki","Light Brown");
		COLOR_MAP.put("Titanium","Titanium Metal");
		COLOR_MAP.put("Marlin","Light Blue");
		COLOR_MAP.put("Brick Red","Medium Red");
		COLOR_MAP.put("Slate Blue","Medium Blue");
		COLOR_MAP.put("Stone","medium gray");
		COLOR_MAP.put("Black & Black","Medium black");
		COLOR_MAP.put("Glacier Blue","Light Blue");
		COLOR_MAP.put("Vista Gray","Medium Gray");
		COLOR_MAP.put("Navy (2379)","Dark blue");
		COLOR_MAP.put("Nomad Red (1815)","Medium Red");
		COLOR_MAP.put("Stone (2330)","Medium Gray");
		COLOR_MAP.put("Mocha","Light Brown");
		COLOR_MAP.put("Grey (Cool Gray 9)","Medium Gray");
		COLOR_MAP.put("Lime (361)","Light Green");
		COLOR_MAP.put("Red (1797)","Medium Red");
		COLOR_MAP.put("Blue (286)","Medium Blue");
		COLOR_MAP.put("Lime (2293)","Light Green");
		COLOR_MAP.put("Blue (287)","Medium Blue");
		COLOR_MAP.put("Lime (2421)","Light Green");
		COLOR_MAP.put("Orange (165)","medium Orange");
		COLOR_MAP.put("Red (186)","Medium Red");
		COLOR_MAP.put("Blue (2193)","Medium Blue");
		COLOR_MAP.put("Green (2294)","Medium Green");
		COLOR_MAP.put("Blue (7461)","Medium blue");
		COLOR_MAP.put("Lime (2422)","Light Green");
		COLOR_MAP.put("Pink (2066)","Medium Pink");
		COLOR_MAP.put("Red (194)","Medium Red");
		COLOR_MAP.put("Sun Orange","Medium orange");

		
		
		/*/// OLD COLOR MAPPING
		COLOR_MAP.put("Black with Black Inner and Lid","Medium Black");
		COLOR_MAP.put("White with Black Lid","Medium White");
		COLOR_MAP.put("White Bottle with Black Lid","Medium White");
		COLOR_MAP.put("Silver Black","Silver Metal");
		COLOR_MAP.put("100% Recycled Content","Other");
		COLOR_MAP.put("Black with Silver Trim_Blue Refill","Medium Black");
		COLOR_MAP.put("Translucent Blue_Black Refill","Clear Blue");
		COLOR_MAP.put("Blue-Black Cartridge","Medium Blue");
		COLOR_MAP.put("Arctic Blue/White Liner","Medium Blue");
		COLOR_MAP.put("Translucent Blue Lid","Clear Blue");
		COLOR_MAP.put("Blue Lid","Medium Blue");
		COLOR_MAP.put("Large Black","Medium Black");
		COLOR_MAP.put("Iron Gate","Other");
		COLOR_MAP.put("Clear - 2x8 standard label 12oz","Clear");
		COLOR_MAP.put("Clear - 2x8 standard label 16.9oz","Clear");
		COLOR_MAP.put("Clear - 2x8 standard label 8oz","Clear");
		COLOR_MAP.put("Black with Silver Trim","Medium Black");
		COLOR_MAP.put("Blue Black Refill","Medium Blue");
		COLOR_MAP.put("Black with Silver Barrel","Medium Black");
		COLOR_MAP.put("Blue Lid Blue Tumbler","Medium Blue");
		COLOR_MAP.put("Multi-Color Pack","Multi Color");
		COLOR_MAP.put("Black White Red","Medium Black");
		COLOR_MAP.put("Black/Black Accents","Medium Black");
		COLOR_MAP.put("Blue Lid Black Bottle","Medium Black");
		COLOR_MAP.put("Cherry/White","Medium Red");
		COLOR_MAP.put("White Bottle Green Lid","Medium White");
		COLOR_MAP.put("Blue Lid with White Bottle","Medium White");
		COLOR_MAP.put("Granite Mug with Black Lid","Medium Gray");
		COLOR_MAP.put("Blue Mug with White Lid","Medium Blue");
		COLOR_MAP.put("Blue White","Medium Blue");
		COLOR_MAP.put("Black White","Medium Black");
		COLOR_MAP.put("Blue-Blue Cartridge","Medium Blue");
		COLOR_MAP.put("Medium/Large","Other");
		COLOR_MAP.put("Black Tumbler with Black Liner","Medium Black");
		COLOR_MAP.put("Clear Lid","Clear");
		COLOR_MAP.put("Large White","Medium White");
		COLOR_MAP.put("Green with Silver Trim","Medium Green");
		COLOR_MAP.put("Blue w/ Silver Trim","Medium Blue");
		COLOR_MAP.put("Blue with Silver Barrel","Medium Blue");
		COLOR_MAP.put("Blue Lid Stainless Bottle","Silver Metal");
		COLOR_MAP.put("White with Red Lid","Medium White");
		COLOR_MAP.put("White Bottle with Clear Lid","Medium White");
		COLOR_MAP.put("White Bottle Orange Lid","Medium White");
		COLOR_MAP.put("Red lid with White Bottle","Medium White");
		COLOR_MAP.put("Granite Mug with Blue Lid","Medium Gray");
		COLOR_MAP.put("Green White","Medium Green");
		COLOR_MAP.put("Blue/White Trim_Black Refill","Medium Blue");
		COLOR_MAP.put("Translucent Green_Black Refill","Clear Green");
		COLOR_MAP.put("Red with Black","Medium Red");
		COLOR_MAP.put("Small","Other");
		COLOR_MAP.put("Granite/Black Liner","Medium Gray");
		COLOR_MAP.put("Black w/ Neon Orange Temples","Medium Black");
		COLOR_MAP.put("Small Black","Medium Black");
		COLOR_MAP.put("Smoke Lid Clear Tumbler","Clear");
		COLOR_MAP.put("Chartreuse/Black Accents","Bright Green");
		COLOR_MAP.put("Clear Lid Black Bottle","Medium Black");
		COLOR_MAP.put("Gray with Pearl Inner and Lid","Medium Gray");
		COLOR_MAP.put("White Bottle with Green Lid","Medium White");
		COLOR_MAP.put("White Bottle Purple Lid","Medium White");
		COLOR_MAP.put("Granite Mug with Red Lid","Medium Gray");
		COLOR_MAP.put("Harvest Green/Black Liner","Medium Green");
		COLOR_MAP.put("Pink Pow/White","Bright Pink");
		COLOR_MAP.put("Black w/ Neon Pink Temples","Medium Black");
		COLOR_MAP.put("Xtra Large Black","Medium Black");
		COLOR_MAP.put("Gunmetal with Red Trim","Metallic Gray");
		COLOR_MAP.put("Gunmetal","Metallic Gray");
		COLOR_MAP.put("Red w/ Silver Trim","Medium Red");
		COLOR_MAP.put("Gold/Black Accents","Medium Yellow");
		COLOR_MAP.put("Dk Green without Grommet","Dark Green");
		COLOR_MAP.put("Green/Pearl","Medium Green");
		COLOR_MAP.put("Burgundy/Silver_Blue Refill","Dark Red");
		COLOR_MAP.put("Translucent Orange_Blue Refil","Clear Orange");
		COLOR_MAP.put("White with Black Trim","Medium White");
		COLOR_MAP.put("Hot Lime/White Liner","Bright Green");
		COLOR_MAP.put("Process Blue Lid","Medium Blue");
		COLOR_MAP.put("University Red/White ","Medium Red");
		COLOR_MAP.put("Gunmetal with Royal Blue Trim","Metallic Gray");
		COLOR_MAP.put("Navy Blue without Grommet","Dark Blue");
		COLOR_MAP.put("No Grommet Dk Green","Dark Green");
		COLOR_MAP.put("Lime with White Inner and Lid","Bright Green");
		COLOR_MAP.put("Navy-White","Dark Blue");
		COLOR_MAP.put("Mocha Lid Clear Tumbler","Clear");
		COLOR_MAP.put("Lime Lid Stainless Bottle","Silver Metal");
		COLOR_MAP.put("Pink with Pearl Inner and Lid","Medium Pink");
		COLOR_MAP.put("Red Mug with Red Lid","Medium Red");
		COLOR_MAP.put("Green/White Trim_Blue Refill","Medium Green");
		COLOR_MAP.put("Metallic Panda Tumbler with White Liner","Metallic Black");
		COLOR_MAP.put("Mocha Lid Mocha Tumbler","Light Brown");
		COLOR_MAP.put("Royal Blue-White","Bright Blue");
		COLOR_MAP.put("White with Red Trim","Medium White");
		COLOR_MAP.put("Metallic Red/Black Liner ","Metallic Red");
		COLOR_MAP.put("Black w/ Neon Yellow Temples","Medium Black");
		COLOR_MAP.put("Red with Silver Trim","Medium Red");
		COLOR_MAP.put("White Bottle with Black Lid and Straw","Medium White");
		COLOR_MAP.put("Red-Black Cartridge","Medium Red");
		COLOR_MAP.put("Navy Tumbler with Black Liner","Dark Blue");
		COLOR_MAP.put("Neon Rhodamine Red","Bright Red");
		COLOR_MAP.put("Royal Blue with Silver Trim","Bright Blue");
		COLOR_MAP.put("Orange/Black Liner","Medium Orange");
		COLOR_MAP.put("XXL White","Medium White");
		COLOR_MAP.put("Electric Green/Frost","Bright Green");
		COLOR_MAP.put("Purple w/ Black Refill","Medium Purple");
		COLOR_MAP.put("Smoke Lid Smoke Tumbler","Light Gray");
		COLOR_MAP.put("Silver/Chartreuse Accents","Silver Metal");
		COLOR_MAP.put("Translucent Red/Frost","Clear Red");
		COLOR_MAP.put("White with White Inner and Choice of Lid","Medium White");
		COLOR_MAP.put("Silver/Green Accents","Silver Metal");
		COLOR_MAP.put("Silver/Blue Accents","Silver Metal");
		COLOR_MAP.put("Silver/Orange Accents","Silver Metal");
		COLOR_MAP.put("Silver/Purple Accents","Silver Metal");
		COLOR_MAP.put("Silver/Red Accents","Silver Metal");
		COLOR_MAP.put("Space Gray/ Black Accents","Medium Gray");
		COLOR_MAP.put("Pearl White/Black Accents","Iridescent White");
		COLOR_MAP.put("White Bottle with Translucent Green Lid","Medium White");
		COLOR_MAP.put("White/Blue Trim_Blue Refill","Medium White");
		COLOR_MAP.put("White/Green Trim_Black Refill","Medium White");
		COLOR_MAP.put("White/Red Trim_Blue Refill","Medium White");
		COLOR_MAP.put("Thunderbolt Blue/Black Liner","Medium Blue");
		COLOR_MAP.put("Black/White","Medium Black");
		COLOR_MAP.put("Orange/White","Medium Orange");
		COLOR_MAP.put("Royal/White","Bright Blue");
		COLOR_MAP.put("Rose Gold/Black Accents","Metallic Yellow");
		COLOR_MAP.put("Orange Flame/White Liner","Bright Orange");
		COLOR_MAP.put("Silver/Blue Accents","Silver Metal");
		COLOR_MAP.put("Translucent Purple/Frost ","Clear Purple");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Stainless","Medium Gray");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Sapphire Blue","Dark Blue");
		COLOR_MAP.put("Ice Clear","Medium White");
		COLOR_MAP.put("Lime Green","Bright Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Purple Violet","Medium Purple");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Smokey Quartz","Dark Gray");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Granite","Medium Gray");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Build Your Own Kit","Multi Color");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Titleist Presentation Box","Other");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Cobalt Blue","Medium Blue");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Black Gradient","Medium Black");
		COLOR_MAP.put("Blue Gradient","Medium Blue");
		COLOR_MAP.put("Red Gradient","Medium Red");
		COLOR_MAP.put("Translucent Lime","Clear Green");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Process Blue","Medium Blue");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Multi Color-Camouflage","Multi Color");
		COLOR_MAP.put("Clear Label","Clear");
		COLOR_MAP.put("White Label","White");
		COLOR_MAP.put("Camouflage","Multi Color");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Fuchsia","Dark Pink");
		COLOR_MAP.put("Tangerine","Medium Orange");
		COLOR_MAP.put("Gunmetal","Medium Gray");
		COLOR_MAP.put("Antique Brass","Brass Metal");
		COLOR_MAP.put("Custom","Other");
		COLOR_MAP.put("Natural","Medium White");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Pearl White","Medium White");
		COLOR_MAP.put("Smoke","Medium Gray");
		COLOR_MAP.put("Black-White","Medium White");
		COLOR_MAP.put("Stainless Steel","Medium Gray");
		COLOR_MAP.put("Black without Grommet","Medium Black");
		COLOR_MAP.put("Dark Green without Grommet","Dark Green");
		COLOR_MAP.put("Navy Blue without Grommet","Dark Blue");
		COLOR_MAP.put("Red without Grommet (close to PMS 200)","Medium Red");
		COLOR_MAP.put("Royal Blue without Grommet (close to PMS 2146)","Bright Blue");
		COLOR_MAP.put("No Grommet Black","Medium Black");
		COLOR_MAP.put("No Grommet Dk Green","Dark Green");
		COLOR_MAP.put("No Grommet Gray","Medium Gray");
		COLOR_MAP.put("No Grommet Navy Blue","Dark Blue");
		COLOR_MAP.put("No Grommet Red","Medium Red");
		COLOR_MAP.put("No Grommet Royal Blue","Bright Blue");
		COLOR_MAP.put("White without Grommet","Medium White");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Lime","Metallic Green");
		COLOR_MAP.put("Metallic Orange","Metallic Orange");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Metallic Light Blue","Metallic Blue");
		COLOR_MAP.put("Thunderbolt Blue","Medium Blue");
		COLOR_MAP.put("Neon Blue","Medium Blue");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Purple","Medium Purple");
		COLOR_MAP.put("Neon Rhodamine Red","Medium Red");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Mix-n-Match Colors","Assorted");
		COLOR_MAP.put("Wood Grain","Medium Brown");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Baseball","Multi Color");
		COLOR_MAP.put("Globe","Medium Blue");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Camo","Multi Color");
		COLOR_MAP.put("Translucent Chartreuse","Clear Green");
		COLOR_MAP.put("Translucent Pink","Clear Pink");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Solid Red","Medium Red");
		COLOR_MAP.put("Solid Blue","Medium Blue");
		COLOR_MAP.put("Frosty","Clear");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Sunburst Orange","Medium Orange");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Rose Gold","Medium Pink");
		COLOR_MAP.put("Arctic Blue","Medium Blue");
		COLOR_MAP.put("Hope Pink","Medium Pink");
		COLOR_MAP.put("Hot Lime","Bright Green");
		COLOR_MAP.put("Ice Blue","Light Blue");
		COLOR_MAP.put("Meadow Green","Medium Green");
		COLOR_MAP.put("Orange Flame","Medium Orange");
		COLOR_MAP.put("Polar White","Medium White");
		COLOR_MAP.put("Corporate Red","Medium Red");
		COLOR_MAP.put("Royal Purple","Medium Purple");
		COLOR_MAP.put("Sandstone","Light Brown");
		COLOR_MAP.put("4 Color Assorted Pack","Assorted");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Corporate Blue","Medium Blue");
		COLOR_MAP.put("Chartreuse","Medium Green");
		COLOR_MAP.put("Blue with Blue Refill","Medium Blue");
		COLOR_MAP.put("Sunshine Red","Medium Red");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("White-Black","Medium Black");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Gun Metal","Medium Gray");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Metallic Silver","Metallic Gray");
		COLOR_MAP.put("Solid Green","Medium Green");
		COLOR_MAP.put("Solid Yellow","Medium Yellow");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Rainbow Color","Multi Color");
		COLOR_MAP.put("Metallic Lime Green","Metallic Green");
		COLOR_MAP.put("Metallic Purple","Metallic Purple");
		COLOR_MAP.put("Metallic Rose","Metallic Red");
		COLOR_MAP.put("Translucent Teal","Clear Green");
		COLOR_MAP.put("Green-Pearl","Medium Green");
		COLOR_MAP.put("Cream","LIGHT WHITE");
		COLOR_MAP.put("Lavender","Medium Purple");
		COLOR_MAP.put("Peach","Medium Orange");
		COLOR_MAP.put("Seafoam","Medium Green");
		COLOR_MAP.put("White 100% Recycled Content","Medium White");
		COLOR_MAP.put("Matte Black","Medium Black");
		COLOR_MAP.put("Bright Green","Bright Green");
		COLOR_MAP.put("Bright Pink","Bright Pink");
		COLOR_MAP.put("Columbia Blue","Medium Blue");
		COLOR_MAP.put("Cherry","Medium Red");
		COLOR_MAP.put("Citrus","Medium Orange");
		COLOR_MAP.put("Grape","Medium Purple");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("Pomegranate","Light Purple");
		COLOR_MAP.put("Strawberry","Medium Red");
		COLOR_MAP.put("Tropical","Other");
		COLOR_MAP.put("Vanilla","Medium White");
		COLOR_MAP.put("Vanilla-Mint","Medium White");
		COLOR_MAP.put("Watermelon","Medium Pink");
		COLOR_MAP.put("Wild Berry","Medium Purple");
		COLOR_MAP.put("White with Pink Packaging","Medium White:Combo:Medium Pink");
		COLOR_MAP.put("Sky Blue","Bright Green");
		COLOR_MAP.put("Charcoal Orange","Medium Orange");
		COLOR_MAP.put("Copper","Medium Orange");
		COLOR_MAP.put("Corporate Green","Medium Green");
		COLOR_MAP.put("Frosted","Medium White");
		COLOR_MAP.put("Rubine Red","Medium Red");
		COLOR_MAP.put("Red Metallic","Metallic Red");
		COLOR_MAP.put("Antique Gold","Gold Metal");
		COLOR_MAP.put("Matte Nickel","Nickel Metal");
		COLOR_MAP.put("Space Gray","Medium Gray");
		COLOR_MAP.put("Jacaranda","Medium Purple");
		COLOR_MAP.put("Marina","Medium Blue");
		COLOR_MAP.put("Raspberry","Light Red");
		COLOR_MAP.put("Neon Lime","Bright Green");
		COLOR_MAP.put("Black with Black Inner and Lid","Black");
		COLOR_MAP.put("Clear - 2x8 standard label 12oz","Clear");
		COLOR_MAP.put("Translucent Green_Black Refill","Green");*/

	}
	public static String getColorGroup(String colorName){
		return COLOR_MAP.get(colorName);
	}
}
