package parser.goldstarcanada;

import java.util.Map;
import java.util.TreeMap;

public class GoldstartCanadaApplicationConstatnt {

	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
	
    static {
   /* 	
    	COLOR_MAP.put("Blue","Medium Blue");
    	COLOR_MAP.put("Red","Medium Red");
    	COLOR_MAP.put("Black","Medium Black");
    	COLOR_MAP.put("Assorted Colors","Assorted");
    	COLOR_MAP.put("Burgundy","Dark Red");
    	COLOR_MAP.put("Satin Silver Metallic","Silver Metal");
    	COLOR_MAP.put("Light Blue","Light Blue");
    	COLOR_MAP.put("Yellow","Medium Yellow");
    	COLOR_MAP.put("Pink","Medium Pink");
    	COLOR_MAP.put("Green","Medium Green");
    	COLOR_MAP.put("purple","Medium Purple");
    	COLOR_MAP.put("orange","Medium Orange");
    	COLOR_MAP.put("moss green","Medium Green");
    	COLOR_MAP.put("bronze","Bronze Metal");
    	COLOR_MAP.put("silver","Silver Metal");
    	COLOR_MAP.put("lime green","Bright Green");
    	COLOR_MAP.put("dark red","Dark Red");
    	COLOR_MAP.put("Gunmetal Gray","Medium Gray");
    	COLOR_MAP.put("Tean Green","Medium Green");
    	COLOR_MAP.put("Burgundy Red Trim","Dark Red");
    	COLOR_MAP.put("Brown","Medium Brown");
    	COLOR_MAP.put("Dark Blue","Dark Blue");
    	COLOR_MAP.put("Gun metal","Medium Gray");
    	COLOR_MAP.put("Teal Green","Medium Green");
    	COLOR_MAP.put("Magenta Pink","Medium Pink");
    	COLOR_MAP.put("Navy Blue","Dark Blue");
    	COLOR_MAP.put("Assorted","Assorted");
    	COLOR_MAP.put("White","Medium White");
    	COLOR_MAP.put("Gray","Medium Gray");
    	COLOR_MAP.put("Royal Blue","Bright Blue");
    	COLOR_MAP.put("Maroon","Dark Red");
    	COLOR_MAP.put("Bright Yellow","Bright Yellow");
    	COLOR_MAP.put("Dark Green","Dark Green");
    	COLOR_MAP.put("Natural","DARK WHITE");
    	COLOR_MAP.put("Assortment","Assorted");
    	COLOR_MAP.put("Brick","Medium Red");
    	COLOR_MAP.put("Navy","Dark Blue");
    	COLOR_MAP.put("Baby Pink","Light Pink");
    	COLOR_MAP.put("Turquoise","Light Green");
    	COLOR_MAP.put("Lilac","Medium Purple");
    	COLOR_MAP.put("Seafoam","Medium Green");
    	COLOR_MAP.put("Plum","Dark Purple");
    	COLOR_MAP.put("Periwinkle","Light Purple");
    	COLOR_MAP.put("Raspberry","Medium Red");
    	COLOR_MAP.put("Butter","Medium Yellow");
    	COLOR_MAP.put("Olive","Dark Green");
    	COLOR_MAP.put("Celery","Light Green");
    	COLOR_MAP.put("Lime","Light Green");
    	COLOR_MAP.put("Dark Yellow","Dark Yellow");
    	COLOR_MAP.put("Emerald Green","Medium Green");
    	COLOR_MAP.put("Gold","Gold Metal");
    	COLOR_MAP.put("Neon Orange","Bright Orange");
    	COLOR_MAP.put("Neon Yellow","Bright Yellow");
    	COLOR_MAP.put("Clear","Clear");
    	COLOR_MAP.put("Champagne","Medium White");
    	COLOR_MAP.put("Aqua Blue","Light Blue");
    	COLOR_MAP.put("Rainbow","Multi Color");
    	COLOR_MAP.put("Opal","Medium White");
    	COLOR_MAP.put("Silver Glitter","Silver Metal");
    	COLOR_MAP.put("Blue-Light Blue","Multi Color");
    	COLOR_MAP.put("Purple-Pink","Multi Color");
    	COLOR_MAP.put("Orange-Yellow","Multi Color");
    	COLOR_MAP.put("Green-Lime","Multi Color");
    	COLOR_MAP.put("Red-Orange","Multi Color");
    	COLOR_MAP.put("Pastel Pink","Light Pink");
    	COLOR_MAP.put("Pastel Green","Light Green");
    	COLOR_MAP.put("Pastel Yellow","Light Yellow");
    	COLOR_MAP.put("Pastel Blue","Light Blue");
    	COLOR_MAP.put("Lt Blue","Light Blue");
    	COLOR_MAP.put("Natural Bamboo","Light Brown");
    	COLOR_MAP.put("Neon Pink","Bright Pink");
    	COLOR_MAP.put("Neon Green","Bright Green");
    	COLOR_MAP.put("Razzle-Dazzle Rainbow","Multi Color");
    	COLOR_MAP.put("Fire and Ice","Multi Color");
    	COLOR_MAP.put("Spectrum","Multi Color");
    	COLOR_MAP.put("Rainbow Pink","Medium Pink");
    	COLOR_MAP.put("Burgundy Red","Dark Red");
    	COLOR_MAP.put("Gunmetal Gray","Metallic Gray");
    	COLOR_MAP.put("Brick Red","Dark Red");
    	COLOR_MAP.put("Taupe","Medium Purple");
    	COLOR_MAP.put("Indigo","Dark Blue");
    	COLOR_MAP.put("Steel","Dark Gray");
    	COLOR_MAP.put("Rainbow Blue","Medium Blue");
    	COLOR_MAP.put("Black Grip","Medium Black");
    	COLOR_MAP.put("Dark Gray","Dark Gray");
    	COLOR_MAP.put("Bright Green","Bright Green");
    	COLOR_MAP.put("Chrome","Other");
    	COLOR_MAP.put("Natural Beige","Other");*/

    	COLOR_MAP.put("White","Medium White");//Sport canada //
    	COLOR_MAP.put("Navy Blue","Dark Blue");
    	COLOR_MAP.put("Royal Blue","Bright Blue");
    	COLOR_MAP.put("Red","Medium Red");
    	COLOR_MAP.put("Purple","Medium Purple");
    	COLOR_MAP.put("Forest Green","Dark Green");
    	COLOR_MAP.put("Black","Medium Black");
    	COLOR_MAP.put("Gold","Gold Metal");
    	COLOR_MAP.put("Copper","Copper Metal");
    	COLOR_MAP.put("Baby Blue","Light Blue");
    	COLOR_MAP.put("Orange","Medium Orange");
    	COLOR_MAP.put("Pink","Medium Pink");
    	COLOR_MAP.put("Forrest Green","Dark Green");
    	COLOR_MAP.put("Kelly Green","Bright Green");
    	COLOR_MAP.put("Athletic Gold","Gold Metal");
    	COLOR_MAP.put("Gray","Medium Gray");
    	COLOR_MAP.put("Burgundy","Dark Red");
    	COLOR_MAP.put("Any Color","Assorted");
    	COLOR_MAP.put("Full color","Multi Color");
    	COLOR_MAP.put("Yellow","Medium Yellow");
    	COLOR_MAP.put("Dark Gray","Dark Gray");
    	COLOR_MAP.put("Light Gray","Light Gray");
    	COLOR_MAP.put("All Colors","Assorted");
    	COLOR_MAP.put("Other Colors","Assorted");
    	COLOR_MAP.put("Light Blue","Light Blue");
    	COLOR_MAP.put("Light Green","Light Green");
    	COLOR_MAP.put("Light Pink","Light Pink");
    	COLOR_MAP.put("Silver","Silver Metal");
    	COLOR_MAP.put("Royal","Medium Blue");
    	COLOR_MAP.put("Clear","Clear");
    	COLOR_MAP.put("Frosted","Clear");
    	COLOR_MAP.put("Green","Medium Green");
    	COLOR_MAP.put("Blue","Medium Blue");
    	COLOR_MAP.put("Navy","Dark Blue");
    	COLOR_MAP.put("Translucent","Clear");
    	COLOR_MAP.put("Raspberry","Medium Red");
    	COLOR_MAP.put("Custom Colors","Assorted");
    	COLOR_MAP.put("Translucent Purple","Bright Purple");
    	COLOR_MAP.put("Translucent Red","Bright Red");
    	COLOR_MAP.put("Translucent Green","Bright Green");
    	COLOR_MAP.put("Translucent Blue","Bright Blue");
    	COLOR_MAP.put("Trans Red","Medium Red");
    	COLOR_MAP.put("Trans Blue","Medium Blue");
    	COLOR_MAP.put("Full Color Process","Multi Color");
    	COLOR_MAP.put("Brown","Medium Brown");
    	COLOR_MAP.put("Trans Purple","Light Purple");
    	COLOR_MAP.put("Trans Green","Light Green");
    	COLOR_MAP.put("Frosted Cap","Clear");
    	COLOR_MAP.put("Green Cap","Medium Green");
    	COLOR_MAP.put("Navy Cap","Dark Blue");
    	COLOR_MAP.put("Black Cap","Medium Black");
    	COLOR_MAP.put("Royal Cap","Bright Blue");
    	COLOR_MAP.put("Pink Cap","Medium Pink");
    	COLOR_MAP.put("Orange Cap","Medium Orange");
    	COLOR_MAP.put("Red Cap","Medium Red");
    	COLOR_MAP.put("Yellow Cap","Medium Yellow");
    	COLOR_MAP.put("Purple Cap","Medium Purple");
    	COLOR_MAP.put("All Colors (No Metallic)","Assorted");
    	COLOR_MAP.put("Metallic Gold","Gold Metal");
    	COLOR_MAP.put("Metallic Silver","Silver Metal");
    	COLOR_MAP.put("Neon Green","Bright Green");
    	COLOR_MAP.put("All Colors ( No Metallic)","Assorted");
    	COLOR_MAP.put("Hot Pink","Medium Pink");
    	COLOR_MAP.put("Assorted","Assorted");


	}


}
