package parser.cb;

import java.util.Map;
import java.util.TreeMap;

public class CBlookup {
	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);

	static{
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Bright White","Bright White");
		COLOR_MAP.put("Pistol","Medium Gray");
		COLOR_MAP.put("Dark Navy","Dark Blue");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Onyx","Medium Black");
		COLOR_MAP.put("Cardinal Red","Medium Red");
		COLOR_MAP.put("Valor","Medium Purple");
		COLOR_MAP.put("Atlas","Medium Blue");
		COLOR_MAP.put("Tour Blue","Bright Blue");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Loft","Medium Green");
		COLOR_MAP.put("Refresh","Dark Pink");
		COLOR_MAP.put("Orange Burst","Medium Orange");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Sea Blue","Medium Blue");
		COLOR_MAP.put("Bayou","Medium Blue");
		COLOR_MAP.put("Rope - RP","Light Brown");
		COLOR_MAP.put("Sea Blue - SBL","Medium Blue");
		COLOR_MAP.put("Sunflower - SF","Medium Yellow");
		COLOR_MAP.put("Navy Blue - NVBU","Dark Blue");
		COLOR_MAP.put("Gray Melange - GMG","Medium Gray");
		COLOR_MAP.put("Burgundy - BRG","Dark Red");
		COLOR_MAP.put("Oxide","Light Gray");
		COLOR_MAP.put("Navy Blue Heather","Dark Blue");
		COLOR_MAP.put("Athletic Gray Heather","Light Gray");
		COLOR_MAP.put("Charcoal Heather","Medium Gray");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Ribbon Pink","Medium Pink");
		COLOR_MAP.put("Hunter","Dark Green");
		COLOR_MAP.put("Seaport","Light Blue");
		COLOR_MAP.put("Chutney","Dark Red");
		COLOR_MAP.put("College Purple","Medium Purple");
		COLOR_MAP.put("Midnigt Green","Medium Green");
		COLOR_MAP.put("Atlas Blue","Light Blue");
		COLOR_MAP.put("Titan","Medium Gray");
		COLOR_MAP.put("French Blue","Medium Blue");
		COLOR_MAP.put("Reflect","Bright Yellow");
		COLOR_MAP.put("Solid Navy Blue","Dark Blue");
		COLOR_MAP.put("Solid Black","Medium Black");
		COLOR_MAP.put("Circuit","Gold Metal");
		COLOR_MAP.put("Steelhead","Medium Blue");
		COLOR_MAP.put("Jasper","Medium Blue");
		COLOR_MAP.put("Coho","Medium Pink");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Titan","Medium Gray");
		COLOR_MAP.put("Intense Red","Medium Red");
		COLOR_MAP.put("Dusty Green","Medium Green");
		COLOR_MAP.put("Bottle Green","Medium Green");
		COLOR_MAP.put("Camouflage","Multi Color");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Off White","Medium White");
		COLOR_MAP.put("Midnight Denim","Dark Blue");
		COLOR_MAP.put("Monarch","Light Brown");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Deep Red","Medium Red");
		COLOR_MAP.put("Digital","Medium Blue");
		COLOR_MAP.put("Cilantro","Medium Green");
		COLOR_MAP.put("Putting Green","Light Green");
		COLOR_MAP.put("College Orange","Medium Orange");
		COLOR_MAP.put("College Gold","Dark Yellow");
		COLOR_MAP.put("Putting Green","Medium Green");
		COLOR_MAP.put("Ribbon Pink","Medium Pink");
		COLOR_MAP.put("Blue","Light Blue");
		COLOR_MAP.put("Pale Yellow","Light Yellow");
		COLOR_MAP.put("Sea Green","Light Green");
		COLOR_MAP.put("Atomic","Medium Orange");
		COLOR_MAP.put("Midnight Green","Dark Green");
		COLOR_MAP.put("Lemon","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Light Green - LIG","Light Green");
		COLOR_MAP.put("Stone","Light Brown");
		COLOR_MAP.put("Bordeaux","Dark Red");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Lotus","Medium Yellow");
		COLOR_MAP.put("Cardinal Red","Medium Red");
		COLOR_MAP.put("Chutney","Dark Red");
		COLOR_MAP.put("College Purple","Medium Purple");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Darkest Red","Dark Red");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Dark Navy","Dark Blue");
		COLOR_MAP.put("Deep Red","Medium Red");
		COLOR_MAP.put("Gray Melange","Medium Gray");
		COLOR_MAP.put("Tuscany","Medium Yellow");
		COLOR_MAP.put("Elemental Gray","Medium Gray");
		COLOR_MAP.put("Scorch","Medium Orange");
		COLOR_MAP.put("Locker","Medium Gray");
		COLOR_MAP.put("Bordeaux","Dark Red");
		COLOR_MAP.put("Bittersweet","Medium Brown");
		COLOR_MAP.put("Apple Green","Medium Green");
		COLOR_MAP.put("Cobalt","Medium Blue");
		COLOR_MAP.put("Red Heather","Medium Red");
		COLOR_MAP.put("Charcoal Heather","Medium Gray");
		COLOR_MAP.put("Navy Heather","Dark Blue");
		COLOR_MAP.put("Deep Water","Medium Blue");
		COLOR_MAP.put("Soft Orange","Medium Orange");
		COLOR_MAP.put("Ash","Light Gray");
		COLOR_MAP.put("Dark Heather","Dark Gray");
		COLOR_MAP.put("Jet Black","Medium Black");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Pale Pink","Light Pink");
		COLOR_MAP.put("Sangria","Medium Pink");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Blue Lake","Medium Blue");
		COLOR_MAP.put("Lime","Light Green");
		COLOR_MAP.put("Kelly","Medium Green");
		COLOR_MAP.put("Bright Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Dark Chocolate Brown","Dark Brown");
		COLOR_MAP.put("Heather Red","Medium Red");
		COLOR_MAP.put("Cardinal","Medium Red");
		COLOR_MAP.put("Clover Green","Medium Green");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Heather Royal","Dark Blue");
		COLOR_MAP.put("Heather Navy","Dark Blue");
		COLOR_MAP.put("Ash","Light Gray");
		COLOR_MAP.put("Athletic Gray Heather","Light Gray");
		COLOR_MAP.put("Dark Heather","Dark Gray");
		COLOR_MAP.put("Jet Black","Medium Black");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Pale Pink","Light Pink");
		COLOR_MAP.put("Sangria","Medium Pink");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Blue Lake","Medium Blue");
		COLOR_MAP.put("Tour Blue","Medium Blue");
		COLOR_MAP.put("Lime","Light Green");
		COLOR_MAP.put("Kelly","Medium Green");
		COLOR_MAP.put("Bright Neon Yellow - BNY","Bright Yellow");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Silver","Medium Gray");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Sand","Light Brown");
		COLOR_MAP.put("Heather Dark Chocolate","Dark Brown");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Heather Maroon","Dark Red");
		COLOR_MAP.put("Heather Purple","Medium Purple");
		COLOR_MAP.put("Candy Pink","Medium Pink");
		COLOR_MAP.put("Heather Sangria","Medium Pink");
		COLOR_MAP.put("Faded Blue","Light Blue");
		COLOR_MAP.put("Aquatic Blue","Medium Blue");
		COLOR_MAP.put("Sapphire","Dark Blue");
		COLOR_MAP.put("Steel Blue","Medium Blue");
		COLOR_MAP.put("Olive","Dark Green");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Dark Chocolate Brown","Dark Brown");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Cardinal","Medium Red");
		COLOR_MAP.put("Silver","Medium Gray");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Heather Dark Chocolate","Medium Brown");
		COLOR_MAP.put("Heather Red","Medium Red");
		COLOR_MAP.put("Heather Purple","Medium Purple");
		COLOR_MAP.put("Steel Blue","Medium Blue");
		COLOR_MAP.put("Clover Green","Medium Green");
		COLOR_MAP.put("Olive","Dark Green");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Heather Navy","Dark Blue");
		COLOR_MAP.put("Heather Royal","Bright Blue");
		COLOR_MAP.put("Liberty Navy","Dark Blue");
		COLOR_MAP.put("Gala","Medium Blue");
		COLOR_MAP.put("Castle","Light Brown");
		COLOR_MAP.put("Tour Blue Heather","Bright Blue");
		COLOR_MAP.put("Midnight Green Heather","Medium Green");
		COLOR_MAP.put("Orange Burst Heather","Medium Orange");
		COLOR_MAP.put("Cilantro Heather","Medium Green");
		COLOR_MAP.put("Digital Heather","Medium Blue");
		COLOR_MAP.put("Cardinal Red Heather","Medium Red");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Iron","Light Gray");
		COLOR_MAP.put("Light Grey","Medium Gray");
		COLOR_MAP.put("Charcoal Heather","Dark Gray");
		COLOR_MAP.put("Red Heather","Medium Red");
		COLOR_MAP.put("Navy Heather","Dark Blue");
		COLOR_MAP.put("Bottle Green Heather","Medium Green");
		COLOR_MAP.put("Charcoal Melange","Medium Gray");
		COLOR_MAP.put("Venice","Medium Blue");
		COLOR_MAP.put("Solid Venice","Medium Blue");
		COLOR_MAP.put("Mid-Gray Heather","Medium Gray");
		COLOR_MAP.put("Mid Gray Heather","Medium Gray");
		COLOR_MAP.put("British Tan","Light Brown");
		COLOR_MAP.put("Shade","Medium Black");
		COLOR_MAP.put("Vineyard","Dark Green");
		COLOR_MAP.put("Charge","Medium Green");
		COLOR_MAP.put("Complex","Medium Blue");
		COLOR_MAP.put("Galaxy","Medium Yellow");
		COLOR_MAP.put("Gravel","Medium Gray");
		COLOR_MAP.put("Legacy Red","Medium Red");
		COLOR_MAP.put("Link","Medium Gray");
		COLOR_MAP.put("Liberty Navy Heather","Dark Blue");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Botanic","Dark Red");
		COLOR_MAP.put("Shine","Medium Blue");
		COLOR_MAP.put("Snorkel Blue","Medium Blue");
		COLOR_MAP.put("Savannah","Medium Brown");
		COLOR_MAP.put("Fog Heather","Medium Gray");
		COLOR_MAP.put("Hunter Heather","Dark Green");
		COLOR_MAP.put("High Vis Orange","Bright Orange");
		COLOR_MAP.put("High Vis Yellow","Bright Yellow");
		COLOR_MAP.put("Pistol","Medium Black");
		COLOR_MAP.put("Digital Blue","Medium Blue");
		COLOR_MAP.put("Elemental Grey","Medium Gray");
		COLOR_MAP.put("Liberty Navy Blue","Dark Blue");
		COLOR_MAP.put("College Orange Heather","Medium Orange");
		COLOR_MAP.put("Anthracite Melange","Medium Gray");
		COLOR_MAP.put("Blood Orange","Medium Orange");
		COLOR_MAP.put("Blue Melange","Medium Blue");
		COLOR_MAP.put("Polished","Medium Gray");
		COLOR_MAP.put("Oxide Heather","Medium Gray");
		COLOR_MAP.put("Grey","Medium Gray");

		
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Translucent Black","Clear Black");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Translucent Pink","Clear Pink");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Teal","Clear Green");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Translucent Frost","Clear White");
		COLOR_MAP.put("Custom","Other");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Full Color","Multi Color");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Metallic Gold","Metallic Yellow");
		COLOR_MAP.put("Metallic Silver","Silver Metal");
		COLOR_MAP.put("Camouflage","Camouflage Green");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Rainbow","Multi Color");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Camel","Light Brown");
		COLOR_MAP.put("Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Sage","Light Green");
		COLOR_MAP.put("Tin","Medium Gray");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Translucent Black (Smoke)","Clear Black");
		COLOR_MAP.put("Clear (Frost)","Clear");
		COLOR_MAP.put("Cream","Medium White");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("Royal Blue","Medium Blue");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Forest Green","Dark Green");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Glow in the Dark","Medium Green");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Golf","Medium Green");
		COLOR_MAP.put("Transparent Frost","Clear White");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Heather","Light Gray");
		COLOR_MAP.put("Cocoa Brown","Medium Brown");
		COLOR_MAP.put("Frost","Clear White");
		COLOR_MAP.put("Translucent Clear","Clear");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Clear","Clear");
		COLOR_MAP.put("Metallic Camouflage","Metallic Green");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Metallic Orange","Metallic Orange");
		COLOR_MAP.put("Metallic Pink","Metallic Pink");
		COLOR_MAP.put("Metallic Purple","Metallic Purple");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Metallic White","Metallic White");
		COLOR_MAP.put("Metallic Yellow","Metallic Yellow");
		COLOR_MAP.put("Frosted","Medium White");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Carolina Blue","Medium Blue");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Bright Carolina Blue","Bright Blue");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Tortoise Shell","Medium Brown");
		COLOR_MAP.put("Wood Grain","Medium Brown");
		COLOR_MAP.put("Green Camo","Camouflage Green");
		COLOR_MAP.put("Translucent Glow in the Dark","Clear Green");
		COLOR_MAP.put("Translucent Maroon","Clear Red");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Translucent White","Clear White");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Magenta","Dark Pink");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Turquoise","Bright Blue");
		COLOR_MAP.put("Cool Gray","Medium Gray");
		COLOR_MAP.put("Mixed Camo","Camouflage Green");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Pure White","Medium White");
		COLOR_MAP.put("Soft Yellow","Light Yellow");
		COLOR_MAP.put("Soft Pink","Light Pink");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Fuchsia","Bright Pink");
		COLOR_MAP.put("Translucent","Clear");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Berry","Dark Pink");
		COLOR_MAP.put("Light Wood","Light Brown");
		COLOR_MAP.put("Medium Wood","Medium Brown");
		COLOR_MAP.put("Dark Wood","Dark Brown");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Wood Tone","Medium Brown");
		COLOR_MAP.put("Titanium","Titanium Metal");
		COLOR_MAP.put("Other","Multi Color");
		COLOR_MAP.put("Titanium Gray","Medium Gray");
		COLOR_MAP.put("Cocoa","Medium Brown");
		COLOR_MAP.put("Blue (Blueberry)","Medium Blue");
		COLOR_MAP.put("Pink (Bubblegum)","Medium Pink");
		COLOR_MAP.put("Green (Melon)","Medium Green");
		COLOR_MAP.put("Purple (Grape)","Medium Purple");
		COLOR_MAP.put("Red (Fruit Punch)","Medium Red");
		COLOR_MAP.put("Yellow (Lemonade)","Medium Yellow");
		COLOR_MAP.put("Dark Red (Strawberry)","Dark Red");
		COLOR_MAP.put("Orange (Creamsicle)","Medium Orange");
		COLOR_MAP.put("Light Blue (Mint)","Light Blue");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Kraft","Light Brown");
		COLOR_MAP.put("Holly","Medium Green");
	
		
		
		
	}
}
