package parser.cb;

import java.util.Map;
import java.util.TreeMap;

public class CBlookup {
	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);

	static{
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Translucent Black","Clear Black");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Translucent Pink","Clear Pink");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Teal","Clear Green");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Translucent Frost","Clear White");
		COLOR_MAP.put("Custom","Other");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Full Color","Multi Color");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Metallic Gold","Metallic Yellow");
		COLOR_MAP.put("Metallic Silver","Silver Metal");
		COLOR_MAP.put("Camouflage","Camouflage Green");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Rainbow","Multi Color");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Camel","Light Brown");
		COLOR_MAP.put("Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Sage","Light Green");
		COLOR_MAP.put("Tin","Medium Gray");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Translucent Black (Smoke)","Clear Black");
		COLOR_MAP.put("Clear (Frost)","Clear");
		COLOR_MAP.put("Cream","Medium White");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("Royal Blue","Medium Blue");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Forest Green","Dark Green");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Glow in the Dark","Medium Green");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Golf","Medium Green");
		COLOR_MAP.put("Transparent Frost","Clear White");
		COLOR_MAP.put("Charcoal","Dark Gray");
		COLOR_MAP.put("Heather","Light Gray");
		COLOR_MAP.put("Cocoa Brown","Medium Brown");
		COLOR_MAP.put("Frost","Clear White");
		COLOR_MAP.put("Translucent Clear","Clear");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Metallic Clear","Clear");
		COLOR_MAP.put("Metallic Camouflage","Metallic Green");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Metallic Orange","Metallic Orange");
		COLOR_MAP.put("Metallic Pink","Metallic Pink");
		COLOR_MAP.put("Metallic Purple","Metallic Purple");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Metallic White","Metallic White");
		COLOR_MAP.put("Metallic Yellow","Metallic Yellow");
		COLOR_MAP.put("Frosted","Medium White");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Carolina Blue","Medium Blue");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Bright Carolina Blue","Bright Blue");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Tortoise Shell","Medium Brown");
		COLOR_MAP.put("Wood Grain","Medium Brown");
		COLOR_MAP.put("Green Camo","Camouflage Green");
		COLOR_MAP.put("Translucent Glow in the Dark","Clear Green");
		COLOR_MAP.put("Translucent Maroon","Clear Red");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Translucent White","Clear White");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Magenta","Dark Pink");
		COLOR_MAP.put("Neon Blue","Bright Blue");
		COLOR_MAP.put("Turquoise","Bright Blue");
		COLOR_MAP.put("Cool Gray","Medium Gray");
		COLOR_MAP.put("Mixed Camo","Camouflage Green");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Pure White","Medium White");
		COLOR_MAP.put("Soft Yellow","Light Yellow");
		COLOR_MAP.put("Soft Pink","Light Pink");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Fuchsia","Bright Pink");
		COLOR_MAP.put("Translucent","Clear");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Berry","Dark Pink");
		COLOR_MAP.put("Light Wood","Light Brown");
		COLOR_MAP.put("Medium Wood","Medium Brown");
		COLOR_MAP.put("Dark Wood","Dark Brown");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Wood Tone","Medium Brown");
		COLOR_MAP.put("Titanium","Titanium Metal");
		COLOR_MAP.put("Other","Multi Color");
		COLOR_MAP.put("Titanium Gray","Medium Gray");
		COLOR_MAP.put("Cocoa","Medium Brown");
		COLOR_MAP.put("Blue (Blueberry)","Medium Blue");
		COLOR_MAP.put("Pink (Bubblegum)","Medium Pink");
		COLOR_MAP.put("Green (Melon)","Medium Green");
		COLOR_MAP.put("Purple (Grape)","Medium Purple");
		COLOR_MAP.put("Red (Fruit Punch)","Medium Red");
		COLOR_MAP.put("Yellow (Lemonade)","Medium Yellow");
		COLOR_MAP.put("Dark Red (Strawberry)","Dark Red");
		COLOR_MAP.put("Orange (Creamsicle)","Medium Orange");
		COLOR_MAP.put("Light Blue (Mint)","Light Blue");
		COLOR_MAP.put("Gold","Dark Yellow");
		COLOR_MAP.put("Kraft","Light Brown");
		COLOR_MAP.put("Holly","Medium Green");
	
		
		
		
	}
}
