package parser.TeamworkAthletic;

import java.util.HashMap;
import java.util.Map;

public class TeamworkAthleticColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Royal","Medium Blue");
		COLOR_MAP.put("Scarlet Red","Medium Red");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Scarlet","Medium Red");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Royal-White","Multi Color");
		COLOR_MAP.put("Purple-White","Multi Color");
		COLOR_MAP.put("Dark Green-White","Multi Color");
		COLOR_MAP.put("Silver-White","Multi Color");
		COLOR_MAP.put("Columbia Blue-White","Multi Color");
		COLOR_MAP.put("Black-White","Multi Color");
		COLOR_MAP.put("White-Royal","Multi Color");
		COLOR_MAP.put("White-Scarlet Red","Multi Color");
		COLOR_MAP.put("White Blue","Multi Color");
		COLOR_MAP.put("White-Navy","Multi Color");
		COLOR_MAP.put("Gold-White","Multi Color");
		COLOR_MAP.put("Navy-White","Multi Color");
		COLOR_MAP.put("Orange-Yellow","Multi Color");
		COLOR_MAP.put("Maroon-White","Multi Color");
		COLOR_MAP.put("Fuschia-White","Medium Pink");
		COLOR_MAP.put("Royal-White-White","Multi Color");
		COLOR_MAP.put("Royal-Orange-White","Multi Color");
		COLOR_MAP.put("Purple-Gold-White","Multi Color");
		COLOR_MAP.put("Scarlet-Black-White","Multi Color");
		COLOR_MAP.put("Scarlet-White-White","Multi Color");
		COLOR_MAP.put("Dark Green-Gold-White","Multi Color");
		COLOR_MAP.put("Black-Scarlet-White","Multi Color");
		COLOR_MAP.put("Black-White-White","Multi Color");
		COLOR_MAP.put("Navy-White-White","Multi Color");
		COLOR_MAP.put("Navy-Vegas Gold-White","Multi Color");
		COLOR_MAP.put("Orange-Black-White","Multi Color");
		COLOR_MAP.put("Maroon-Gold-White","Multi Color");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("College Blue","Medium Blue");
		COLOR_MAP.put("White-Black","Multi Color");
		COLOR_MAP.put("Silver-Black","Multi Color");
		COLOR_MAP.put("Fuchsia","Bright Pink");
		COLOR_MAP.put("Columbia Blue","Medium Blue");
		COLOR_MAP.put("Vegas Gold","Gold Metal");
		COLOR_MAP.put("Cardinal","Medium Red");
		COLOR_MAP.put("Texas Orange","Medium Orange");
		COLOR_MAP.put("Fluorescent Green","Bright Green");
		COLOR_MAP.put("Gold-Black-White","Multi Color");
		COLOR_MAP.put("Maroon-Black-White","Multi Color");
		COLOR_MAP.put("Purple-Black-White","Multi Color");
		COLOR_MAP.put("Dark Green-Black-White","Multi Color");
		COLOR_MAP.put("White-Black-Scarlet","Multi Color");
		COLOR_MAP.put("White-Black-Gold","Multi Color");
		COLOR_MAP.put("White-Black-Maroon","Multi Color");
		COLOR_MAP.put("White-Black-Purple","Multi Color");
		COLOR_MAP.put("White-Black-Dark Green","Multi Color");
		COLOR_MAP.put("Royal Blue-Black-White","Multi Color");
		COLOR_MAP.put("White-Black-Royal Blue","Multi Color");
		COLOR_MAP.put("Scarlet-Black","Multi Color");
		COLOR_MAP.put("Black-Scarlet","Multi Color");
		COLOR_MAP.put("Black-Gold","Multi Color");
		COLOR_MAP.put("Black-Orange","Multi Color");
		COLOR_MAP.put("Navy-Gold","Multi Color");
		COLOR_MAP.put("Orange-White","Multi Color");
		COLOR_MAP.put("Navy-Columbia Blue","Multi Color");
		COLOR_MAP.put("Scarlet-White","Multi Color");
		COLOR_MAP.put("Royal Blue-White","Multi Color");
		COLOR_MAP.put("Royal Blue-Gold","Multi Color");
		COLOR_MAP.put("Kelly Green-White","Multi Color");
		COLOR_MAP.put("Royal Blue-White-Royal Blue","Multi Color");
		COLOR_MAP.put("Scarlet-White-Scarlet","Multi Color");
		COLOR_MAP.put("Kelly Green-White-Kelly Green","Multi Color");
		COLOR_MAP.put("Black-White-Black","Multi Color");
		COLOR_MAP.put("Gold-White-Gold","Multi Color");
		COLOR_MAP.put("Navy-White-Navy","Multi Color");
		COLOR_MAP.put("Orange-White-Orange","Multi Color");
		COLOR_MAP.put("Maroon-White-Maroon","Multi Color");
		COLOR_MAP.put("Purple-White-Purple","Multi Color");
		COLOR_MAP.put("Scarlet-Black-Scarlet","Multi Color");
		COLOR_MAP.put("Dark Green-White-Dark Green","Multi Color");
		COLOR_MAP.put("Black-Scarlet-Black","Multi Color");
		COLOR_MAP.put("Columbia Blue-White-Columbia Blue","Multi Color");
		COLOR_MAP.put("Black-Gold-Black","Multi Color");
		COLOR_MAP.put("Black-Orange-Black","Multi Color");
		COLOR_MAP.put("Navy-Gold-Navy","Multi Color");
		COLOR_MAP.put("Navy-Columbia Blue-Navy","Multi Color");
		COLOR_MAP.put("White-White","Medium White");
		COLOR_MAP.put("Navy-Scarlet-White","Multi Color");
		COLOR_MAP.put("Fuchsia-Black-White","Multi Color");
		COLOR_MAP.put("Columbia Blue-Navy-White","Multi Color");
		COLOR_MAP.put("Royal Blue-White-White","Multi Color");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("White-Scarlet","Multi Color");
		COLOR_MAP.put("Gold-Black","Multi Color");
		COLOR_MAP.put("White-Royal Blue","Multi Color");
		COLOR_MAP.put("Scarlet-White-Black","Multi Color");
		COLOR_MAP.put("White-White-Black","Multi Color");
		COLOR_MAP.put("Gold-White-Black","Multi Color");
		COLOR_MAP.put("Navy-White-Black","Multi Color");
		COLOR_MAP.put("Orange-White-Black","Multi Color");
		COLOR_MAP.put("Maroon-White-Black","Multi Color");
		COLOR_MAP.put("Purple-White-Black","Multi Color");
		COLOR_MAP.put("Dark Green-White-Black","Multi Color");
		COLOR_MAP.put("Silver-White-Black","Multi Color");
		COLOR_MAP.put("Columbia Blue-White-Black","Multi Color");
		COLOR_MAP.put("Royal Blue-White-Black","Multi Color");
		COLOR_MAP.put("Kelly Green-White-Black","Multi Color");
		COLOR_MAP.put("Cardinal-White","Multi Color");
		COLOR_MAP.put("Texas Orange-White","Multi Color");
		COLOR_MAP.put("Cinder","Other");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Fluorescent Yellow","Medium Yellow");
		COLOR_MAP.put("Electric Blue","Medium Blue");
		COLOR_MAP.put("Teal-Orange-White","Multi Color");
		COLOR_MAP.put("Royal-Scarlet-White","Multi Color");
		COLOR_MAP.put("Scarlet-Gold-White","Multi Color");
		COLOR_MAP.put("Silver-Black-White","Multi Color");
		COLOR_MAP.put("Black-Silver-White","Multi Color");
		COLOR_MAP.put("Black-Gold-White","Multi Color");
		COLOR_MAP.put("Pink-Black-White","Multi Color");
		COLOR_MAP.put("Scarlet Red-White","Multi Color");
		COLOR_MAP.put("Scarlet-Ash Heather","Multi Color");
		COLOR_MAP.put("White-Purple","Multi Color");
		COLOR_MAP.put("White-Dark Green","Multi Color");
		COLOR_MAP.put("White-Orange","Multi Color");
		COLOR_MAP.put("Scarlet-White-Scarlet-Navy","Multi Color");
		COLOR_MAP.put("Black-White-Black-White","Multi Color");
		COLOR_MAP.put("Navy-White-Navy-Scarlet","Multi Color");
		COLOR_MAP.put("Cream-Black-Cream-Black","Multi Color");
		COLOR_MAP.put("Light Blue-Black-White-Light Blue","Multi Color");
		COLOR_MAP.put("College Blue-White-College Blue-Navy","Multi Color");
		COLOR_MAP.put("College Blue-Scarlet-White-Navy","Multi Color");
		COLOR_MAP.put("College Blue White-College Blue-Navy","Multi Color");
		COLOR_MAP.put("White-Royal Blue-Scarlet","Multi Color");
		COLOR_MAP.put("White-Royal Blue-Royal Blue","Multi Color");
		COLOR_MAP.put("White-Scarlet-Black","Multi Color");
		COLOR_MAP.put("White-Scarlet-Scarlet","Multi Color");
		COLOR_MAP.put("White-Navy-Scarlet","Multi Color");
		COLOR_MAP.put("White-Navy-Navy","Multi Color");
		COLOR_MAP.put("White-Navy-Gold","Multi Color");
		COLOR_MAP.put("White-Orange-Black","Multi Color");
		COLOR_MAP.put("White-Maroon-Gold","Multi Color");
		COLOR_MAP.put("White-Purple-Gold","Multi Color");
		COLOR_MAP.put("White-Dark Green-Gold","Multi Color");
		COLOR_MAP.put("White-Black-Metallic Silver","Multi Color");
		COLOR_MAP.put("White-Black-Metallic Gold","Multi Color");
		COLOR_MAP.put("White-Navy-Columbia Blue","Multi Color");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Silver-Scarlet","Multi Color");
		COLOR_MAP.put("Silver-Navy","Multi Color");
		COLOR_MAP.put("Silver-Royal Blue","Multi Color");
		COLOR_MAP.put("Navy-Gold-White","Multi Color");
		COLOR_MAP.put("Purple-Orange-White","Multi Color");
		COLOR_MAP.put("Dark Green-Vegas Gold-White","Multi Color");
		COLOR_MAP.put("Fuchsia-Purple-White","Multi Color");
		COLOR_MAP.put("Black-Fuchsia-White","Multi Color");
		COLOR_MAP.put("Maroon-Vegas Gold-White","Multi Color");
		COLOR_MAP.put("Columbia Blue-Fuchsia-White","Multi Color");
		COLOR_MAP.put("Apple Green-Black-White","Multi Color");
		COLOR_MAP.put("Royal Blue-Scarlet-White","Multi Color");
		COLOR_MAP.put("Cardinal Red","Medium Red");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Black-White-Scarlet","Multi Color");
		COLOR_MAP.put("Black-White-Gold","Multi Color");
		COLOR_MAP.put("Maroon-White-Gold","Multi Color");
		COLOR_MAP.put("Purple-White-Gold","Multi Color");
		COLOR_MAP.put("Navy-White-Gold","Multi Color");
		COLOR_MAP.put("Royal Blue-White-Gold","Multi Color");
		COLOR_MAP.put("Black-Orange-White","Multi Color");
		COLOR_MAP.put("Navy-Columbia Blue-White","Multi Color");
		COLOR_MAP.put("Cardinal-White-Cardinal","Multi Color");
		COLOR_MAP.put("Texas Orange-White-Texas Orange","Multi Color");
		COLOR_MAP.put("Royal Blue-Gold-Royal Blue","Multi Color");
		COLOR_MAP.put("Teal-White-Teal","Multi Color");
		COLOR_MAP.put("Gold-Black-Gold","Multi Color");
		COLOR_MAP.put("Orange-Black-Orange","Multi Color");
		COLOR_MAP.put("Silver-Maroon-Silver","Multi Color");
		COLOR_MAP.put("Columbia Blue-Black-Columbia Blue","Multi Color");
		COLOR_MAP.put("Kelly Green-Gold","Multi Color");
		COLOR_MAP.put("Navy-White-Scarlet","Multi Color");
		COLOR_MAP.put("Maroon-White-White","Multi Color");
		COLOR_MAP.put("Dark Green-White-White","Multi Color");
		COLOR_MAP.put("Black-White-Silver","Multi Color");
		COLOR_MAP.put("White-Dark Green-Dark Green","Multi Color");
		COLOR_MAP.put("White-Maroon-Maroon","Multi Color");
		COLOR_MAP.put("Texas-Orange-White","Multi Color");
		COLOR_MAP.put("Scarlet-Navy","Multi Color");
		COLOR_MAP.put("Dark Green-Gold","Multi Color");
		COLOR_MAP.put("Cardinal-Black-White","Multi Color");
		COLOR_MAP.put("White-Purple-Black","Multi Color");
		COLOR_MAP.put("White-Cardinal-Black","Multi Color");
		COLOR_MAP.put("White-Dark Green-Black","Multi Color");
		COLOR_MAP.put("Black-Black-White","Multi Color");
		COLOR_MAP.put("Purple-Fluorescent Green-White","Multi Color");
		COLOR_MAP.put("White-Gold","Multi Color");
		COLOR_MAP.put("White-Maroon","Multi Color");
		COLOR_MAP.put("White-Dark Geen","Multi Color");
		COLOR_MAP.put("White-Columbia Blue","Multi Color");
		COLOR_MAP.put("White-Kelly Green","Multi Color");
		COLOR_MAP.put("Columbia Blue-White-Purple","Multi Color");
		COLOR_MAP.put("Texas Orange-White-Black","Multi Color");
		COLOR_MAP.put("Black-White-Fluorescent Green","Multi Color");
		COLOR_MAP.put("Navy-White-Columbia Blue","Multi Color");
		COLOR_MAP.put("Fluorescent Blue","Bright Blue");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Apple Green","Medium Green");
		COLOR_MAP.put("Black-White-Orange","Multi Color");
		COLOR_MAP.put("Royal Blue-White-Scarlet","Multi Color");
		COLOR_MAP.put("Dark Green-White-Gold","Multi Color");
		COLOR_MAP.put("Silver-White-Navy","Multi Color");
		COLOR_MAP.put("Columbia Blue-White-Navy","Multi Color");
		COLOR_MAP.put("Black-White-Vegas Gold","Multi Color");
		COLOR_MAP.put("Maroon-White-Silver","Multi Color");
		COLOR_MAP.put("Scarlet-Scarlet-White","Multi Color");
		COLOR_MAP.put("Navy-Navy-White","Multi Color");
		COLOR_MAP.put("Black-Metallic Gold-White","Multi Color");
		COLOR_MAP.put("Royal Blue-Royal Blue-White","Multi Color");
		COLOR_MAP.put("Cardinal-White-Black","Multi Color");
		COLOR_MAP.put("Dark Green-White-Vegas Gold","Multi Color");
		COLOR_MAP.put("Fluorescent Green-White-Black","Multi Color");
		COLOR_MAP.put("Fuchsia-White-Black","Multi Color");
		COLOR_MAP.put("Ash","Light Green");
		COLOR_MAP.put("Fuschia","Dark Pink");
		COLOR_MAP.put("Navy-Scarlet","Multi Color");
		COLOR_MAP.put("Maroon-Gold","Multi Color");
		COLOR_MAP.put("Purple-Gold","Multi Color");
		COLOR_MAP.put("Royal Blue-Scarlet","Multi Color");
		COLOR_MAP.put("White-Scarlet-White","Multi Color");
		COLOR_MAP.put("White-Black-White","Multi Color");
		COLOR_MAP.put("White-Gold-White","Multi Color");
		COLOR_MAP.put("Scranton","Medium Red");
		COLOR_MAP.put("Metallic Silver","Medium Gray");
		COLOR_MAP.put("Metallic Gold","Dark Yellow");
		COLOR_MAP.put("Fluorescent Pink","Medium Pink");
		COLOR_MAP.put("Fluorescent Orange","Medium Orange");
		COLOR_MAP.put("Tennessee Orange","Medium Orange");
		COLOR_MAP.put("Royal Blue-Gold-White","Multi Color");
		COLOR_MAP.put("White-Teal","Multi Color");
		COLOR_MAP.put("White-Cardinal","Multi Color");
		COLOR_MAP.put("Black-Fluorescent Green","Multi Color");
		COLOR_MAP.put("Fluorescent Green-Black","Multi Color");
		COLOR_MAP.put("Navy-Orange-White","Multi Color");
		COLOR_MAP.put("Navy-Silver-White","Multi Color");
		COLOR_MAP.put("Dark Green-Black","Multi Color");
		COLOR_MAP.put("Orange-Black","Multi Color");
		COLOR_MAP.put("Maroon-Black","Multi Color");
		COLOR_MAP.put("Teal-Black","Multi Color");
		COLOR_MAP.put("Purple-Black","Medium Purple");
		COLOR_MAP.put("Columbia Blue-Black","Multi Color");
		COLOR_MAP.put("Vegas Gold-Black","Multi Color");
		COLOR_MAP.put("Cardinal-Black","Multi Color");
		COLOR_MAP.put("Texas Orange-Black-White","Multi Color");
		COLOR_MAP.put("Fuchsia-Black","Multi Color");
		COLOR_MAP.put("Royal Blue-Black","Multi Color");
		COLOR_MAP.put("Pink-White","Multi Color");
		COLOR_MAP.put("Pink-Black","Multi Color");
		COLOR_MAP.put("Fuchsia-Fluorescent Green-Black","Multi Color");
		COLOR_MAP.put("Columbia Blue-Black-White","Multi Color");
		COLOR_MAP.put("Purple-Pink-White","Multi Color");
		COLOR_MAP.put("White-Scarlet-White-Scarlet","Multi Color");
		COLOR_MAP.put("White-Black-White-Black","Multi Color");
		COLOR_MAP.put("White-Navy-White-Navy","Multi Color");
		COLOR_MAP.put("Silver-Scarlet-White-Scarlet","Multi Color");
		COLOR_MAP.put("Silver-Black-White-Black","Multi Color");
		COLOR_MAP.put("Silver-Navy-White-Navy","Multi Color");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Vegas Gold-White","Multi Color");
		COLOR_MAP.put("Kelly Green-Black","Multi Color");
		COLOR_MAP.put("Navy-Black-White","Multi Color");
		COLOR_MAP.put("Purple-Silver","Multi Color");
		COLOR_MAP.put("Columbia Blue-Navy","Multi Color");
		COLOR_MAP.put("Scarlet-Gold","Multi Color");
		COLOR_MAP.put("Black-Silver","Multi Color");
		COLOR_MAP.put("Black-Vegas Gold","Multi Color");
		COLOR_MAP.put("Navy-Silver","Multi Color");
		COLOR_MAP.put("Kelly-White","Multi Color");
		COLOR_MAP.put("Custom Colors","Assorted");
		COLOR_MAP.put("Ribbon Pink","Multi Color");
		COLOR_MAP.put("Zebra Multi-Color","Multi Color");
		COLOR_MAP.put("Tie Dye Multi-Color","Multi Color");
		COLOR_MAP.put("Zebra","Multi Color");
		COLOR_MAP.put("Camo Pink","Multi Color");
		COLOR_MAP.put("Neon Peace Multi-Color","Multi Color");

	}
	public static String getColorGroup(String colorName){
		String colorGroup = COLOR_MAP.get(colorName);
		return colorGroup == null?"Other":colorGroup;
	}
}
