package com.a4tech.util;

import java.util.HashMap;
import java.util.Map;

public class ApplicationConstants {
   
	
	public static final String PRICE_SPLITTER_BASE_PRICEGRID              	= "___";
	public static final int CONST_INT_VALUE_ONE                     	    =  1;
	public static final String CONST_STRING_VALUE_ONE                     	= "1";
	public static final String CONST_STRING_CAPITAL_Y                     	= "Y";
	public final static String CONST_STRING_EMPTY  							= "";
	public static final String CONST_STRING_COMMA_SEP 						= ",";
    public static final String  CONST_PRICE_TYPE_CODE_LIST    				= "L";
    public static final String  CONST_PRICE_TYPE_CODE_NET 					= "N";
    public static final String  CONST_CHAR_N 								= "N";
    public static final String  CONST_CHAR_Y 								= "Y";
    public static final boolean  CONST_BOOLEAN_TRUE 						= true;
    public static final boolean  CONST_BOOLEAN_FALSE 						= false;
    public static final String 	CONST_STRING_EQUAL 							= "=";
    public static final String  CONST_VALUE_TYPE_CODE_LIST 					= "LIST";
    public static final String  CONST_VALUE_TYPE_CODE_NET 					= "NET";
    public static final String  CONST_DELIMITER_COLON 						= ":";
    public static final String  CONST_STRING_COMBO 							= "Combo";
    public static final String  CONST_DELIMITER_SEMICOLON 					= ";";
    public static final String  CONST_VALUE_TYPE_DIMENSION 					= "Dimension";
    public static final String  CONST_VALUE_TYPE_CAPACITY 					= "Capacity";
    public static final String  CONST_VALUE_TYPE_VOLUME 					= "Volume";
    public static final String  CONST_VALUE_TYPE_APPAREL 					= "Apparel";
    public static final String  CONST_VALUE_TYPE_OTHER 						= "Other";
    public static final String  CONST_VALUE_TYPE_SPACE 						= " ";
    public static final String 	DATE_FORMAT 								= "yyyy-MM-dd'T'HH:mm:ss.SZ";
    public static final String  CONST_STRING_UNIMPRINTED					= "UNIMPRINTED";
    public static final String  CONST_STRING_HOT_STAMPED					= "Hot Stamped";
    public static final String  CONST_STRING_HOT_FOIL_STAMPED			    = "Hot/foil stamped";
    public static final String  CONST_STRING_TRUE							= "True";
    public static final String  CONST_STRING_COUNTRY_CODE_CH                = "CH";
    public static final String  CONST_STRING_COUNTRY_CODE_US                = "US";
    public static final String  CONST_STRING_COUNTRY_NAME_USA			    = "U.S.A.";
    public static final String  CONST_STRING_COUNTRY_NAME_CHINA			    = "CHINA";
    public static final String  CONST_STRING_ZERO                           = "0";
    public static final String  CONST_STRING_INCHES							= "in";
    public static final String  CONST_STRING_SHIPPING_WEIGHT                = "lbs";
    public static final String	CONST_STRING_SHIPPING_NUMBER_UNIT_CARTON    = "per Carton";
    public static final String	CONST_STRING_DOWNLOAD_FILE_PATH 			= "D:\\A4 ESPUpdate\\ErrorFiles\\";
    public static final String	CONST_STRING_SECONDARY 						= "Secondary";
    public static final String  CONST_STRING_PERSONALIZATION                = "PERSONALIZATION";
    public static final String  CONST_STRING_PRINTED                        =  "Printed";
    
    public final static String  COMBO_VALUES_SEPARATOR 					    = ":";
    public final static Integer COMBO_TEXT_VALUE_INDEX 					    = 1;
	public static final String  CONST_STRING_COMBO_TEXT 					= "Combo";
	public static final String  CONST_STRING_BLEND_TEXT 					= "Blend";
	public static final String  CONST_MEDIATYPE 							= "application/json";
	public static final String 	CONST_ASI_NUMBER 							= "Asi";
	public static final String 	CONST_USERNAME 								= "Username";
	public static final String 	CONST_PASSWORD 								= "Password";
	
	public static final String  CONST_DELIMITER_PIPE                 		= "|";
	public static final String  CONST_DELIMITER_SPLITTING_PIPE              = "\\|";
	public static final String  CONST_DELIMITER_AMPERSAND    				= "&"; 
	public static final String  CONST_DELIMITER_COMMA						= ",";
	public static final String  CONST_DELIMITER_FSLASH 					    = "/";
	//public static final String  CONST_DELIMITER_BSLASH 					    = "\\";
	public static final String  CONST_DELIMITER_HYPHEN 					    = "-";
	public static final String	CONST_DIMENSION_SPLITTER					= "@@";
	public static final String  CONST_DELIMITER_PERCENT_SIGN                = "%";
	
	public static final int     CONST_NUMBER_ZERO                           = 0;
	public static final int     CONST_NEGATIVE_NUMBER_ONE					= -1;
	
	public static final String  CONST_STRING_FALSE						= "False";
	public static final String  CONST_STRING_DISCOUNT_CODE_Z			= "Z";
	public static final String  CONST_STRING_SERVICECHARGE				= "Required";
	public static final String  CONST_STRING_YES						= "Yes";
	public static final String  CONST_STRING_CURRENCY_USD               ="USD";
	public static final String  CONST_STRING_IMMD_CHARGE			    = "Imprint Method Charge";
	public static final String	CONST_STRING_FULLCOLOR					="FULL COLOR";
	public static final String	CONST_STRING_DAYS					    ="days";
	public static final String	CONST_SHIPPING_UNIT_KG					="kg";
	public static final String	CONST_SHIPPING_UNIT_GRAMS				="grams";
	public static final String  CONST_STRING_IMPRINT_METHOD             = "Imprint Method";
	public static final String  CONST_STRING_WARRANTY_AVAILABLE         = "WARRANTY AVAILABLE";
	public static final String  CONST_STRING_WARRANTY_LENGTH			= "WARRANTY LENGTH";
	public static final String  CONST_STRING_LIFE_TIME                  = "Lifetime";
	public static final String  CONST_STRING_GRAPHIC					= "Graphic";
	public static final String  CONST_STRING_HARDWARE					= "Hardware";
	public static final String  CONST_STRING_WARRANTY_CHARGE_TYPE		= "Warranty Charge";
	public static final String  CONST_STRING_WARRANTY_INFORMATION 		= "Warranty Information";
	public static final String  CONST_REDIRECT_URL               		= "redirect:redirect.htm";
	public static final String  CONST_STRING_HOME						= "home";
	public static final String  CONST_STRING_SUCCESS					= "success";
	public static final String  CONST_STRING_FILE_NAME                  = "fileName";
	public static final String  SUCCESS_PRODUCTS_COUNT      			= "successProductsCount";
	public static final String  FAILURE_PRODUCTS_COUNT      			= "failureProductsCount";
	public static final String  CONST_STRING_SUCCESS_MSG			    = "successmsg";
	public static final String  CONST_STRING_UN_AUTHORIZED				= "unAuthorized";
	public static final String  CONST_STRING_ERROR_PAGE					= "errorPage";
	public static final String	CONST_STRING_XLS						= "xls";
	public static final String	CONST_STRING_XLSX						= "xlsx";
	public static final String	CONST_STRING_INVALID_UPLOAD_FILE		= "invalidUploadFile";
	public static final String	CONST_STRING_INVALID_DETAILS			= "invalidDetails";
	public static final String  MAIL_SEND_SUCCESS_MESSAGE				= "Email has been sent Successfully !!!";
	public static final String  CONST_STRING_CSV						= "csv";
	public static final String  CONST_STRING_DOT_TXT                    = ".txt";
	public static final int     CONST_INT_VALUE_TWO                     =  2;
	public static final int     CONST_INT_VALUE_THREE                   =  3;
	public static final String  CONST_STRING_OTHER_FABRIC				= "Other Fabric";
	public static final String  CONST_STRING_PRODUCT_COLOR              = "Product Color";
	public static final String  CONST_STRING_SIZE 		                = "Size";
	public static final String  CONST_STRING_TRIM                       = "trim";
	public static final String  SIZE_TYPE_STANDARD_AND_NUMBERED			= "Standard & Numbered";
	public static final String  TRADE_MARK_SYMBOL                       = "®";
	public static final String  SQUARE_SYMBOL							= "";
	public static final String  PARENTHESE_OPEN_SYMBOL                  = "(";  
	public static final String  PARENTHESE_CLOSE_SYMBOL                 = ")";
	public static final String  SQUARE_BRACKET_OPEN                     = "[";
	public static final String  SQUARE_BRACKET_CLOSE                    = "]";
	public static final String  COLOR_NAME_NAVY                         = "Navy";
	public static final String  COLOR_NAME_NAVY_BLUE                    = "Navy Blue";
	
	
	public static final String  CONST_STRING_COUNTRY_CODE_CN            = "CN";
	public static final String  CONST_STRING_AND					    = "and";
	public static final String  CONST_STRING_PLUS				        = "\\+";
	public static final String  CONST_STRING_RUN_CHARGE			    	= "Run Charge";
	public static final String  CONST_STRING_COPY_CHARGE			    ="Copy Changes Charge";
	public static final String  CONST_STRING_SETUP_CHARGE			    ="Set-up Charge";
	public static final String  CONST_STRING_ARTWK_CHARGE			    ="Artwork Charge";
	public static final String  CONST_DELIMITER_DOT						= ".";
	public static final String  CONST_STRING_IMPRNT_COLR				= "COLR";
	public static final String  CONST_STRING_IMPRINT_CODE             = "IMMD";
	public static final String  CONST_STRING_NEWLINECHARS             ="(\r\n|\n)";	
	public static final String  CONST_STRING_NEWLINE          		  ="\n";	
	
	public static final String	CONST_STRING_SHIPPING_NUMBER_UNIT_CASE   = "per Case";
	public static final String	CONST_STRING_BIG_SPACE   				= "   ";
	public static final String	CONST_STRING_UNCLASSIFIED_OTHER 		="UNCLASSIFIED/OTHER";
	 public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	 
	
	  public static Map<String, String> SUPPLIER_EMAIL_ID_MAP =new HashMap<String, String>();
	  public static Map<String, String> SUPPORT_EMAIL_ID_MAP =new HashMap<String, String>();
	    static {
	       
	    	SUPPLIER_EMAIL_ID_MAP.put("55201", "venkateswarlu.nidamanuri@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("55202", "azam.rizvi@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("55203", "sharvari.patil@a4technology.com");
	    	//SUPPLIER_EMAIL_ID_MAP.put("55204", "sharvari.patil@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("55204", "azam.rizvi@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("55205", "venkateswarlu.nidamanuri@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("65851", "amey.more@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("91561", "sharvari.patil@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("40445", "amey.more@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("82283", "sharvari.patil@a4technology.com");
	    	SUPPLIER_EMAIL_ID_MAP.put("91284", "amey.more@a4technology.com");
	    	
	    	SUPPORT_EMAIL_ID_MAP.put("dev_1", "amey.more@a4technology.com");
	    	SUPPORT_EMAIL_ID_MAP.put("dev_2", "venkateswarlu.nidamanuri@a4technology.com");
	    	SUPPORT_EMAIL_ID_MAP.put("dev_3", "sharvari.patil@a4technology.com");
	    	SUPPORT_EMAIL_ID_MAP.put("sysadmin_1", "salman@a4technology.com");
	    	SUPPORT_EMAIL_ID_MAP.put("sysadmin_2", "soheb.khan@a4technology.com");
	    	

	    	COLOR_MAP.put("001-Black","Medium Black");
	    	COLOR_MAP.put("011-Black","Medium Black");
	    	COLOR_MAP.put("011-Coal","Medium Black");
	    	COLOR_MAP.put("013-Black Heather","Medium Black");
	    	COLOR_MAP.put("01-Black","Medium Black");
	    	COLOR_MAP.put("021-Charcoal Heather","Medium Gray");
	    	COLOR_MAP.put("022-Charcoal","Medium Gray");
	    	COLOR_MAP.put("026-Carbon Heather","Dark Gray");
	    	COLOR_MAP.put("029-Shadow","Medium Gray");
	    	COLOR_MAP.put("02-Carhartt Brown","Medium Brown");
	    	COLOR_MAP.put("032-Taupe Gray","Medium Gray");
	    	COLOR_MAP.put("033-Gray","Medium Gray");
	    	COLOR_MAP.put("034-Heather Gray","Medium Gray");
	    	COLOR_MAP.put("039-Gravel","Medium Gray");
	    	COLOR_MAP.put("050-Camo Gray","Medium Gray");
	    	COLOR_MAP.put("051- Light Gray","Light Gray");
	    	COLOR_MAP.put("051-Light Gray","Light Gray");
	    	COLOR_MAP.put("053-Minimal Gray","Medium Gray");
	    	COLOR_MAP.put("054-Minimal Gray Heather","Medium Gray");
	    	COLOR_MAP.put("056-Vapor Gray","Medium Gray");
	    	COLOR_MAP.put("058-Asphalt Heather","Dark Gray");
	    	COLOR_MAP.put("058-Asphalt Heather/Navy Stripe","Medium Gray");
	    	COLOR_MAP.put("063-Dark Gray Heather Multi","Medium Gray");
	    	COLOR_MAP.put("063-Dark Heather Gray Multi","Medium Gray");
	    	COLOR_MAP.put("065-Dark Shale Heather","Medium Gray");
	    	COLOR_MAP.put("066-Asphalt","Medium Black");
	    	COLOR_MAP.put("06-Realtree Xtra","Camouflage Green");
	    	COLOR_MAP.put("070-Slate Heather","Other");
	    	COLOR_MAP.put("071-Rugged Gray Camo","Camouflage Gray");
	    	COLOR_MAP.put("074-Coal Heather","Medium Gray");
	    	COLOR_MAP.put("075-Steel","Medium Gray");
	    	COLOR_MAP.put("078- Dark Gray Heather","Clear Gray");
	    	COLOR_MAP.put("079-Dark Shale","Dark Gray");
	    	COLOR_MAP.put("100-White","Medium White");
	    	COLOR_MAP.put("103-Natural","DARK WHITE");
	    	COLOR_MAP.put("108-Birch","Light Brown");
	    	COLOR_MAP.put("111-Winter White","Medium White");
	    	COLOR_MAP.put("119-Marshmallow","Medium White");
	    	COLOR_MAP.put("201- Dark Brown","Dark Brown");
	    	COLOR_MAP.put("205-Coffee","Medium Brown");
	    	COLOR_MAP.put("209-Dark Canyon Brown","Dark Brown");
	    	COLOR_MAP.put("211-Brown","Medium Brown");
	    	COLOR_MAP.put("211-Carhartt Brown","Dark Brown");
	    	COLOR_MAP.put("223-Rust","Medium Brown");
	    	COLOR_MAP.put("232-Tan","Light Brown");
	    	COLOR_MAP.put("235- Light Brown","Light Brown");
	    	COLOR_MAP.put("235-Light Brown","Light Brown");
	    	COLOR_MAP.put("237-Dark Tan","Light Brown");
	    	COLOR_MAP.put("246-Mid Brown","Medium Brown");
	    	COLOR_MAP.put("250-Khaki","Medium Brown");
	    	COLOR_MAP.put("251-Desert","Light Brown");
	    	COLOR_MAP.put("253-Dark Khaki","Medium Brown");
	    	COLOR_MAP.put("256-Dark Tan Chambray","Light Brown");
	    	COLOR_MAP.put("257-Yukon","Medium Brown");
	    	COLOR_MAP.put("261-Sand","Light Brown");
	    	COLOR_MAP.put("264-Golden Khaki","Medium Yellow");
	    	COLOR_MAP.put("266-Cottonwood","Light Brown");
	    	COLOR_MAP.put("279-Warm Oatmeal Heather Multi","Light Brown");
	    	COLOR_MAP.put("285-Field Khaki","Light Brown");
	    	COLOR_MAP.put("294-Rugged Khaki Camo","Camouflage Brown");
	    	COLOR_MAP.put("295-Warm Oatmeal Heather","Medium White");
	    	COLOR_MAP.put("295-Warm Oatmeal Heather/Purple Sage Stripe","Light Brown");
	    	COLOR_MAP.put("297-Spring Khaki","Light Brown");
	    	COLOR_MAP.put("300-Green","Medium Green");
	    	COLOR_MAP.put("301-Army Green","Dark Green");
	    	COLOR_MAP.put("307-Olive","Medium Green");
	    	COLOR_MAP.put("308-Breen","Medium Green");
	    	COLOR_MAP.put("309- Duffel Bag Green","Medium Green");
	    	COLOR_MAP.put("309-Duffel Bag Green","Medium Green");
	    	COLOR_MAP.put("310-Bronze Green","Medium Green");
	    	COLOR_MAP.put("312-Distressed Army Green","Medium Green");
	    	COLOR_MAP.put("314-Mossy Oak (R) Break-Up Infinity (R)","Multi Color");
	    	COLOR_MAP.put("314-Mossy Oak Break Up Infinity","Multi Color");
	    	COLOR_MAP.put("314-Mossy Oak Break-up Infinity","Camouflage Green");
	    	COLOR_MAP.put("314-Mossy Oak(R) Break-up Infinity","Multi Color");
	    	COLOR_MAP.put("316-Moss","Dark Green");
	    	COLOR_MAP.put("323-Brite Lime","Bright Green");
	    	COLOR_MAP.put("327-Sour Apple","Medium Green");
	    	COLOR_MAP.put("333-Herb","Medium Green");
	    	COLOR_MAP.put("336-Watermint Heather","Light Green");
	    	COLOR_MAP.put("337-Spearmint Heather","Medium Green");
	    	COLOR_MAP.put("338-Spearmint","Medium Green");
	    	COLOR_MAP.put("351-Foliage","Medium Green");
	    	COLOR_MAP.put("358-Dark Green","Dark Green");
	    	COLOR_MAP.put("363-Emerald","Medium Green");
	    	COLOR_MAP.put("367-Citron Heather","Medium Yellow");
	    	COLOR_MAP.put("368-Emerald Heather","Medium Green");
	    	COLOR_MAP.put("387-Moss Green","Medium Green");
	    	COLOR_MAP.put("387-Moss Heather","Medium Green");
	    	COLOR_MAP.put("391-Burnt Olive","Medium Green");
	    	COLOR_MAP.put("3-Color Desert","Camouflage Brown");
	    	COLOR_MAP.put("401-Classic Dark","Medium Blue");
	    	COLOR_MAP.put("402-Indigo","Medium Blue");
	    	COLOR_MAP.put("403-Midnight","Dark Blue");
	    	COLOR_MAP.put("404-Lapis Blue Heather","Medium Blue");
	    	COLOR_MAP.put("405-Soft Blue Heather","Medium Blue");
	    	COLOR_MAP.put("407-Denim","Dark Blue");
	    	COLOR_MAP.put("409-True Blue Indigo","Medium Blue");
	    	COLOR_MAP.put("410-Dark Navy","Dark Blue");
	    	COLOR_MAP.put("411-Indigo Heather","Bright Blue");
	    	COLOR_MAP.put("412-Navy","Dark Blue");
	    	COLOR_MAP.put("415-Dark Vintage Blue","Dark Blue");
	    	COLOR_MAP.put("418-Navy Heather","Dark Blue");
	    	COLOR_MAP.put("420-Trailblazer","Dark Blue");
	    	COLOR_MAP.put("422-Authentic Indigo","Medium Blue");
	    	COLOR_MAP.put("423-Rustic Worn","Medium Blue");
	    	COLOR_MAP.put("426-Hudson Blue","Medium Blue");
	    	COLOR_MAP.put("432-Cobalt Blue","Medium Blue");
	    	COLOR_MAP.put("434-Royal","Bright Blue");
	    	COLOR_MAP.put("435-Ink Blue","Medium Blue");
	    	COLOR_MAP.put("437-Steel Blue","Light Blue");
	    	COLOR_MAP.put("438-Cool Blue","Bright Blue");
	    	COLOR_MAP.put("440-Camo Deep Blue","Medium Blue");
	    	COLOR_MAP.put("443-Dark Teal","Medium Green");
	    	COLOR_MAP.put("444-Vivid Blue","Medium Blue");
	    	COLOR_MAP.put("450-Pearl Blue","Medium Blue");
	    	COLOR_MAP.put("451-Midstone","Medium Blue");
	    	COLOR_MAP.put("452-Camo Indigo","Medium Blue");
	    	COLOR_MAP.put("454-Coastline","Light Blue");
	    	COLOR_MAP.put("455-Aegean Blue Heather","Medium Blue");
	    	COLOR_MAP.put("456-Washed Indigo","Medium Blue");
	    	COLOR_MAP.put("460-Coast Blue Heather Multi","Bright Blue");
	    	COLOR_MAP.put("465-Medium Blue","Medium Blue");
	    	COLOR_MAP.put("467-Tidal Blue Heather","Medium Blue");
	    	COLOR_MAP.put("468-Classic Wash","Dark Blue");
	    	COLOR_MAP.put("470-Bluestone","Medium Blue");
	    	COLOR_MAP.put("472-Navy","Dark Blue");
	    	COLOR_MAP.put("472-New Navy","Dark Blue");
	    	COLOR_MAP.put("473-Coast Blue Heather","Bright Blue");
	    	COLOR_MAP.put("476-Dark Blue","Dark Blue");
	    	COLOR_MAP.put("477-Island Blue","Medium Blue");
	    	COLOR_MAP.put("482- Deep Blue","Dark Blue");
	    	COLOR_MAP.put("482-Deep Blue","Medium Blue");
	    	COLOR_MAP.put("485-Timeworn Indigo","Bright Blue");
	    	COLOR_MAP.put("487-Island Blue Heather","Medium Blue");
	    	COLOR_MAP.put("488-Patriot Blue","Medium Gray");
	    	COLOR_MAP.put("489-Nautical Blue","Medium Blue");
	    	COLOR_MAP.put("490-Classic Blue","Medium Blue");
	    	COLOR_MAP.put("491-Ultra Blue","Medium Blue");
	    	COLOR_MAP.put("493-Medium Blue Chambray","Medium Blue");
	    	COLOR_MAP.put("496-Seaport Blue","Medium Blue");
	    	COLOR_MAP.put("497-Tumbled Blue","Medium Blue");
	    	COLOR_MAP.put("499-Denim Blue Chambray","Light Blue");
	    	COLOR_MAP.put("501-Plum","Dark Purple");
	    	COLOR_MAP.put("502-Plum Heather","Dark Purple");
	    	COLOR_MAP.put("503-Distressed Plum","Medium Purple");
	    	COLOR_MAP.put("507-Plum Heather Multi","Dark Purple");
	    	COLOR_MAP.put("515-Dusty Plum","Medium Purple");
	    	COLOR_MAP.put("516-Magenta","Medium Green");
	    	COLOR_MAP.put("534-Lilas","Medium Purple");
	    	COLOR_MAP.put("537-Misty Lilac Heather","Medium Purple");
	    	COLOR_MAP.put("538-Lilas Heather","Medium Purple");
	    	COLOR_MAP.put("540-Wild Ginger","Dark Pink");
	    	COLOR_MAP.put("541-Wild Ginger Heather","Dark Pink");
	    	COLOR_MAP.put("551-Magenta Heather","Medium Purple");
	    	COLOR_MAP.put("551-Winter White Heather","Medium White");
	    	COLOR_MAP.put("555-Nightshade Heather","Dark Gray");
	    	COLOR_MAP.put("563-Purple Sage","Medium Purple");
	    	COLOR_MAP.put("564-Purple Sage Heather","Dark Purple");
	    	COLOR_MAP.put("566-Hybrid Camo Purple","Medium Purple");
	    	COLOR_MAP.put("600-Red","Medium Red");
	    	COLOR_MAP.put("601-Dark Red Heather","Dark Red");
	    	COLOR_MAP.put("603-Malbec","Dark Red");
	    	COLOR_MAP.put("606-Malbec Heather","Dark Red");
	    	COLOR_MAP.put("607-Crimson","Medium Red");
	    	COLOR_MAP.put("608-Dark Crimson","Dark Red");
	    	COLOR_MAP.put("609-Cinnamon Red","Dark Red");
	    	COLOR_MAP.put("611-Cinnamon Red Heather Multi","Medium Red");
	    	COLOR_MAP.put("614-Port","Dark Red");
	    	COLOR_MAP.put("624-Crab Apple","Medium Red");
	    	COLOR_MAP.put("625-Sangria","Dark Red");
	    	COLOR_MAP.put("629-H Red","Medium Red");
	    	COLOR_MAP.put("640-Dark Red","Dark Red");
	    	COLOR_MAP.put("641-Chili Heather","Medium Red");
	    	COLOR_MAP.put("643-Deep Wine","Dark Red");
	    	COLOR_MAP.put("647-Chili","Medium Red");
	    	COLOR_MAP.put("660-Wild Rose Heather","Dark Pink");
	    	COLOR_MAP.put("661-Wild Rose","Medium Pink");
	    	COLOR_MAP.put("689-Light Blossom Heather","Medium Pink");
	    	COLOR_MAP.put("698-Geranium Coral Heather","Medium Pink");
	    	COLOR_MAP.put("6-Color Desert","Camouflage Brown");
	    	COLOR_MAP.put("701-Yellow","Medium Yellow");
	    	COLOR_MAP.put("716-Honey Ginger","Light Brown");
	    	COLOR_MAP.put("723-Mustard Yellow","Medium Yellow");
	    	COLOR_MAP.put("732-Spectra Yellow","Medium Yellow");
	    	COLOR_MAP.put("736-Vivid Orange","Medium Orange");
	    	COLOR_MAP.put("738-Cyber Yellow","Medium Yellow");
	    	COLOR_MAP.put("740-Lemongrass","Medium Green");
	    	COLOR_MAP.put("741-Lemongrass Heather","Medium Green");
	    	COLOR_MAP.put("800-Orange","Medium Orange");
	    	COLOR_MAP.put("803-Spice","Medium Brown");
	    	COLOR_MAP.put("810-Spiced Coral","Medium Red");
	    	COLOR_MAP.put("820-Blaze Orange","Medium Orange");
	    	COLOR_MAP.put("824-Brite Orange","Bright Orange");
	    	COLOR_MAP.put("827-Bold Orange","Bright Orange");
	    	COLOR_MAP.put("833-Burnt Coral Heather","Medium Orange");
	    	COLOR_MAP.put("840-Peach Fuzz Heather","Medium Orange");
	    	COLOR_MAP.put("847-Burnt Coral","Medium Orange");
	    	COLOR_MAP.put("903-Frontier Brown","Medium Brown");
	    	COLOR_MAP.put("908-Canyon Brown","Medium Brown");
	    	COLOR_MAP.put("908-Dark Coffee","Dark Brown");
	    	COLOR_MAP.put("909-Dark Coffee","Dark Brown");
	    	COLOR_MAP.put("910-Dark Khaki Digi Camo","Camouflage Brown");
	    	COLOR_MAP.put("912-Light Shale Brown","Medium Brown");
	    	COLOR_MAP.put("913-Worn Brown","Light Brown");
	    	COLOR_MAP.put("965-Hickory Stripe","Multi Color");
	    	COLOR_MAP.put("967-Khaki Camo","Camouflage Brown");
	    	COLOR_MAP.put("968-Bedrock","Dark Blue");
	    	COLOR_MAP.put("969-Rinsed Light Blue","Medium Blue");
	    	COLOR_MAP.put("975-Assorted","Assorted");
	    	COLOR_MAP.put("977-Realtree Xtra","Camouflage Green");
	    	COLOR_MAP.put("977-Realtree Xtra (R)","Camouflage Green");
	    	COLOR_MAP.put("977-Realtree Xtra (TM)","Camouflage Green");
	    	COLOR_MAP.put("980-Frontier","Light Blue");
	    	COLOR_MAP.put("984-Stream Blue","Medium Blue");
	    	COLOR_MAP.put("988-Dark Cobalt Blue","Dark Blue");
	    	COLOR_MAP.put("990-Pioneer Blue","Medium Blue");
	    	COLOR_MAP.put("991-Flint Stone","Medium Gray");
	    	COLOR_MAP.put("993-Lapis Blue Heather","Dark Blue");
	    	COLOR_MAP.put("Abilene","Dark Blue");
	    	COLOR_MAP.put("ABL-Authentic Blue","Medium Blue");
	    	COLOR_MAP.put("AF Digital Tiger Stripe","Multi Color");
	    	COLOR_MAP.put("AF Tan","Light Brown");
	    	COLOR_MAP.put("Air Force Digital Tiger Stripe","Camouflage Blue ");
	    	COLOR_MAP.put("Amarillo","Medium Blue");
	    	COLOR_MAP.put("Antique","Light Blue");
	    	COLOR_MAP.put("Antique Blue","Light Blue");
	    	COLOR_MAP.put("Antique Indigo","Dark Blue");
	    	COLOR_MAP.put("Antique Navy","Dark Blue");
	    	COLOR_MAP.put("Antique Wash","Medium Blue");
	    	COLOR_MAP.put("APH-Asphalt","Medium Black");
	    	COLOR_MAP.put("ARG-Army Green","Medium Green");
	    	COLOR_MAP.put("Army","Medium Green");
	    	COLOR_MAP.put("Army Green","Medium Green");
	    	COLOR_MAP.put("Army Universal","Camouflage Green");
	    	COLOR_MAP.put("Army Universal/Sand","Other");
	    	COLOR_MAP.put("Ash Heather","Light Gray");
	    	COLOR_MAP.put("ASH-Ash","Medium Gray");
	    	COLOR_MAP.put("Asian Tiger Stripe","Multi Color");
	    	COLOR_MAP.put("Asphalt","Medium Black");
	    	COLOR_MAP.put("Asphalt Heather","Dark Gray");
	    	COLOR_MAP.put("A-TACS AU (TM)/Tan499","Other");
	    	COLOR_MAP.put("A-TACS AU Camo (TM)","Multi Color");
	    	COLOR_MAP.put("A-Tacs Camo (R)","Multi Color");
	    	COLOR_MAP.put("A-TACS FG (TM)/Tan499","Other");
	    	COLOR_MAP.put("A-TACS FG Camo (TM)","Multi Color");
	    	COLOR_MAP.put("A-TACS LE Camo (TM)","Multi Color");
	    	COLOR_MAP.put("Authentic Blue","Medium Blue");
	    	COLOR_MAP.put("Authentic Indigo","Medium Blue");
	    	COLOR_MAP.put("Authentic Stone","Dark Blue");
	    	COLOR_MAP.put("Azalea (AZL)","Dark Pink");
	    	COLOR_MAP.put("Banjo Blue","Dark Blue");
	    	COLOR_MAP.put("Bark","Light Brown");
	    	COLOR_MAP.put("Barley-Black","Light Brown");
	    	COLOR_MAP.put("Barn Red Plaid","Other");
	    	COLOR_MAP.put("Barrel","Medium Blue");
	    	COLOR_MAP.put("Beige Heather","Multi Color");
	    	COLOR_MAP.put("Birch","Medium Brown");
	    	COLOR_MAP.put("Bison Brown","Medium Brown");
	    	COLOR_MAP.put("Bisque Heather","Medium Orange");
	    	COLOR_MAP.put("BKC-Black Chambray","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black (BLK)","Medium Black");
	    	COLOR_MAP.put("Black Chocolate","Dark Brown");
	    	COLOR_MAP.put("Black Forest Green","Dark Green");
	    	COLOR_MAP.put("Black Heather","Medium Black");
	    	COLOR_MAP.put("Black Mesquite","Dark Green");
	    	COLOR_MAP.put("BLACK-01","Medium Black");
	    	COLOR_MAP.put("Black-Barley","Medium Black");
	    	COLOR_MAP.put("Black-Camo","Camouflage Black");
	    	COLOR_MAP.put("Black-Gray","Pewter Metal");
	    	COLOR_MAP.put("Blacksmith","Medium Black");
	    	COLOR_MAP.put("Black-Yellow","Multi Color");
	    	COLOR_MAP.put("Bleach","Light Blue");
	    	COLOR_MAP.put("Bleach Wash","Light Blue");
	    	COLOR_MAP.put("Bleached Indigo","Light Blue");
	    	COLOR_MAP.put("BLK-Black","Medium Black");
	    	COLOR_MAP.put("BLM-Brite Lime","Bright Green");
	    	COLOR_MAP.put("BLS-Bluestone","Medium Blue");
	    	COLOR_MAP.put("Blue","Medium Blue");
	    	COLOR_MAP.put("Blue Chambray","Medium Blue");
	    	COLOR_MAP.put("Blue Frost","Light Blue");
	    	COLOR_MAP.put("Blue Granite","Medium Blue");
	    	COLOR_MAP.put("Blue Stone","Medium Blue");
	    	COLOR_MAP.put("Bluemarine","Light Blue");
	    	COLOR_MAP.put("Bluestone","Medium Blue");
	    	COLOR_MAP.put("BLZ-Blaze Orange","Medium Orange");
	    	COLOR_MAP.put("BOG-Brite Orange","Bright Orange");
	    	COLOR_MAP.put("Boulder","Medium Blue");
	    	COLOR_MAP.put("Bozeman","Dark Blue");
	    	COLOR_MAP.put("Breaking Barriers","Medium Blue");
	    	COLOR_MAP.put("Breen","Medium Green");
	    	COLOR_MAP.put("Brick","Other");
	    	COLOR_MAP.put("Brick Plaid","Other");
	    	COLOR_MAP.put("Brite Orange","Medium Orange");
	    	COLOR_MAP.put("BRN- Carhartt Brown","Medium Brown");
	    	COLOR_MAP.put("BRN-Carhartt Brown","Medium Brown");
	    	COLOR_MAP.put("Bronze Green","Multi Color");
	    	COLOR_MAP.put("Brown","Medium Brown");
	    	COLOR_MAP.put("Brown Boot","Medium Brown");
	    	COLOR_MAP.put("Brown Heather","Medium Brown");
	    	COLOR_MAP.put("Brown-Barley","Light Brown");
	    	COLOR_MAP.put("Brown-Black","Multi Color");
	    	COLOR_MAP.put("BRS-Brass","Brass Metal");
	    	COLOR_MAP.put("Burgundy","Dark Red");
	    	COLOR_MAP.put("Burnt Coral","Medium Pink");
	    	COLOR_MAP.put("Burnt Coral Heather","Medium Orange");
	    	COLOR_MAP.put("Burnt Olive","Medium Green");
	    	COLOR_MAP.put("Camel Brown","Medium Brown");
	    	COLOR_MAP.put("Camo Gray","Multi Color");
	    	COLOR_MAP.put("Camo Green","Multi Color");
	    	COLOR_MAP.put("Camouflage","Other");
	    	COLOR_MAP.put("Canyon Brown","Medium Brown");
	    	COLOR_MAP.put("Canyon Heather","Other");
	    	COLOR_MAP.put("Carbon Black","Medium Black");
	    	COLOR_MAP.put("Cardinal (CDN)","Medium Red");
	    	COLOR_MAP.put("CARHARTT BROWN-02","Medium Brown");
	    	COLOR_MAP.put("Caribbean Blue","Medium Green");
	    	COLOR_MAP.put("CBL-Blue Chambray","Medium Blue");
	    	COLOR_MAP.put("CBR-Canyon Brown","Medium Brown");
	    	COLOR_MAP.put("Cedar Green","Dark Green");
	    	COLOR_MAP.put("Cement","Medium Gray");
	    	COLOR_MAP.put("Chambray","Medium Blue");
	    	COLOR_MAP.put("Chambray Blue","Medium Blue");
	    	COLOR_MAP.put("Champagne Beige","Multi Color");
	    	COLOR_MAP.put("Charcoal","Medium Gray");
	    	COLOR_MAP.put("Charcoal Gray","Medium Gray");
	    	COLOR_MAP.put("Charcoal Heather","Medium Gray");
	    	COLOR_MAP.put("CHH-Charcoal Gray","Medium Gray");
	    	COLOR_MAP.put("CHH-Charcoal Heather","Medium Gray");
	    	COLOR_MAP.put("Chocolate","Medium Brown");
	    	COLOR_MAP.put("Chocolate (CHC)","Dark Brown");
	    	COLOR_MAP.put("Chocolate Brown","Medium Brown");
	    	COLOR_MAP.put("CHR-Charcoal","Medium Gray");
	    	COLOR_MAP.put("Cinnamon Red","Dark Red");
	    	COLOR_MAP.put("Clear","Clear");
	    	COLOR_MAP.put("CLH-Coal Heather","Medium Black");
	    	COLOR_MAP.put("COA-Coal","Medium Black");
	    	COLOR_MAP.put("Coal","Dark Gray");
	    	COLOR_MAP.put("Coal-Multi","Multi Color");
	    	COLOR_MAP.put("Coast Blue Heather","Dark Blue");
	    	COLOR_MAP.put("Coastline","Light Blue");
	    	COLOR_MAP.put("Cobalt Blue","Other");
	    	COLOR_MAP.put("Coral (CRL)","Medium Orange");
	    	COLOR_MAP.put("Cottonwood","Light Brown");
	    	COLOR_MAP.put("Coyote","Medium Brown");
	    	COLOR_MAP.put("Crab Apple","Medium Red");
	    	COLOR_MAP.put("Crazy Horse Brown","Medium Brown");
	    	COLOR_MAP.put("Creek Wash","Medium Blue");
	    	COLOR_MAP.put("Crest","Light Blue");
	    	COLOR_MAP.put("Crimson","Medium Red");
	    	COLOR_MAP.put("Cyan","Medium Blue");
	    	COLOR_MAP.put("Cyan (CYN)","Bright Blue");
	    	COLOR_MAP.put("Dark Bison Brown","Dark Brown");
	    	COLOR_MAP.put("Dark Blue","Dark Blue");
	    	COLOR_MAP.put("Dark Brown","Dark Brown");
	    	COLOR_MAP.put("Dark Brown Bison","Dark Brown");
	    	COLOR_MAP.put("Dark Brown Heather","Dark Brown");
	    	COLOR_MAP.put("Dark Classic Wash","Dark Blue");
	    	COLOR_MAP.put("Dark Cobalt","Dark Blue");
	    	COLOR_MAP.put("Dark Cobalt Blue","Dark Blue");
	    	COLOR_MAP.put("Dark Crimson","Dark Red");
	    	COLOR_MAP.put("Dark Denim","Dark Blue");
	    	COLOR_MAP.put("Dark Gray","Dark Gray");
	    	COLOR_MAP.put("Dark Green","Dark Green");
	    	COLOR_MAP.put("Dark Indigo","Dark Blue");
	    	COLOR_MAP.put("Dark Khaki","Medium Brown");
	    	COLOR_MAP.put("Dark Knight","Medium Blue");
	    	COLOR_MAP.put("Dark Moss","Medium Green");
	    	COLOR_MAP.put("Dark Navy","Dark Blue");
	    	COLOR_MAP.put("Dark Olive","Medium Green");
	    	COLOR_MAP.put("Dark Pewter (DKP)","Dark Gray");
	    	COLOR_MAP.put("Dark Red","Medium Red");
	    	COLOR_MAP.put("Dark Red Heather","Medium Red");
	    	COLOR_MAP.put("Dark Shadow","Medium Black");
	    	COLOR_MAP.put("Dark Shale","Medium Gray");
	    	COLOR_MAP.put("Dark Shale / Coastline","Medium Brown");
	    	COLOR_MAP.put("Dark Shale Heather","Medium Brown");
	    	COLOR_MAP.put("Dark Stone","Dark Blue");
	    	COLOR_MAP.put("Dark Tan","Light Brown");
	    	COLOR_MAP.put("Dark Teal","Dark Green");
	    	COLOR_MAP.put("Dark Tint","Dark Blue");
	    	COLOR_MAP.put("Dark Worn In Blue","Dark Blue");
	    	COLOR_MAP.put("Darkest Denim","Dark Blue");
	    	COLOR_MAP.put("Darkstone","Dark Blue");
	    	COLOR_MAP.put("Deep Blue","Dark Blue");
	    	COLOR_MAP.put("Deep Indigo","Dark Blue");
	    	COLOR_MAP.put("Deep Indigo Wash","Dark Blue");
	    	COLOR_MAP.put("Deep Sea Coral","Medium Blue");
	    	COLOR_MAP.put("Deep Wine","Dark Red");
	    	COLOR_MAP.put("Deepstone","Medium Blue");
	    	COLOR_MAP.put("Denim","Dark Blue");
	    	COLOR_MAP.put("DES-Desert","Light Brown");
	    	COLOR_MAP.put("Desert","Light Brown");
	    	COLOR_MAP.put("Desert Digital","Camouflage Brown");
	    	COLOR_MAP.put("Desert Digital/Coyote","Other");
	    	COLOR_MAP.put("Desert Sand","Medium Brown");
	    	COLOR_MAP.put("DFE-Dark Coffee","Medium Brown");
	    	COLOR_MAP.put("DGR-Dark Green","Dark Green");
	    	COLOR_MAP.put("Digi Camo Khaki","Camouflage Brown");
	    	COLOR_MAP.put("Dillon","Medium Blue");
	    	COLOR_MAP.put("DKB- Dark Brown","Medium Brown");
	    	COLOR_MAP.put("DKB-Dark Brown","Dark Brown");
	    	COLOR_MAP.put("DKG-Dark Gray","Dark Gray");
	    	COLOR_MAP.put("DKH-Dark Khaki","Medium Brown");
	    	COLOR_MAP.put("DMS-Dark Moss","Medium Green");
	    	COLOR_MAP.put("DNM-Denim","Medium Blue");
	    	COLOR_MAP.put("DNY-Dark Navy","Dark Blue");
	    	COLOR_MAP.put("DPM-Dusty Plum","Medium Purple");
	    	COLOR_MAP.put("DPS-Deepstone","Medium Brown");
	    	COLOR_MAP.put("Dried Rose","Medium Red");
	    	COLOR_MAP.put("DST-Darkstone","Medium Blue");
	    	COLOR_MAP.put("Duffel Bag Green","Medium Green");
	    	COLOR_MAP.put("Dusk Gray","Other");
	    	COLOR_MAP.put("Dusty","Medium Blue");
	    	COLOR_MAP.put("Dusty Mulberry Heather","Medium Pink");
	    	COLOR_MAP.put("Dusty Plum","Medium Purple");
	    	COLOR_MAP.put("DVB-Dark Vintage Blue","Dark Blue");
	    	COLOR_MAP.put("DWN-Deep Wine","Medium Red");
	    	COLOR_MAP.put("Earth","Medium Brown");
	    	COLOR_MAP.put("Ecru","DARK WHITE");
	    	COLOR_MAP.put("Electric Violet (EVL)","Medium Purple");
	    	COLOR_MAP.put("ELM-Elm","Medium Green");
	    	COLOR_MAP.put("Empire Blue","Medium Blue");
	    	COLOR_MAP.put("Empire Blue Heather","Medium Blue");
	    	COLOR_MAP.put("Empire Blue-Multi","Multi Color");
	    	COLOR_MAP.put("Enamel Blue Heather","Medium Blue");
	    	COLOR_MAP.put("Ether","Medium Blue");
	    	COLOR_MAP.put("Everyday Blue","Medium Blue");
	    	COLOR_MAP.put("Faded Black","Medium Black");
	    	COLOR_MAP.put("FAT-Fatigue","Other");
	    	COLOR_MAP.put("FBI-Faded Blue Indigo","Medium Blue");
	    	COLOR_MAP.put("FDK-Field Khaki","Light Brown");
	    	COLOR_MAP.put("Field Khaki","Light Brown");
	    	COLOR_MAP.put("Fir Green","Medium Green");
	    	COLOR_MAP.put("Flag","Other");
	    	COLOR_MAP.put("Flint Stone","Medium Blue");
	    	COLOR_MAP.put("Foliage Green","Medium Green");
	    	COLOR_MAP.put("Forest Green","Dark Green");
	    	COLOR_MAP.put("Forest Night","Dark Green");
	    	COLOR_MAP.put("FRB-Frontier Brown","Medium Brown");
	    	COLOR_MAP.put("Freedom Green","Medium Green");
	    	COLOR_MAP.put("Frontier Brown","Medium Brown");
	    	COLOR_MAP.put("Fudge Brown","Medium Brown");
	    	COLOR_MAP.put("Galaxy Blue","Medium Blue");
	    	COLOR_MAP.put("Galaxy Blue (GBL)","Medium Blue");
	    	COLOR_MAP.put("Geranium Coral","Medium Pink");
	    	COLOR_MAP.put("Geranium Coral Heather","Medium Pink");
	    	COLOR_MAP.put("GKH-Golden Khaki","Light Yellow");
	    	COLOR_MAP.put("Golden Khaki","Light Yellow");
	    	COLOR_MAP.put("Goldenrod","Dark Yellow");
	    	COLOR_MAP.put("Granite","Medium Blue");
	    	COLOR_MAP.put("Grape (GRP)","Medium Purple");
	    	COLOR_MAP.put("Grass Green","Light Green");
	    	COLOR_MAP.put("Grass Green (GGN)","Medium Green");
	    	COLOR_MAP.put("Gravel","Medium Gray");
	    	COLOR_MAP.put("GRAVEL - 04","Medium Gray");
	    	COLOR_MAP.put("GRAVEL-04","Medium Gray");
	    	COLOR_MAP.put("Gray","Medium Gray");
	    	COLOR_MAP.put("Gray Heather (GRH)","Medium Gray");
	    	COLOR_MAP.put("Green","Dark Green");
	    	COLOR_MAP.put("Green Heather","Multi Color");
	    	COLOR_MAP.put("Green Lily","Medium Green");
	    	COLOR_MAP.put("Green Sulphur","Medium Green");
	    	COLOR_MAP.put("GRY-Gray","Medium Gray");
	    	COLOR_MAP.put("GVL-Gravel","Medium Gray");
	    	COLOR_MAP.put("Harness Brown","Medium Brown");
	    	COLOR_MAP.put("Heather Black","Medium Black");
	    	COLOR_MAP.put("Heather Blue","Medium Blue");
	    	COLOR_MAP.put("Heather Dark Chocolate","Dark Brown");
	    	COLOR_MAP.put("Heather Gray","Light Gray");
	    	COLOR_MAP.put("Heather Tan","Light Brown");
	    	COLOR_MAP.put("Heavy Dark Stone","Dark Blue");
	    	COLOR_MAP.put("Heavy Denim Stone","Medium Blue");
	    	COLOR_MAP.put("Herb","Other");
	    	COLOR_MAP.put("HGY-Heather Gray","Light Gray");
	    	COLOR_MAP.put("Hibiscus (HBS)","Medium Orange");
	    	COLOR_MAP.put("High Visibility Lime","Bright Green");
	    	COLOR_MAP.put("High Visibility Yellow","Bright Yellow");
	    	COLOR_MAP.put("Hi-Vis","Other");
	    	COLOR_MAP.put("Hi-Viz Orange","Other");
	    	COLOR_MAP.put("HI-Viz Yellow","Other");
	    	COLOR_MAP.put("Honey Ginger","Light Brown");
	    	COLOR_MAP.put("HTG-Hunter Green","Medium Green");
	    	COLOR_MAP.put("Hunter Green","Dark Green");
	    	COLOR_MAP.put("Hunter Green (HNP)","Dark Green");
	    	COLOR_MAP.put("Hunter Pine (HNP)","Dark Green");
	    	COLOR_MAP.put("Hybrid Camo Purple","Medium Purple");
	    	COLOR_MAP.put("Independence Red","Medium Red");
	    	COLOR_MAP.put("Indigo","Dark Blue");
	    	COLOR_MAP.put("Indigo Denim","Dark Blue");
	    	COLOR_MAP.put("Indigo Heather","Dark Blue");
	    	COLOR_MAP.put("Industrial Brown","Light Brown");
	    	COLOR_MAP.put("Infantry Blue","Medium Blue");
	    	COLOR_MAP.put("Ink Blue","Medium Blue");
	    	COLOR_MAP.put("Island Blue","Medium Blue");
	    	COLOR_MAP.put("Java Brown","Dark Brown");
	    	COLOR_MAP.put("Java Brown Chambray","Dark Brown");
	    	COLOR_MAP.put("KBN-Khaki-Carhartt Brown","Multi Color");
	    	COLOR_MAP.put("Khaki","Light Brown");
	    	COLOR_MAP.put("Khaki (KHI)","Light Brown");
	    	COLOR_MAP.put("KHI-Khaki","Medium Brown");
	    	COLOR_MAP.put("KMS-Khaki-Moss","Multi Color");
	    	COLOR_MAP.put("LAPD Navy","Dark Blue");
	    	COLOR_MAP.put("Lapis Blue Heather","Light Blue");
	    	COLOR_MAP.put("Laser Blue","Light Blue");
	    	COLOR_MAP.put("Lavender Fog (LVF)","Light Purple");
	    	COLOR_MAP.put("LBR-Light Brown","Light Brown");
	    	COLOR_MAP.put("LGB-Light Worn-In Blue","Light Blue");
	    	COLOR_MAP.put("LGY-Light Gray","Light Gray");
	    	COLOR_MAP.put("Light Blossom Heather","Medium Pink");
	    	COLOR_MAP.put("Light Blue","Light Blue");
	    	COLOR_MAP.put("Light Blue Plaid","Light Blue");
	    	COLOR_MAP.put("Light Brown","Light Brown");
	    	COLOR_MAP.put("Light Chambray","Light Blue");
	    	COLOR_MAP.put("Light Classic Wash","Light Blue");
	    	COLOR_MAP.put("Light Denim","Light Blue");
	    	COLOR_MAP.put("Light Orchid-Multi","Multi Color");
	    	COLOR_MAP.put("Light Periwinkle","Light Purple");
	    	COLOR_MAP.put("Light Raisin","Light Purple");
	    	COLOR_MAP.put("Light Shale Brown Heather","Medium Brown");
	    	COLOR_MAP.put("Light Stone","Medium Blue");
	    	COLOR_MAP.put("Light Tan","Light Brown");
	    	COLOR_MAP.put("Loden","Dark Green");
	    	COLOR_MAP.put("Loden Green Plaid","Other");
	    	COLOR_MAP.put("LVB-Light Vintage Blue","Light Blue");
	    	COLOR_MAP.put("Macon","Medium Blue");
	    	COLOR_MAP.put("Magenta","Dark Pink");
	    	COLOR_MAP.put("Magenta Heather","Medium Pink");
	    	COLOR_MAP.put("Magenta Heather Stripe","Medium Purple");
	    	COLOR_MAP.put("Mahogany","Medium Brown");
	    	COLOR_MAP.put("Maize","Other");
	    	COLOR_MAP.put("Malbec Heather","Medium Purple");
	    	COLOR_MAP.put("Mallard","Other");
	    	COLOR_MAP.put("Mallard Plaid","Other");
	    	COLOR_MAP.put("Marina (MRN)","Medium Green");
	    	COLOR_MAP.put("Marshmallow","Medium White");
	    	COLOR_MAP.put("MBL-Medium Blue","Medium Blue");
	    	COLOR_MAP.put("MDS-Midstone","Medium Blue");
	    	COLOR_MAP.put("MDT-Midnight","Medium Black");
	    	COLOR_MAP.put("Mediterranean","Medium Blue");
	    	COLOR_MAP.put("Mediterranean Blue","Medium Blue");
	    	COLOR_MAP.put("Medium Denim","Medium Blue");
	    	COLOR_MAP.put("Medium Vintage","Medium White");
	    	COLOR_MAP.put("Merlot","Medium Purple");
	    	COLOR_MAP.put("Mid Stone","Dark Blue");
	    	COLOR_MAP.put("Mid Tint","Medium Blue");
	    	COLOR_MAP.put("Midland","Dark Blue");
	    	COLOR_MAP.put("Midnight","Dark Blue");
	    	COLOR_MAP.put("Minimal Gray","Medium Gray");
	    	COLOR_MAP.put("Mist Gray floral camo","Multi Color");
	    	COLOR_MAP.put("Misty Lilac","Medium Purple");
	    	COLOR_MAP.put("Misty Lilac Heather","Light Purple");
	    	COLOR_MAP.put("MOS-Moss","Medium Green");
	    	COLOR_MAP.put("Moss","Medium Green");
	    	COLOR_MAP.put("Moss Heather","Medium Green");
	    	COLOR_MAP.put("Mulberry Purple","Medium Purple");
	    	COLOR_MAP.put("Multi","Other");
	    	COLOR_MAP.put("Multi Color Plaid","Multi Color");
	    	COLOR_MAP.put("Multi Color Stripes","Multi Color");
	    	COLOR_MAP.put("MultiCam (R)","Multi Color");
	    	COLOR_MAP.put("Multistripe","Multi Color");
	    	COLOR_MAP.put("MUS-Mushroom","Medium Brown");
	    	COLOR_MAP.put("NAT-Natural","Medium White");
	    	COLOR_MAP.put("Natural","DARK WHITE");
	    	COLOR_MAP.put("Nautical Blue","Medium Blue");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Navy (NVY)","Dark Blue");
	    	COLOR_MAP.put("Navy Blue","Dark Blue");
	    	COLOR_MAP.put("Navy Heather","Multi Color");
	    	COLOR_MAP.put("Navy Indigo","Dark Blue");
	    	COLOR_MAP.put("New Navy","Dark Blue");
	    	COLOR_MAP.put("Night Sky","Dark Blue");
	    	COLOR_MAP.put("Nightfire","Dark Blue");
	    	COLOR_MAP.put("Nightshade","Medium Black");
	    	COLOR_MAP.put("Nightshade Heather","Other");
	    	COLOR_MAP.put("NVY-Navy","Dark Blue");
	    	COLOR_MAP.put("Oatmeal","Light Brown");
	    	COLOR_MAP.put("Oatmeal Heather (OAH)","Light Brown");
	    	COLOR_MAP.put("Ocean Blue","Light Blue");
	    	COLOR_MAP.put("Ocean Blue Plaid","Other");
	    	COLOR_MAP.put("Ocean Water","Light Blue");
	    	COLOR_MAP.put("Olive","Dark Green");
	    	COLOR_MAP.put("Olive (OLI)","Medium Green");
	    	COLOR_MAP.put("Olive Green","Dark Green");
	    	COLOR_MAP.put("Olive Taupe","Light Brown");
	    	COLOR_MAP.put("OLV-Olive","Medium Green");
	    	COLOR_MAP.put("Orange","Medium Orange");
	    	COLOR_MAP.put("ORG-Orange","Medium Orange");
	    	COLOR_MAP.put("Over-Dyed Black","Medium Black");
	    	COLOR_MAP.put("Patriot Blue","Medium Blue");
	    	COLOR_MAP.put("Patriot Blue Heather","Medium Blue");
	    	COLOR_MAP.put("Payson","Medium Blue");
	    	COLOR_MAP.put("Peach Beige","Medium Pink");
	    	COLOR_MAP.put("Pebbled Brown","Medium Brown");
	    	COLOR_MAP.put("Petal (PAL)","Medium Pink");
	    	COLOR_MAP.put("Petunia (PTN)","Dark Pink");
	    	COLOR_MAP.put("Pewter (PEW)","Medium Gray");
	    	COLOR_MAP.put("Pine","Dark Green");
	    	COLOR_MAP.put("Pink","Medium Pink");
	    	COLOR_MAP.put("Pink Rose (PKR)","Medium Pink");
	    	COLOR_MAP.put("Pinkcamo","Camouflage Pink");
	    	COLOR_MAP.put("Plaid Multi","Multi Color");
	    	COLOR_MAP.put("Plum","Medium Purple");
	    	COLOR_MAP.put("Port","Dark Red");
	    	COLOR_MAP.put("Port Heather","Multi Color");
	    	COLOR_MAP.put("Pre-Wash","Dark Blue");
	    	COLOR_MAP.put("Pre-Washed","Dark Blue");
	    	COLOR_MAP.put("Pre-Washed Charcoal Gray","Dark Gray");
	    	COLOR_MAP.put("Pre-Washed Indigo","Dark Blue");
	    	COLOR_MAP.put("Pre-Washed Tan","Light Brown");
	    	COLOR_MAP.put("Pre-Washed Wheat","Light Brown");
	    	COLOR_MAP.put("PRT-Port","Dark Red");
	    	COLOR_MAP.put("PTB-Petrol Blue","Medium Blue");
	    	COLOR_MAP.put("Purple","Medium Purple");
	    	COLOR_MAP.put("Purple Heather","Light Purple");
	    	COLOR_MAP.put("Purple Sage Heather","Medium Purple");
	    	COLOR_MAP.put("Putty","Light Brown");
	    	COLOR_MAP.put("Raisin Heather","Dark Purple");
	    	COLOR_MAP.put("Ranger Green","Medium Green");
	    	COLOR_MAP.put("Ravine","Dark Blue");
	    	COLOR_MAP.put("Rawhide","Medium Brown");
	    	COLOR_MAP.put("Realtree (R) Xtra","Multi Color");
	    	COLOR_MAP.put("Realtree Xtra","Camouflage Brown");
	    	COLOR_MAP.put("Realtree Xtra (R)","Camouflage Brown");
	    	COLOR_MAP.put("Realtree Xtra (R) - 06","Camouflage Brown");
	    	COLOR_MAP.put("REALTREE XTRA (R) -06","Camouflage Brown");
	    	COLOR_MAP.put("Realtree Xtra(R)","Other");
	    	COLOR_MAP.put("Red","Medium Red");
	    	COLOR_MAP.put("Red (RED)","Medium Red");
	    	COLOR_MAP.put("Red Orange","Multi Color");
	    	COLOR_MAP.put("Red Oxide","Dark Red");
	    	COLOR_MAP.put("RED-Red","Medium Red");
	    	COLOR_MAP.put("Redwood Brown","Medium Brown");
	    	COLOR_MAP.put("Rigid","Dark Blue");
	    	COLOR_MAP.put("Rigid Indigo","Dark Blue");
	    	COLOR_MAP.put("River Denim","Dark Blue");
	    	COLOR_MAP.put("River Wash","Medium Blue");
	    	COLOR_MAP.put("Rocky Top","Light Blue");
	    	COLOR_MAP.put("Rocky Trail","Medium Blue");
	    	COLOR_MAP.put("Rolling River","Dark Blue");
	    	COLOR_MAP.put("Root Beer","Dark Blue");
	    	COLOR_MAP.put("Rose","Medium Red");
	    	COLOR_MAP.put("Rosebud","Dark Pink");
	    	COLOR_MAP.put("Rough Stone","Dark Gray");
	    	COLOR_MAP.put("Rough Wash","Light Blue");
	    	COLOR_MAP.put("Royal","Bright Blue");
	    	COLOR_MAP.put("Royal (RYL)","Bright Blue");
	    	COLOR_MAP.put("Royal Blue","Bright Blue");
	    	COLOR_MAP.put("Royal Blue (RYL)","Bright Blue");
	    	COLOR_MAP.put("RUGGED CAMO - 15","Camouflage Green");
	    	COLOR_MAP.put("RUGGED CAMO-15","Camouflage Green");
	    	COLOR_MAP.put("Russet Brown","Medium Brown");
	    	COLOR_MAP.put("Rust Brown","Medium Brown");
	    	COLOR_MAP.put("RYL-Royal","Medium Blue");
	    	COLOR_MAP.put("Sable","Dark Brown");
	    	COLOR_MAP.put("Safety Green","Bright Green");
	    	COLOR_MAP.put("Safety Orange","Bright Orange");
	    	COLOR_MAP.put("Sage","Other");
	    	COLOR_MAP.put("Sage Green","Medium Green");
	    	COLOR_MAP.put("Sage Plaid","Other");
	    	COLOR_MAP.put("Sand","Light Brown");
	    	COLOR_MAP.put("Scottsdale","Medium Blue");
	    	COLOR_MAP.put("Shadow","Medium Gray");
	    	COLOR_MAP.put("Shadow Black","Medium Black");
	    	COLOR_MAP.put("Sheriff's Brown","Medium Brown");
	    	COLOR_MAP.put("Silver Gray (SVG)","Medium Gray");
	    	COLOR_MAP.put("Silver tan","Other");
	    	COLOR_MAP.put("Slate","Medium Gray");
	    	COLOR_MAP.put("Slate Blue","Medium Blue");
	    	COLOR_MAP.put("Slate Heather","Other");
	    	COLOR_MAP.put("Smokey Taupe","Medium Gray");
	    	COLOR_MAP.put("SND-Sand","Silver Metal");
	    	COLOR_MAP.put("Soft Blue Heather","Medium Blue");
	    	COLOR_MAP.put("Spice","Other");
	    	COLOR_MAP.put("Spruce Green","Medium Green");
	    	COLOR_MAP.put("Starlight Wash","Medium Blue");
	    	COLOR_MAP.put("Steel","Silver Metal");
	    	COLOR_MAP.put("Steel Blue","Dark Blue");
	    	COLOR_MAP.put("Steel Gray Plaid","Other");
	    	COLOR_MAP.put("STL-Steel","Silver Metal");
	    	COLOR_MAP.put("Stone","Light Brown");
	    	COLOR_MAP.put("Stone Bleach","Medium Blue");
	    	COLOR_MAP.put("Stone Dark Denim","Dark Blue");
	    	COLOR_MAP.put("Stone Wash","Medium Blue");
	    	COLOR_MAP.put("Stonebleach","Light Blue");
	    	COLOR_MAP.put("Stonewash","Light Blue");
	    	COLOR_MAP.put("Stonewashed","Medium Blue");
	    	COLOR_MAP.put("Stonewashed Indigo","Light Blue");
	    	COLOR_MAP.put("Storm Blue","Medium Blue");
	    	COLOR_MAP.put("Storm Heather","Other");
	    	COLOR_MAP.put("Stripe-Barley","Light Brown");
	    	COLOR_MAP.put("STW-Stonewash","Medium Blue");
	    	COLOR_MAP.put("Subdued Urban Digital","Camouflage Gray");
	    	COLOR_MAP.put("Subdued Urban Digital/Black","Other");
	    	COLOR_MAP.put("Subtle Worn","Medium Blue");
	    	COLOR_MAP.put("Sweet Plum (SWP)","Medium Purple");
	    	COLOR_MAP.put("Tan","Light Brown");
	    	COLOR_MAP.put("Tan Brown","Multi Color");
	    	COLOR_MAP.put("Tan499","Other");
	    	COLOR_MAP.put("TAN-Tan","Light Brown");
	    	COLOR_MAP.put("Teal Blue (TBL)","Medium Green");
	    	COLOR_MAP.put("Tiger Stripe","Multi Color");
	    	COLOR_MAP.put("Topiary Green","Medium Green");
	    	COLOR_MAP.put("Topiary Green Heather","Medium Green");
	    	COLOR_MAP.put("Traffic Blue","Other");
	    	COLOR_MAP.put("Traffic Yellow","Other");
	    	COLOR_MAP.put("True Blue","Medium Blue");
	    	COLOR_MAP.put("True Blue Indigo","Medium Blue");
	    	COLOR_MAP.put("Tulip Pink","Medium Pink");
	    	COLOR_MAP.put("Turquoise","Light Blue");
	    	COLOR_MAP.put("U.S. Coast Guard Blue","Medium Blue");
	    	COLOR_MAP.put("Union","Dark Blue");
	    	COLOR_MAP.put("Urban","Multi Color");
	    	COLOR_MAP.put("Vanilla Ice","Medium White");
	    	COLOR_MAP.put("Vintage","Medium Blue");
	    	COLOR_MAP.put("Vintage Blue","Medium Blue");
	    	COLOR_MAP.put("Vintage Dark","Medium Blue");
	    	COLOR_MAP.put("Vintage Denim","Medium Blue");
	    	COLOR_MAP.put("Vintage Indigo","Medium Blue");
	    	COLOR_MAP.put("Vintage Midnight","Medium Blue");
	    	COLOR_MAP.put("Vintage Saddle","Medium Brown");
	    	COLOR_MAP.put("Vintage Stone","Medium Blue");
	    	COLOR_MAP.put("Vivid Teal","Medium Blue");
	    	COLOR_MAP.put("Warm Oatmeal Heather","Light Brown");
	    	COLOR_MAP.put("Washed Indigo","Dark Blue");
	    	COLOR_MAP.put("Watermint","Multi Color");
	    	COLOR_MAP.put("Wheat","Light Brown");
	    	COLOR_MAP.put("White","Medium White");
	    	COLOR_MAP.put("White (WHT)","Medium White");
	    	COLOR_MAP.put("WHT-White","Medium White");
	    	COLOR_MAP.put("Wild Ginger","Medium Brown");
	    	COLOR_MAP.put("Wild Pink","Medium Pink");
	    	COLOR_MAP.put("Wild Rose","Medium Pink");
	    	COLOR_MAP.put("Wild Rose Heather","Medium Red");
	    	COLOR_MAP.put("Wine","Dark Red");
	    	COLOR_MAP.put("Wine (WIN)","Dark Red");
	    	COLOR_MAP.put("Winter White","Medium White");
	    	COLOR_MAP.put("Winter White Heather","Medium White");
	    	COLOR_MAP.put("Wistful Mauve","Medium Pink");
	    	COLOR_MAP.put("Woodbine Green Heather","Medium Green");
	    	COLOR_MAP.put("Woodland","Camouflage Green");
	    	COLOR_MAP.put("Woodland Digital","Camouflage Green");
	    	COLOR_MAP.put("Woodland Digital/Coyote","Other");
	    	COLOR_MAP.put("Woodland/3 Color Desert","Other");
	    	COLOR_MAP.put("Woodland/Olive","Other");
	    	COLOR_MAP.put("Worn Bark","Dark Blue");
	    	COLOR_MAP.put("Worn Black","Light Black");
	    	COLOR_MAP.put("Worn Brown","Light Brown");
	    	COLOR_MAP.put("Worn Dark","Dark Blue");
	    	COLOR_MAP.put("Worn In","Medium Blue");
	    	COLOR_MAP.put("Worn in Blue","Light Blue");
	    	COLOR_MAP.put("WRB-Worn in Blue","Light Blue");
	    	COLOR_MAP.put("WTB-Weathered Blue","Light Blue");
	    	COLOR_MAP.put("WWH-Winter White","Medium White");
	    	COLOR_MAP.put("Xtra","Camouflage Brown");
	    	COLOR_MAP.put("Yellow","Medium Yellow");
	    	COLOR_MAP.put("Royal","Bright Blue");
	    	COLOR_MAP.put("Bright Blue","Bright Blue");
	    	COLOR_MAP.put("Realtree Xtra ®","Camouflage Brown");
	    	COLOR_MAP.put("CAMO","Camouflage Brown");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Antique Navy","Dark Blue");
	    	COLOR_MAP.put("Blue Dusk","Dark Blue");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Olive","Dark Green");
	    	COLOR_MAP.put("Hunter Pine","Dark Green");
	    	COLOR_MAP.put("Wild Rose","Dark Pink");
	    	COLOR_MAP.put("Wine","Dark Red");
	    	COLOR_MAP.put("Deep Wine","Dark Red");
	    	COLOR_MAP.put("Deep Wine","Dark Red");
	    	COLOR_MAP.put("Dark Red","Dark Red");
	    	COLOR_MAP.put("994-Coastline","Light Blue");
	    	COLOR_MAP.put("239-Light Brown","Light Brown");
	    	COLOR_MAP.put("Khaki","Light Brown");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("BLACK","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("001-Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("012-Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Caribbean Blue","Medium Blue");
	    	COLOR_MAP.put("Ceil Blue","Medium Blue");
	    	COLOR_MAP.put("Blue Dusk","Medium Blue");
	    	COLOR_MAP.put("BlueDusk","Medium Blue");
	    	COLOR_MAP.put("245-Mid Brown","Medium Brown");
	    	COLOR_MAP.put("222-Carhartt Brown","Medium Brown");
	    	COLOR_MAP.put("Night Brown-Camel","Medium Brown");
	    	COLOR_MAP.put("Brown-Barley","Medium Brown");
	    	COLOR_MAP.put("Brown-Black","Medium Brown");
	    	COLOR_MAP.put("Brown-Camo","Medium Brown");
	    	COLOR_MAP.put("Pewter","Medium Gray");
	    	COLOR_MAP.put("010-Charcoal-Shadow","Medium Gray");
	    	COLOR_MAP.put("023-Charcoal","Medium Gray");
	    	COLOR_MAP.put("Gray-Black","Medium Gray");
	    	COLOR_MAP.put("Gray-Blue","Medium Gray");
	    	COLOR_MAP.put("Dark Shale-Dark Shale","Medium Gray");
	    	COLOR_MAP.put("Charcoal-Birch","Medium Gray");
	    	COLOR_MAP.put("355-Moss","Medium Green");
	    	COLOR_MAP.put("620-Crab Apple","Medium Green");
	    	COLOR_MAP.put("Olive","Medium Green");
	    	COLOR_MAP.put("348-Bronze Green-Olive","Medium Green");
	    	COLOR_MAP.put("371-Spearmint","Medium Green");
	    	COLOR_MAP.put("986-Realtree","Medium Green");
	    	COLOR_MAP.put("979-Realtree","Medium Green");
	    	COLOR_MAP.put("Rose-Black","Medium Pink");
	    	COLOR_MAP.put("849-Spiced Coral","Medium Pink");
	    	COLOR_MAP.put("Dusty Plum-Barley","Medium Purple");
	    	COLOR_MAP.put("505-Plum","Medium Purple");
	    	COLOR_MAP.put("Camo Purple- Camo Mesh","Medium Purple");
	    	COLOR_MAP.put("932-Dark Crimson","Medium Red");
	    	COLOR_MAP.put("Cinnamon Red-Dark Shale","Medium Red");
	    	COLOR_MAP.put("Magenta-Dark Shale","Medium Red");
	    	COLOR_MAP.put("Winter White Heather - Coast Blue Heather","Medium White");
	    	COLOR_MAP.put("Winter White Heather- Peach Fuzz Heather","Medium White");
	    	COLOR_MAP.put("Winter White Heather - Magenta Heather","Medium White");
	    	COLOR_MAP.put("Birch- Purple Sage","Medium White");
	    	COLOR_MAP.put("Birch- Spiced Coral","Medium White");
	    	COLOR_MAP.put("In The Mix Khaki","Multi Color");
	    	COLOR_MAP.put("In The Mix Black","Multi Color");
	    	COLOR_MAP.put("Painterly","Multi Color");
	    	COLOR_MAP.put("Realtree Xtra-Chocolate","Multi Color");
	    	COLOR_MAP.put("Nightfall Floret","Multi Color");
	    	COLOR_MAP.put("From Scratch","Multi Color");
	    	COLOR_MAP.put("Realtree Xtra-Pink Rose","Multi Color");
	    	COLOR_MAP.put("Stripe-Barley","Other");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Free Feather Galaxy","Medium Blue");
	    	COLOR_MAP.put("Dark Brown","Dark Brown");
	    	COLOR_MAP.put("BLACK-05","Medium Black");
	    	COLOR_MAP.put("Blaze Orange","Bright Orange");
	    	COLOR_MAP.put("Dark Brown","Dark Brown");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Pewter","Medium Gray");
	    	COLOR_MAP.put("Light Shale Brown","Medium Brown");
	    	COLOR_MAP.put("Pewter","Medium Gray");
	    	COLOR_MAP.put("Gray","Medium Gray");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Light Shale Brown","Medium Brown");
	    	COLOR_MAP.put("Dusty Plum","Medium Purple");
	    	COLOR_MAP.put("Birch","Medium White");
	    	COLOR_MAP.put("Coal","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Chocolate","Medium Brown");
	    	COLOR_MAP.put("Lime Punch","Bright Green");
	    	COLOR_MAP.put("Xtra","Camouflage Brown");
	    	COLOR_MAP.put("Dark Gray","Dark Gray");
	    	COLOR_MAP.put("Gold","Dark Yellow");
	    	COLOR_MAP.put("Barley","Light Brown");
	    	COLOR_MAP.put("Purple Sage","Light Purple");
	    	COLOR_MAP.put("Rose Stitching","Light Red");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("CARHARTT BROWN-04","Medium Brown");
	    	COLOR_MAP.put("Barley","Medium Brown");
	    	COLOR_MAP.put("Brown","Medium Brown");
	    	COLOR_MAP.put("Gray","Medium Gray");
	    	COLOR_MAP.put("Gray","Medium Gray");
	    	COLOR_MAP.put("Pewter","Medium Gray");
	    	COLOR_MAP.put("Dark Khaki Digi Camo","Medium Gray");
	    	COLOR_MAP.put("Dark Shale","Medium Gray");
	    	COLOR_MAP.put("Heather Gray","Medium Gray");
	    	COLOR_MAP.put("Blaze Orange","Medium Orange");
	    	COLOR_MAP.put("Rose Stitching","Medium Pink");
	    	COLOR_MAP.put("Dusty Plum","Medium Purple");
	    	COLOR_MAP.put("Rose Stitching","Medium Red");
	    	COLOR_MAP.put("Yellow","Medium Yellow");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Navy","Dark Blue");
	    	COLOR_MAP.put("Dark Crimson","Dark Red");
	    	COLOR_MAP.put("Wine","Dark Red");
	    	COLOR_MAP.put("Asphalt","Medium Black");
	    	COLOR_MAP.put("Black","Medium Black");
	    	COLOR_MAP.put("Realtree","Medium Brown");
	    	COLOR_MAP.put("Chocolate","Medium Brown");
	    	COLOR_MAP.put("Jade","Medium Green");
	    	COLOR_MAP.put("Brite Lime","Medium Green");
	    	COLOR_MAP.put("Blaze Orange","Medium Orange");
	    	COLOR_MAP.put("Burnt Coral","Medium Pink");
	    	COLOR_MAP.put("Purple Sage","Medium Purple");
	    	COLOR_MAP.put("Black","Medium Black");
	    	
	    	
	    }
    
}
