package parser.proGolf;

import java.util.HashMap;
import java.util.Map;

public class ProGolfColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("NAME","Color Group");
		COLOR_MAP.put("BLACK","Medium Black");
		COLOR_MAP.put("DARK BLACK","Dark Black");
		COLOR_MAP.put("NAVY","Dark Blue");
		COLOR_MAP.put("ROYAL","Medium Blue");
		COLOR_MAP.put("BLUE STEEL","Medium Blue");
		COLOR_MAP.put("GREEN","Medium Green");
		COLOR_MAP.put("MOSS","Medium Green");
		COLOR_MAP.put("KHAKI","Medium Brown");
		COLOR_MAP.put("CAMO","Camouflage Brown");
		COLOR_MAP.put("CLAY","Light Brown");
		COLOR_MAP.put("CHARCOAL","Medium Gray");
		COLOR_MAP.put("PINK CHAMPAGNE","Medium Pink");
		COLOR_MAP.put("BURGUNDY","Dark Red");
		COLOR_MAP.put("MOCHA","Medium Brown");
		COLOR_MAP.put("RED","Medium Red");
		COLOR_MAP.put("SUNGOLD","Medium Yellow");
		COLOR_MAP.put("COPPER","Copper Metal");
		COLOR_MAP.put("MATTE WHITE","Medium White");
		COLOR_MAP.put("MATTE BLUE","Medium Blue");
		COLOR_MAP.put("VISTA GRAY","Medium Gray");
		COLOR_MAP.put("STONE","Light Gray");
		COLOR_MAP.put("NOMAD RED","Medium Red");
		COLOR_MAP.put("WHITE","Medium White");
		COLOR_MAP.put("AERO BLUE","Medium Blue");
		COLOR_MAP.put("GYM BLUE","Medium Blue");
		COLOR_MAP.put("NICKEL","Nickel Metal");
		COLOR_MAP.put("PINK","Medium Pink");
		COLOR_MAP.put("BLUE","Medium Blue");
		COLOR_MAP.put("HI-VIS ORANGE","Bright Orange");
		COLOR_MAP.put("VOLT GREEN","Medium Green");
		COLOR_MAP.put("GRAY","Medium Gray");
		COLOR_MAP.put("MAGNETIC BLUE","Bright Blue");
		COLOR_MAP.put("QUIET SHADE","Medium Gray");
		COLOR_MAP.put("SAND","Light Brown");
		COLOR_MAP.put("LAVENDER","Medium Purple");
		COLOR_MAP.put("TRUE NAVY HEATHER","Dark Blue");
		COLOR_MAP.put("BLUE WAKE HEATHER","Bright Blue");
		COLOR_MAP.put("CARDINAL HEATHER","Medium Red");
		COLOR_MAP.put("COBALT HEATHER","Medium Blue");
		COLOR_MAP.put("DEEP ORANGE HEATHER","Dark Orange");
		COLOR_MAP.put("FOREST GREEN HEATHER","Dark Green");
		COLOR_MAP.put("GRAPHITE HEATHER","Medium Gray");
		COLOR_MAP.put("SCARLET HEATHER","Dark Red");
		COLOR_MAP.put("TURF GREEN HEATHER","Bright Green");
		COLOR_MAP.put("VARSITY PURPLE HEATHER","Medium Purple");
		COLOR_MAP.put("VINTAGE HEATHER","Medium Gray");
		COLOR_MAP.put("YELLOW","Medium Yellow");
		COLOR_MAP.put("ORANGE","Medium Orange");
		COLOR_MAP.put("HUNTER GREEN","Dark Green");
		COLOR_MAP.put("ROYAL BLUE","Dark Blue");
		COLOR_MAP.put("PURPLE","Medium Purple");
		COLOR_MAP.put("NATURAL TAN","Light Brown");
		COLOR_MAP.put("LIME","Light Green");
		COLOR_MAP.put("COASTAL BLUE","Medium Blue");
		COLOR_MAP.put("CHOCOLATE","Medium Brown");
		COLOR_MAP.put("GOLD","Gold Metal");
		COLOR_MAP.put("VEGAS GOLD","Dark Yellow");
		COLOR_MAP.put("TEXAS ORANGE","Medium Orange");
		COLOR_MAP.put("GRAY CONCRETE","Medium Gray");
		COLOR_MAP.put("MAROON","Dark Red");
		COLOR_MAP.put("BLUE LAKE","Medium Blue");
		COLOR_MAP.put("DEEP ORANGE","Dark Orange");
		COLOR_MAP.put("FOREST GREEN","Medium Green");
		COLOR_MAP.put("IRON GRAY","Dark Gray");
		COLOR_MAP.put("KELLY GREEN","Medium Green");
		COLOR_MAP.put("TROPIC BLUE","Medium Green");
		COLOR_MAP.put("TRUE RED","Medium Red");
		COLOR_MAP.put("TRUE ROYAL","Medium Blue");
		COLOR_MAP.put("TRUE NAVY","Dark Blue");
		COLOR_MAP.put("PINK RASPBERRY HEATHER","Dark Pink");
		COLOR_MAP.put("DIESEL GREY","Medium Gray");
		COLOR_MAP.put("TEAL SPARK","Light Blue");
		COLOR_MAP.put("PINK LUXE","Medium Pink");
		COLOR_MAP.put("PROVENCE BLUE","Light Blue");
		COLOR_MAP.put("SALSA RED","Medium Red");
		COLOR_MAP.put("SMOKED PEARL","Light Gray");
		COLOR_MAP.put("CLASSIC CHARCOAL","Medium Gray");
		COLOR_MAP.put("WATERMELON","Light Red");
		COLOR_MAP.put("PURPLE SLATE","Medium Purple");
		COLOR_MAP.put("RED VIOLET","Medium Red");
		COLOR_MAP.put("BASE GREY","Medium Gray");
		COLOR_MAP.put("CORAL","Medium Pink");
		COLOR_MAP.put("PLUM","Medium Purple");
		COLOR_MAP.put("GREY","Medium Gray");
		COLOR_MAP.put("MARINE","Light Blue");
		COLOR_MAP.put("BRITISH KHAKI","Light Brown");
		COLOR_MAP.put("STEEL BLUE","Bright Blue");
		COLOR_MAP.put("SANDSTONE","Medium Yellow");
		COLOR_MAP.put("STORM BLUE","Bright Blue");
		COLOR_MAP.put("DARK GRAY","Dark Gray");
		COLOR_MAP.put("TEAM RED","Medium Red");
		COLOR_MAP.put("MINT","Medium Green");
		COLOR_MAP.put("FROST BLUE","Light Blue");
		COLOR_MAP.put("FRUIT PUNCH","Medium Red");
		COLOR_MAP.put("SEASWELL","Medium Green");
		COLOR_MAP.put("SHOCK RED","Bright Red");
		COLOR_MAP.put("JACARANDA","Medium Purple");
		COLOR_MAP.put("SHOCK MINT","Medium Green");
		COLOR_MAP.put("FRENCH NAVY","Dark Blue");
		COLOR_MAP.put("EUCALYPTUS","Medium Green");
		COLOR_MAP.put("MIST","Light Blue");
		COLOR_MAP.put("CHEMICAL TURQUOISE","Medium Green");
		COLOR_MAP.put("BROWN","Medium Brown");
		COLOR_MAP.put("BAHIA BLUE","Bright Blue");
		COLOR_MAP.put("NYLON LIME","Bright Green");
		COLOR_MAP.put("NOMAD ORANGE","Medium Orange");
		COLOR_MAP.put("EQT BLUE","Medium Blue");
		COLOR_MAP.put("SHOCK BLUE","Bright Blue");
		COLOR_MAP.put("EQT PINK","Medium Pink");
		COLOR_MAP.put("SHARP LEMON","Medium Yellow");
		COLOR_MAP.put("GRASSHOPPER","Medium Green");
		COLOR_MAP.put("MINERAL BLUE","Medium Blue");
		COLOR_MAP.put("SEA LETTUCE","Medium Green");
		COLOR_MAP.put("FULL CUSTOM - BLACK","Medium Black");
		COLOR_MAP.put("FULL CUSTOM - WHITE","Medium White");
		COLOR_MAP.put("MATTE GRAY","Medium Gray");
		COLOR_MAP.put("CRIMSON","Dark Red");
		COLOR_MAP.put("WHITE (POLKA DOT)","Medium White");
		COLOR_MAP.put("RAINBOW","Multi Color");
		COLOR_MAP.put("COURT PURPLE","Medium Purple");
		COLOR_MAP.put("LUCKY GREEN","Medium Green");
		COLOR_MAP.put("BLUE SAPPHIRE","Medium Blue");
		COLOR_MAP.put("FLINT GRAY","Medium Gray");
		COLOR_MAP.put("MIDNIGHT NAVY","Dark Blue");
		COLOR_MAP.put("BROWN PLAID","Medium Brown");
		COLOR_MAP.put("VIVID GREEN","Medium Green");
		COLOR_MAP.put("OLIVE KHAKI","Dark Green");
		COLOR_MAP.put("ORANGE BLAZE","Medium Orange");
		COLOR_MAP.put("PRO RED","Medium Red");
		COLOR_MAP.put("UNIVERSITY BLUE","Light Blue");
		COLOR_MAP.put("VARSITY PURPLE","Medium Purple");
		COLOR_MAP.put("VARSITY ROYAL","Medium Blue");
		COLOR_MAP.put("CARBON","Medium Gray");
		COLOR_MAP.put("INSIGNIA BLUE","Medium Blue");
		COLOR_MAP.put("LIGHT BLUEBERRY","Light Blue");
		COLOR_MAP.put("CHLOROPHYLL","Medium Green");
		COLOR_MAP.put("PRO BLUE","Medium Blue");
		COLOR_MAP.put("VARSITY RED","Medium Red");
		COLOR_MAP.put("VIBRANT BLUE","Medium Blue");
		COLOR_MAP.put("LIGHT GAME ROYAL HEATHER","Medium Blue");
		COLOR_MAP.put("BLACK HEATHER","Medium Black");
		COLOR_MAP.put("CARBON HEATHER","Other");
		COLOR_MAP.put("MONSOON HEATHER","Medium Blue");
		COLOR_MAP.put("OATMEAL","Light Brown");
		COLOR_MAP.put("TORTOISE","Light Green");
		COLOR_MAP.put("SOLAR ORANGE","Medium Orange");
		COLOR_MAP.put("ANTHRACITE","Medium Gray");
		COLOR_MAP.put("PACIFIC BLUE","Medium Blue");
		COLOR_MAP.put("FRENCH BLUE","Medium Blue");
		COLOR_MAP.put("SKYLINE BLUE","Medium Blue");
		COLOR_MAP.put("SIGNAL BLUE","Medium Blue");
		COLOR_MAP.put("NEON GREEN","Bright Green");
		COLOR_MAP.put("SILVER","Silver Metal");
		COLOR_MAP.put("NEON PINK","Bright Pink");
		COLOR_MAP.put("PASTEL PINK","Medium Pink");
		COLOR_MAP.put("LIGHT BLUE","Light Blue");
		COLOR_MAP.put("PINE GREEN","Medium Green");
		COLOR_MAP.put("BRIGHT BLUE","Bright Blue");
		COLOR_MAP.put("OPTIC ORANGE","Medium Orange");
		COLOR_MAP.put("LIME GREEN","Light Green");
		COLOR_MAP.put("BRUSHED NICKEL","Nickel Metal");
		COLOR_MAP.put("PETROL","Other");
		COLOR_MAP.put("ACTION GREEN","Medium Green");
		COLOR_MAP.put("VOLT","Medium Green");
		COLOR_MAP.put("COOL GREY","Light Gray");
		COLOR_MAP.put("BLUSTERY","Medium Green");
		COLOR_MAP.put("OLD ROYAL","Dark Blue");
		COLOR_MAP.put("UNIVERSITY RED","Medium Red");
		COLOR_MAP.put("BRISK BLUE","Medium Blue");
		COLOR_MAP.put("PINK FIRE","Medium Pink");
		COLOR_MAP.put("CHARTREUSE","Medium Green");
		COLOR_MAP.put("DEEP ROYAL BLUE","Light Blue");
		COLOR_MAP.put("DARK GREY","Light Gray");
		COLOR_MAP.put("LIGHT PHOTO BLUE","Dark Blue");
		COLOR_MAP.put("GYM RED","Medium Red");
		COLOR_MAP.put("WASABE GREEN","Medium Green");
		COLOR_MAP.put("CHALLENGE RED","Medium Red");
		COLOR_MAP.put("COLLEGE NAVY","Dark Blue");
		COLOR_MAP.put("BRIGHT CRIMSON","Bright Red");
		COLOR_MAP.put("PINK POW","Medium Pink");
		COLOR_MAP.put("SHINY NICKEL","Nickel Metal");
		COLOR_MAP.put("ANTIQUE BRONZE","Bronze Metal");
		COLOR_MAP.put("NAVY BLUE","Dark Blue");
		COLOR_MAP.put("ANTIQUE NICKEL","Medium Gray");
		COLOR_MAP.put("BRONZE","Medium Brown");
		COLOR_MAP.put("DARK YELLOW","Dark Yellow");
		COLOR_MAP.put("MEDIUM BLUE","Medium Blue");
		COLOR_MAP.put("DARK BLUE","Dark Blue");
		COLOR_MAP.put("METALLIC YELLOW","Metallic Yellow");
		COLOR_MAP.put("NEON ORANGE","Bright Orange");
		COLOR_MAP.put("LIGHT GREEN","Light Green");
		COLOR_MAP.put("NATURAL","DARK WHITE");
		COLOR_MAP.put("TEAL","Medium Green");
		COLOR_MAP.put("PASSION FRUIT","Medium Pink");
		COLOR_MAP.put("LIGHT PURPLE","Medium Purple");
		COLOR_MAP.put("CRANBERRY","Medium Red");
		COLOR_MAP.put("DARK PURPLE","Medium Purple");
		COLOR_MAP.put("DARK GREEN","Dark Green");
		COLOR_MAP.put("CARNIVAL MIX","Multi Color");
		COLOR_MAP.put("DESIGNER MIX","Multi Color");
		COLOR_MAP.put("NEON MIX","Multi Color");
		COLOR_MAP.put("REGULAR MIX","Multi Color");
		COLOR_MAP.put("TROPICAL MIX","Multi Color");
		COLOR_MAP.put("ASSORTED","Assorted");
		COLOR_MAP.put("POWER RED","Medium Red");
		COLOR_MAP.put("EQUIPMENT BLUE","Medium Blue");
		COLOR_MAP.put("BRIGHT ROYAL","Bright Blue");
		COLOR_MAP.put("SESAME","Medium Yellow");
		COLOR_MAP.put("MID GRAY","Medium Gray");
		COLOR_MAP.put("AMAZON","Medium Green");
		COLOR_MAP.put("TAWNY PORT","Light Brown");
		COLOR_MAP.put("HEATHER GREY","Medium Gray");
		COLOR_MAP.put("CORNSILK","Medium Yellow");
		COLOR_MAP.put("TEAM ORANGE","Medium Orange");
		COLOR_MAP.put("FUSION PINK","Medium Pink");
		COLOR_MAP.put("NIGHT PURPLE","Medium Purple");
		COLOR_MAP.put("MEAN GREEN","Medium Green");
		COLOR_MAP.put("TIDAL BLUE","Light Blue");
		COLOR_MAP.put("ALUMINUM PINK","Medium Pink");
		COLOR_MAP.put("LAWN","Light Green");
		COLOR_MAP.put("VALOR BLUE","Light Blue");
		COLOR_MAP.put("TEAM GREEN","Medium Green");
		COLOR_MAP.put("TRAILS END BROWN","Medium Brown");
		COLOR_MAP.put("MIDNIGHT NAVY BLUE","Dark Blue");
		COLOR_MAP.put("PINENUT","Light Brown");
		COLOR_MAP.put("FLAMINGO","Bright Pink");
		COLOR_MAP.put("INDIGO","Medium Blue");
		COLOR_MAP.put("MAGENTA","Medium pink");
		COLOR_MAP.put("FIRE","Medium Red");
		COLOR_MAP.put("TRUE WHITE","Medium White");
		COLOR_MAP.put("DARK KHAKI","Medium Brown");
		COLOR_MAP.put("DEEP BLACK","Medium Black");
		COLOR_MAP.put("DEEP NAVY","Dark Blue");
		COLOR_MAP.put("GREY STRIPE","Medium Gray");
		COLOR_MAP.put("BRIGHT LIME","Bright Green");
		COLOR_MAP.put("RED-WHITE STRIPE","Medium Red");
		COLOR_MAP.put("WHITE STRIPE","Medium White");
		COLOR_MAP.put("BLACK STRIPE","Medium Black");
		COLOR_MAP.put("HIGHRISE","Medium Gray");
		COLOR_MAP.put("SILVER LINING","Silver Metal");
		COLOR_MAP.put("RIVIERA BLUE","Light Blue");
		COLOR_MAP.put("NEW BLUE","Medium Blue");
		COLOR_MAP.put("VARSITY ROYAL-WHITE","Medium Blue");
		COLOR_MAP.put("VARSITY RED-BLACK","Medium Red");
		COLOR_MAP.put("COBALT","Medium Blue");
		COLOR_MAP.put("FRACTURE","Dark Gray");
		COLOR_MAP.put("GRIDDLE","Medium Black");
		COLOR_MAP.put("METALLIC","Assorted");
		COLOR_MAP.put("SAGE","Medium Green");
		COLOR_MAP.put("SILVER-BLACK","Medium Gray");
		COLOR_MAP.put("NOBLE GREEN","Medium Green");
		COLOR_MAP.put("LAKE BLUE","Light Blue");
		COLOR_MAP.put("SPORT RED","Medium Red");
		COLOR_MAP.put("OLIVE","Medium Green");
		COLOR_MAP.put("HEATHER GRAY","Medium Gray");
		COLOR_MAP.put("STORM GRAY","Medium Gray");
		COLOR_MAP.put("SUNSET","Medium Purple");
		COLOR_MAP.put("TERRA","Other");
		COLOR_MAP.put("AQUA","Light Blue");
		COLOR_MAP.put("HOT PINK","Bright Pink");
		COLOR_MAP.put("GUN METAL","Medium Gray");
		COLOR_MAP.put("HEATHER CHARCOAL","Medium Gray");
		COLOR_MAP.put("BERRY","Medium Pink");
		COLOR_MAP.put("MID BLUE","Medium Blue");
		COLOR_MAP.put("JADE","Medium Green");
		COLOR_MAP.put("CREAM","Medium White");
		COLOR_MAP.put("FUSHIA","Medium Purple");
		COLOR_MAP.put("NEON GREEN(SOLID OR CLEAR)","Medium Green");
		COLOR_MAP.put("PEWTER","Medium Gray");
		COLOR_MAP.put("NEON PINK (SOLID OR CLEAR)","Medium Pink");
		COLOR_MAP.put("NEON ORANGE(SOLID OR CLEAR)","Medium Orange");
		COLOR_MAP.put("PINK RUSH","Medium Pink");
		COLOR_MAP.put("CITRON","Medium Yellow");
		COLOR_MAP.put("BLUE WAKE","Medium Green");
		COLOR_MAP.put("CAROLINA BLUE","Medium Blue");
		COLOR_MAP.put("NEON ORANGE (SOLID OR CLEAR)","Medium Orange");
		COLOR_MAP.put("CLEAR NEON YELLOW","Medium Yellow");
		COLOR_MAP.put("NEON GREEN (SOLID OR CLEAR)","Medium Green");
		COLOR_MAP.put("BRASS","Dark Yellow");
		COLOR_MAP.put("FUSCHIA","Medium Purple");
		COLOR_MAP.put("PEACH","Medium Orange");
		COLOR_MAP.put("LIGHT PINK","Light Pink");
		COLOR_MAP.put("PINK RASPBERRY","Dark Pink");
		COLOR_MAP.put("CARROT","Medium Orange");
		COLOR_MAP.put("VIBRANT GREEN","Medium Green");
		COLOR_MAP.put("PURPLE MAGIC","Medium Purple");
		COLOR_MAP.put("ZINFANDEL","Medium Purple");
		COLOR_MAP.put("BRIGHT WHITE","Bright White");
		COLOR_MAP.put("EQUIPMENT GREEN","Medium Green");
		COLOR_MAP.put("EQUIPMENT PINK","Medium Pink");
		COLOR_MAP.put("LIGHT YELLOW","Light Yellow");
		COLOR_MAP.put("CHILI PEPPER","Medium Red");
		COLOR_MAP.put("MANDARIN ORANGE","Medium Orange");
		COLOR_MAP.put("PAISLEY PURPLE","Medium Purple");
		COLOR_MAP.put("BLUE ATOLL","Bright Blue");
		COLOR_MAP.put("BIRD OF PARADISE","Multi Color");
		COLOR_MAP.put("PARADISE","Light Blue");
		COLOR_MAP.put("PARAKEET","Medium Green");
		COLOR_MAP.put("GRIFFIN GRAY","Medium Gray");
		COLOR_MAP.put("POOL BLUE","Medium Blue");
		COLOR_MAP.put("REBEL RED","Medium Red");
		COLOR_MAP.put("PURPLE LUXE","Medium Purple");
		COLOR_MAP.put("BLUE INDIGO","Medium Blue");
		COLOR_MAP.put("ROYAL ENAMEL","Bright Blue");
		COLOR_MAP.put("BLACKTOP","Medium Black");
		COLOR_MAP.put("HUNTER","Dark Green");
		COLOR_MAP.put("METALLIC SILVER","Silver Metal");
		COLOR_MAP.put("CAVIAR BLACK","Medium Black");
		COLOR_MAP.put("PALACE BLUE","Light Blue");
		COLOR_MAP.put("GRAY HEATHER","Medium Gray");
		COLOR_MAP.put("TAUPIA","Medium Brown");
		COLOR_MAP.put("CLEAR BLUE","Light Blue");
		COLOR_MAP.put("NAVY HEATHER","Dark Blue");
		COLOR_MAP.put("LUCKY BLUE","Medium Blue");
		COLOR_MAP.put("BRIGHT ORANGE","Bright Orange");
		COLOR_MAP.put("DARK SLATE","Dark Gray");
		COLOR_MAP.put("BLAST BLUE","Medium Blue");
		COLOR_MAP.put("CORE BLUE","Medium Blue");
		COLOR_MAP.put("LIGHT AQUA","Light Blue");
		COLOR_MAP.put("SCARLET","Medium Red");
		COLOR_MAP.put("ULTRA BEAUTY","Other");
		COLOR_MAP.put("SHOCK PINK","Medium Pink");
		COLOR_MAP.put("ENERGY","Other");
		COLOR_MAP.put("VIVID YELLOW","Bright Yellow");
		COLOR_MAP.put("SOLAR LIME","Bright Green");
		COLOR_MAP.put("WHITE PLAIN TOE","Medium White");
		COLOR_MAP.put("BLACK PLAIN TOE SADDLE","Medium Black");
		COLOR_MAP.put("BROWN PLAIN TOE SADDLE","Medium Brown");
		COLOR_MAP.put("TAN CVO PATTERN","Medium Brown");
		COLOR_MAP.put("DARK BLUE CVO PATTERN","Medium Blue");
		COLOR_MAP.put("CHARCOAL CVO PATTERN","Medium Gray");
		COLOR_MAP.put("DARK BROWN WALLABY","Medium Brown");
		COLOR_MAP.put("BLACK WALLABY","Medium Black");
		COLOR_MAP.put("OCEAN","Light Blue");
		COLOR_MAP.put("ESTATE BLUE","Medium Blue");
		COLOR_MAP.put("BATTLESHIP GRAY","Medium Gray");
		COLOR_MAP.put("GARNET","Other");
		COLOR_MAP.put("POSH PURPLE","Medium Purple");
		COLOR_MAP.put("TRUE ROYAL HEATHER","Bright Blue");
		COLOR_MAP.put("CHARGE GREEN","Medium Green");
		COLOR_MAP.put("CHARCOAL GRAY HEATHER","Medium Gray");
		COLOR_MAP.put("CHARCOAL GREY","Medium Gray");
		COLOR_MAP.put("MEDIUM GRAY HEATHER","Medium Gray");
		COLOR_MAP.put("RASPBERRY ROSE HEATHER","Medium Pink");
		COLOR_MAP.put("WILD ORCHID HEATHER","Medium Pink");
		COLOR_MAP.put("SUNSET CORAL HEATHER","Medium Orange");
		COLOR_MAP.put("DEEP BLUE HEATHER","Dark Blue");
		COLOR_MAP.put("BAJA BLUE HEATHER","Bright Blue");
		COLOR_MAP.put("GREEN GLEN","Medium Green");
		COLOR_MAP.put("VINE GREEN","Medium Green");
		COLOR_MAP.put("AUTUMN ORANGE","Medium Orange");
		COLOR_MAP.put("GRAY SMOKE","Medium Gray");
		COLOR_MAP.put("HYPER BLUE","Medium Blue");
		COLOR_MAP.put("OCEAN BLUE","Medium Blue");
		COLOR_MAP.put("RICH RED","Medium Red");
		COLOR_MAP.put("VIOLET PURPLE","Medium Purple");
		COLOR_MAP.put("WHITE TRADITIONAL SADDLE","Medium White");
		COLOR_MAP.put("TAN SUEDE","Medium Brown");
		COLOR_MAP.put("NAVY SUEDE","Dark Blue");
		COLOR_MAP.put("CHOCOLATE BROWN","Medium Brown");
		COLOR_MAP.put("ANTIQUE TAN DRIVING MOC","Medium Brown");
		COLOR_MAP.put("BLACK DRIVING MOC","Medium Black");
		COLOR_MAP.put("WHITE VELCRO ATHLETIC","Medium White");
		COLOR_MAP.put("WHITE ATHLETIC","Medium White");
		COLOR_MAP.put("FJ CASCADE BOOT","Other");
		COLOR_MAP.put("DARK TAUPE SANDAL","Medium Brown");
		COLOR_MAP.put("BLACK SLIDE","Medium Black");
		COLOR_MAP.put("ENGLISH TAN CAP TOE","Medium Brown");
		COLOR_MAP.put("BLACK CAP TOE","Medium Black");
		COLOR_MAP.put("BLACK MOC TOE","Medium Black");
		COLOR_MAP.put("COGNAC MOC TOE","Medium Brown");
		COLOR_MAP.put("GRAFFITI PRINT MOE TOE VELCRO","Medium Black");
		COLOR_MAP.put("ZEBRA/FUSCHIA U-THROAT","Medium Purple");
		COLOR_MAP.put("CHEETAH/DARK BROWN U-THROAT","Dark Brown");
		COLOR_MAP.put("WHITE SPORT CONTRAST STITCH","Medium White");
		COLOR_MAP.put("CHABLIS SPORT CONTRAST STITCH","Other");
		COLOR_MAP.put("DEEP BLUE SPORT CONTRAST STITCH","Medium Blue");
		COLOR_MAP.put("BLACK SPORT CONTRAST STITCH","Medium Black");
		COLOR_MAP.put("TAN SPORT CONTRAST STITCH","Medium Brown");
		COLOR_MAP.put("WHITE BICYCLE TOE","Medium White");
		COLOR_MAP.put("WHITE U-THROAT UMBRELLA","Medium White");
		COLOR_MAP.put("RED U-THROAT UMBRELLA","Medium Red");
		COLOR_MAP.put("NAVY U-THROAT UMBRELLA","Dark Blue");
		COLOR_MAP.put("RAINBOW SWEPT BACK SADDLE","Medium White");
		COLOR_MAP.put("PINK ROSE ENGINEERED MESH","Medium Pink");
		COLOR_MAP.put("SEA FOAM ENGINEERED MESH","Medium Green");
		COLOR_MAP.put("POOL BLUE ENGINEERED MESH","Medium Blue");
		COLOR_MAP.put("GREY MIST ENGINEERED MESH","Medium Gray");
		COLOR_MAP.put("BRILLIANT BLUE","Medium Blue");
		COLOR_MAP.put("BRIGHT PURPLE","Medium Purple");
		COLOR_MAP.put("NEON YELLOW","Medium Yellow");
		COLOR_MAP.put("STEEL GRAY","Medium Gray");
		COLOR_MAP.put("TEAL GREEN","Medium Green");
		COLOR_MAP.put("DRESS BLUE NAVY","Dark Blue");
		COLOR_MAP.put("RUNNING CORE CORE BLACK","Medium White");
		COLOR_MAP.put("CORE SILVER METALLIC","Silver Metal");
		COLOR_MAP.put("RUNNING WHITE","Medium White");
		COLOR_MAP.put("BIRCH","Light Gray");
		COLOR_MAP.put("ACID","Light Green");
		COLOR_MAP.put("DARK GRAY HEATHER","Medium Gray");
		COLOR_MAP.put("OBSIDIAN","Medium Blue");
		COLOR_MAP.put("GAME ROYAL","Medium Blue");
		COLOR_MAP.put("GRIDIRON GREEN","Medium Green");
		COLOR_MAP.put("SIGNAL RED","Medium Red");
		COLOR_MAP.put("ELECTRIC BLUE","Bright Blue");
		COLOR_MAP.put("YIELD YELLOW","Light Yellow");
		COLOR_MAP.put("BLUE SPARK","Medium Blue");
		COLOR_MAP.put("FAIR BLUE","Light Blue");
		COLOR_MAP.put("CLOROPHYLL","Medium Green");
		COLOR_MAP.put("URBAN HAZE","Light Green");
		COLOR_MAP.put("TOUR YELLOW","Medium Yellow");
		COLOR_MAP.put("PHOTO BLUE","Medium Blue");
		COLOR_MAP.put("BLUEPRINT","Medium Blue");
		COLOR_MAP.put("DIESEL GRAY","Medium Gray");
		COLOR_MAP.put("ACID GREEN","Medium Green");
		COLOR_MAP.put("SKY BLUE","Light Blue");
		COLOR_MAP.put("SLATE","Light Gray");
		COLOR_MAP.put("BRICK RED","Medium Red");
		COLOR_MAP.put("BURNT ORANGE","Medium Orange");
		COLOR_MAP.put("MUSTARD","Medium Yellow");
		COLOR_MAP.put("WASABE","Light Green");
		COLOR_MAP.put("CHALK BLUE","Medium Blue");
		COLOR_MAP.put("FERN GREEN","Medium Green");
		COLOR_MAP.put("NINE IRON","Medium Gray");
		COLOR_MAP.put("MARINE BLUE","Dark Blue");
		COLOR_MAP.put("LEGEND BLUE","Medium Blue");
		COLOR_MAP.put("CLAY GREEN","Medium Green");
		COLOR_MAP.put("NAVY/BLUE","Medium White");
		COLOR_MAP.put("BONE","Medium White");
		COLOR_MAP.put("DEEP ROYAL","Dark Blue");
		COLOR_MAP.put("CARDINAL","Medium Red");
		COLOR_MAP.put("GRAPHITE","Medium Gray");
		COLOR_MAP.put("STEEL","Medium Gray");
		COLOR_MAP.put("NAUTICAL BLUE","Medium Blue");
		COLOR_MAP.put("REEF BLUE","Bright Blue");
		COLOR_MAP.put("VIVID PINK","Medium Pink");
		COLOR_MAP.put("OLIVE CAMO","Medium Green");
		COLOR_MAP.put("MATTE SILVER","Silver Metal");
		COLOR_MAP.put("VIBRANT ORANGE","Medium Orange");
		COLOR_MAP.put("HIGH RISK RED","Medium Red");
		COLOR_MAP.put("ATOMIC BLUE","Medium Blue");
		COLOR_MAP.put("COLUMBIA","Medium Green");
		COLOR_MAP.put("QUARRY","Medium Gray");
		COLOR_MAP.put("PEACOAT HEATHER","Dark Blue");
		COLOR_MAP.put("LIGHT GREY HEATHER","Medium Gray");
		COLOR_MAP.put("BLUE HEAVEN","Medium Blue");
		COLOR_MAP.put("OMPHALODES","Light Blue");
		COLOR_MAP.put("GREEN GECKO","Medium Green");
		COLOR_MAP.put("ZINNIA","Medium Orange");
		COLOR_MAP.put("ORCHID BLOOM","Medium Purple");
		COLOR_MAP.put("ROSE RED","Medium Red");
		COLOR_MAP.put("BERING SEA","Dark Blue");
		COLOR_MAP.put("COOL BLUE","Light Blue");
		COLOR_MAP.put("MINT LEAF","Medium Green");
		COLOR_MAP.put("CHERRY TOMATO","Medium Red");
		COLOR_MAP.put("PURPLE CACTUS FLOWER","Medium Purple");
		COLOR_MAP.put("FLURO PEACH","Bright Orange");
		COLOR_MAP.put("DAZZLING BLUE","Bright Blue");
		COLOR_MAP.put("LIGHT GRAY HEATHER","Medium Gray");
		COLOR_MAP.put("PEACOAT","Dark Blue");
		COLOR_MAP.put("SURF THE WEB","Medium Blue");
		COLOR_MAP.put("SHOCK GREEN","Bright Green");
		COLOR_MAP.put("VOLTAGE BLUE","Medium Blue");
		COLOR_MAP.put("PINK CRUSH","Bright Pink");
		COLOR_MAP.put("ALLOY GREEN","Medium Green");
		COLOR_MAP.put("BLACK TOP","Medium Black");
		COLOR_MAP.put("BLUE RIBBON","Medium Blue");
		COLOR_MAP.put("PISTON PURPLE","Dark Purple");
		COLOR_MAP.put("BLUE PRINT","Medium Blue");
		COLOR_MAP.put("BERRY BURST","Medium Purple");
		COLOR_MAP.put("VIOLET","Medium Purple");
		COLOR_MAP.put("ASPHALT","Medium Black");
		COLOR_MAP.put("CORAL SUNSET","Medium Orange");
		COLOR_MAP.put("PETROL GRAY","Medium Gray");
		COLOR_MAP.put("CARGO BROWN","Medium Brown");
		COLOR_MAP.put("ASTRO GREEN","Medium Green");
		COLOR_MAP.put("PURPLE HAZE","Medium Purple");
		COLOR_MAP.put("PINK ROUGE","Bright Pink");
		COLOR_MAP.put("BLUE ENAMEL","Medium Blue");
		COLOR_MAP.put("FLARE ORANGE","Medium Orange");
		COLOR_MAP.put("MATTE BLACK","Medium Black");
		COLOR_MAP.put("MET SILVER","Medium Gray");
		COLOR_MAP.put("MARLIN","Light Blue");
		COLOR_MAP.put("SURF","Light Blue");
		COLOR_MAP.put("IVORY","Medium White");
		COLOR_MAP.put("MOCHA BLACK","Medium Black");
		COLOR_MAP.put("OAT","Light Brown");
		COLOR_MAP.put("BLACK W/ GRAY BORDER","Medium Black");
		COLOR_MAP.put("COOL GRAY","Medium Gray");
		COLOR_MAP.put("HEATHER LIGHT BLUE","Light Blue");
		COLOR_MAP.put("STONE BLUE","Medium Blue");
		COLOR_MAP.put("OLD MOSS HEATHER","Medium Brown");
		COLOR_MAP.put("STARLIGHT","Dark Blue");
		COLOR_MAP.put("CHARCOAL GRAY","Medium Gray");
		COLOR_MAP.put("DUSTY ROSE","Medium Pink");
		COLOR_MAP.put("IRIS PURPLE","Medium Purple");
		COLOR_MAP.put("HOT CORAL","Medium Pink");
		COLOR_MAP.put("PINK RUSH HEATHER","Medium Pink");
		COLOR_MAP.put("ORANGE ICE","Medium Orange");
		COLOR_MAP.put("ICE BLUE","Light Blue");
		COLOR_MAP.put("CLEAR","Clear");
		COLOR_MAP.put("SEAFOAM","Medium Green");
		COLOR_MAP.put("POPPY RED","Medium Red");
		COLOR_MAP.put("ORCHID","Medium Purple");
		COLOR_MAP.put("GLACIER GRAY","Medium Gray");
		COLOR_MAP.put("PINK DOGWOOD","Medium Pink");
		COLOR_MAP.put("PERISCOPE","Medium Gray");
		COLOR_MAP.put("VIRTUAL PINK","Medium Pink");
		COLOR_MAP.put("TRADEWINDS","Other");
		COLOR_MAP.put("RICH GREEN","Medium Green");
		COLOR_MAP.put("CLEAR GRAY","Clear Gray");
		COLOR_MAP.put("JOY BLUE","Medium Blue");
		COLOR_MAP.put("COLLEGIATE ROYAL","Medium Blue");
		COLOR_MAP.put("DARK NAVY","Dark Blue");
		COLOR_MAP.put("PEACOAT NAVY","Dark Blue");
		COLOR_MAP.put("TANGO RED","Medium Red");
		COLOR_MAP.put("LIMOGES","Multi Color");
		COLOR_MAP.put("MONUMENT","Multi Color");
		COLOR_MAP.put("CAVIAR HEATHER","Other");
		COLOR_MAP.put("DYNASTY GREEN HEATHER","Medium Green");
		COLOR_MAP.put("LIMOGES HEATHER","Other");
		COLOR_MAP.put("STRIPE","Medium Black");
		COLOR_MAP.put("BLUEPRINT HEATHER","Medium Blue");
		COLOR_MAP.put("HIGHRISE HEATHER","Medium Gray");
		COLOR_MAP.put("CASTLEROCK HEATHER","Medium Gray");
		COLOR_MAP.put("TAN","Medium Brown");
		COLOR_MAP.put("ALL OVER BLACK CAP TOE","Medium Black");
		COLOR_MAP.put("ALL OVER TAN CAP TOE","Medium Brown");
		COLOR_MAP.put("ALL OVER BROWN CAP TOE","Medium Brown");
		COLOR_MAP.put("WHITE SPORT SPEED SADDLE","Medium White");
		COLOR_MAP.put("BLACK SPORT SPEED SADDLE","Medium Black");
		COLOR_MAP.put("TMAG EQUIPMENT BLUE HEATHER","Medium Blue");
		COLOR_MAP.put("TMAG MINERAL BLUE HEATHER","Medium Green");
		COLOR_MAP.put("GRAPHITE GRAY","Medium Gray");
		COLOR_MAP.put("STADIUM GREEN","Medium Green");
		COLOR_MAP.put("GREY HEATHER","Medium Gray");
		COLOR_MAP.put("DARK SMOKE GRAY","Medium Gray");
		COLOR_MAP.put("WILD ORCHID","Medium Purple");
		COLOR_MAP.put("BLUSHING PINK","Medium Pink");
		COLOR_MAP.put("SUNNY LIME HEATHER","Medium Yellow");
		COLOR_MAP.put("SOFT BLUE","Light Blue");
		COLOR_MAP.put("MINT BURST HEATHER","Medium Green");
		COLOR_MAP.put("BLACK BICYCLE TOE SADDLE","Medium Black");
		COLOR_MAP.put("CLOUD SANDAL","Medium Gray");
		COLOR_MAP.put("BLUE SANDAL","Medium Blue");
		COLOR_MAP.put("GREY MIST ENJOY","Medium Gray");
		COLOR_MAP.put("LAVENDER ENJOY","Medium Purple");
		COLOR_MAP.put("NEUTRAL","Medium Brown");
		COLOR_MAP.put("ANTHRACITE/COOL GREY","Medium Black");
		COLOR_MAP.put("WOLF PURE PLATINUM/DARK ","Medium Gray");
		COLOR_MAP.put("PHOTO BLUE/SUMMIT DEEP ROYAL","Medium Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/TEAM RED","Medium Red");
		COLOR_MAP.put("PURE PLATINUM/ANTHRACITE","Medium Gray");
		COLOR_MAP.put("MIDNIGHT NAVY/BRIGHT CRIMSON/DARK","Dark Blue");
		COLOR_MAP.put("OMEGA BLUE","Medium White");
		COLOR_MAP.put("WOLF BETA BLUE","Medium Gray");
		COLOR_MAP.put("COPA/DARK GREY","Medium Black");
		COLOR_MAP.put("COOL MTLC COOL GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/COOL ANTHRACITE/","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/MTLC COOL GREY","Medium White");
		COLOR_MAP.put("UNIVERSITY RED/WOLF METALLIC","Medium White");
		COLOR_MAP.put("WOLF RACER BLUE","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/COOL VIVID","Medium Gray");
		COLOR_MAP.put("COOL METALLIC SILVER","Medium Black");
		COLOR_MAP.put("PURE PLATINUM","Medium White");
		COLOR_MAP.put("OBSIDIAN/BRIGHT CRIMSON","Medium White");
		COLOR_MAP.put("PURE PLATINUM/PHOTO BLUE","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/COOL RAGE GREEN","Medium Gray");
		COLOR_MAP.put("WOLF ANTHRACITE","Medium Gray");
		COLOR_MAP.put("GUM YELLOW/MIDNIGHT NAVY","Medium White");
		COLOR_MAP.put("LIGHT BONE/DUST/UNIVERSITY RED","Medium Brown");
		COLOR_MAP.put("PURE PLATINUM/SAIL/ACTION RED","Medium Gray");
		COLOR_MAP.put("BRIGHT CRIMSON/METALLIC SILVER","Medium White");
		COLOR_MAP.put("MTLC COOL GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON/","Medium White");
		COLOR_MAP.put("DEEP ROYAL BLUE/MIDNIGHT NAVY/BRIGHT","Bright Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/UNIVERSITY RED/","Medium White");
		COLOR_MAP.put("VIVID ORANGE/HYPER PINK","Medium White");
		COLOR_MAP.put("BRIGHT CRIMSON/HYPER ORANGE/MIDNIGHT","Medium Red");
		COLOR_MAP.put("MIDNIGHT NAVY/CHALK BLUE/BRIGHT","Dark Blue");
		COLOR_MAP.put("COSMIC PURPLE/VIVID ORANGE","Medium Purple");
		COLOR_MAP.put("WOLF GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON/MIDNIGHT","Medium Gray");
		COLOR_MAP.put("COSMIC PURPLE/ANTHRACITE","Medium White");
		COLOR_MAP.put("COOL ANTHRACITE","Medium White");
		COLOR_MAP.put("BRIGHT CRIMSON/FIERCE PURPLE/","Medium White");
		COLOR_MAP.put("PURE PLATINUM/COSMIC PURPLE/DIGITAL PINK/","Medium Gray");
		COLOR_MAP.put("DARK MTLC DARK GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/DARK COOL","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON","Medium Gray");
		COLOR_MAP.put("CHALK BLUE/MIDNIGHT NAVY","Medium Blue");
		COLOR_MAP.put("HYPER TURQ","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/HYPER PINK","Medium White");
		COLOR_MAP.put("DEEP ROYAL BLUE/BRIGHT CRIMSON/SAIL","Bright Blue");
		COLOR_MAP.put("ANTHRACITE/VOLTAGE GREEN","Medium Gray");
		COLOR_MAP.put("PHOTO BLUE/PHOTO BLUE","Medium White");
		COLOR_MAP.put("VOLTAGE GREEN","Medium Green");
		COLOR_MAP.put("HYPER COBALT/WOLF WOLF GREY","Medium Blue");
		COLOR_MAP.put("HYPER COBALT/WOLF GREY","Medium Blue");
		COLOR_MAP.put("BLUE OCEAN FOG","Medium Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/UNIVERSITY RED","Medium Red");
		COLOR_MAP.put("MIDNIGHT NAVY/HYPER COBALT","Dark Blue");
		COLOR_MAP.put("TARP GREEN/SQUADRON BLUE","Medium White");
		COLOR_MAP.put("STADIUM GREY","Medium White");
		COLOR_MAP.put("NIGHT STADIUM","Medium White");
		COLOR_MAP.put("MED BASE GREY","Medium Black");
		COLOR_MAP.put("DK GREY HEATHER/DARK BASE GREY","Medium Gray");
		COLOR_MAP.put("CLASSIC STONE/BAROQUE BROWN","Medium Brown");
		COLOR_MAP.put("IRON ORE","Medium White");
		COLOR_MAP.put("DARK CHINO HTR","Medium Gray");
		COLOR_MAP.put("BIRCH HEATHER/CHALK BLUE/MIDNIGHT NAVY","Medium Brown");
		COLOR_MAP.put("BIRCH HEATHER/CARBON HEATHER/OBSIDIAN","Medium Brown");
		COLOR_MAP.put("LT CRIMSON","Medium White");
		COLOR_MAP.put("VIOLET SHADE","Medium White");
		COLOR_MAP.put("TURF ORANGE","Medium White");
		COLOR_MAP.put("HYPER PINK/MEDIUM OLIVE","Medium Pink");
		COLOR_MAP.put("CAMOUFLAGE","Multi Color");
		COLOR_MAP.put("STARS/STRIPES","Dark Blue");
		COLOR_MAP.put("FULL CUSTOM - NAVY","Dark Blue");
		COLOR_MAP.put("SILVER/GYM RED","Medium Gray");
		COLOR_MAP.put("DARK OBSIDIAN/SILVER/PHOTO BLUE","Medium Blue");
		COLOR_MAP.put("MEDIUM OLIVE/SILVER/BRIGHT CRIMSON","Medium Green");
		COLOR_MAP.put("BLUE AZURE","Medium Blue");
		COLOR_MAP.put("TITANIUM","Titanium Metal");
		COLOR_MAP.put("EMERALD GREEN","Medium Green");
		COLOR_MAP.put("RUBY RED","Medium Red");
		COLOR_MAP.put("FOLKSTONE GRAY","Medium Gray");
		COLOR_MAP.put("AURORA","Medium Yellow");
		COLOR_MAP.put("VIVID VIOLA","Medium Purple");
		COLOR_MAP.put("HAWAIIAN OCEAN","Light Blue");
		COLOR_MAP.put("STRONG BLUE","Bright Blue");
		COLOR_MAP.put("PUMA RED","Medium Red");
		COLOR_MAP.put("BRIGHT GREEN","Medium Green");
		COLOR_MAP.put("MAROON HEATHER","Dark Red");
		COLOR_MAP.put("OATMEAL HEATHER","Copper Metal");
		COLOR_MAP.put("FOOTWEAR FOOTWEAR CORE BLACK","Medium White");
		COLOR_MAP.put("CORE CORE IRON MET","Medium Black");
		COLOR_MAP.put("CORE DARK SILVER METALLIC/RED","Medium Black");
		COLOR_MAP.put("FOOTWEAR SILVER METALLIC/CORE BLACK","Medium White");
		COLOR_MAP.put("FOOTWEAR MINERAL BLUE/SHOCK BLUE","Medium White");
		COLOR_MAP.put("FOOTWEAR DARK SILVER METALLIC/SOLAR YELLOW","Medium White");
		COLOR_MAP.put("DARK SILVER METALLIC","Medium White");
		COLOR_MAP.put("IRON/RUNNING BLACK","Medium Gray");
		COLOR_MAP.put("ONIX/IRON MET/SOLAR YELLOW","Medium Gray");
		COLOR_MAP.put("CORE CORE FTWR WHITE","Medium Black");
		COLOR_MAP.put("HT GREY HEATHER SOLID LIGHT GREY HEATHER SOLID FOO","Medium Gray");
		COLOR_MAP.put("FOOTWEAR FOOTWEAR GUM","Medium White");
		COLOR_MAP.put("ONIX/LIGHT ONIX/FOOTWEAR WHTIE","Medium Gray");
		COLOR_MAP.put("CORE CORE FOOTWEAR WHITE","Medium Black");
		COLOR_MAP.put("BROWN/FOOTWEAR EQUIPMENT GREEN","Medium Brown");
		COLOR_MAP.put("FOOTWEAR SILVER METALLIC/BAJA BLUE","Medium White");
		COLOR_MAP.put("CORE DARK GREY HEATER SOLID SUNSET CORAL","Medium Gray");
		COLOR_MAP.put("FOOTWEAR MATTE SILVER/WILD ORCHID","Medium White");
		COLOR_MAP.put("BAJA BLUE/SHOCK RED/BAJA BLUE","Medium Blue");
		COLOR_MAP.put("MINT BURST/LAVENDER MIST/SILVER MET","Medium Green");
		COLOR_MAP.put("FOOTWEAR LIGHT ONIX/SILVER MET","Medium White");
		COLOR_MAP.put("PROJECT X LZ PRO","Other");
		COLOR_MAP.put("PROJECT X SD","Other");
		COLOR_MAP.put("SILVER METALLIC/FLASH RED","Medium White");
		COLOR_MAP.put("CLEAR ONIX/RUNNING SOLAR RED","Clear");
		COLOR_MAP.put("FOOTWEAR CORE BOLD RED","Medium White");
		COLOR_MAP.put("FOOTWEAR MATTE SILVER/RASPBERRY ROSE","Clear");
		COLOR_MAP.put("MONK'S ROBE-TEAM GOLD","Dark Yellow");
		COLOR_MAP.put("DRIZZLE","Medium White");
		COLOR_MAP.put("CHIPMUNK-PEACOAT","Medium Brown");
		COLOR_MAP.put("TURBULENCE-HIGH RISK RED","Medium White");
		COLOR_MAP.put("BLACK PEARL","Medium Black");
		COLOR_MAP.put("PINE","Silver Metal");
		COLOR_MAP.put("PINK/RIBBON","Medium Pink");
		COLOR_MAP.put("WINE","Medium Red");
		COLOR_MAP.put("KHAKI/GREEN","Medium Brown");
		COLOR_MAP.put("NAVY/RED","Dark Blue");
		COLOR_MAP.put("CHARCOAL/RED","Medium Gray");
		COLOR_MAP.put("ROYAL BLUE/CHARCOAL","Bright Blue");
		COLOR_MAP.put("GRAY/AQUA","Medium Gray");
		COLOR_MAP.put("BLACK POLKA DOT","Medium Black");
		COLOR_MAP.put("SHAFT - PROJECT X LZ","Other");
		COLOR_MAP.put("TRADEWINDS-GREEN GECKO","Medium Green");
		COLOR_MAP.put("QUICKSILVER-CAYENNE","Medium Gray");
		COLOR_MAP.put("TURBULENCE","Medium Black");
		COLOR_MAP.put("WHITE SWAN","Medium White");
		COLOR_MAP.put("BISON BROWN","Medium Brown");
		COLOR_MAP.put("LIMESTONE GRAY","Medium White");
		COLOR_MAP.put("CLOISONNE","Medium Black");
		COLOR_MAP.put("SPICY ORANGE","Bright Orange");
		COLOR_MAP.put("GRAY VIOLET","Light Purple");
		COLOR_MAP.put("PUMA SILVER","Light Gray");
		COLOR_MAP.put("HIGH-RISE-FLUO PEACH","Medium Orange");
		COLOR_MAP.put("CACTUS FLOWER-ORCHID BLOOM PURPLE","Medium White");
		COLOR_MAP.put("OPTIC PINK","Medium Pink");
		COLOR_MAP.put("OPTIC YELLOW","Medium Yellow");
		COLOR_MAP.put("SHAFT - PROJECT X LZ PRO","Other");
		COLOR_MAP.put("","");


	}
	public static String getColorGroup(String colorName){
		return COLOR_MAP.get(colorName.toUpperCase());
	}
}
