package parser.proGolf;

import java.util.HashMap;
import java.util.Map;

public class ProGolfColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Name","Color Group");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Dark Black","Dark Black");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Royal","Medium Blue");
		COLOR_MAP.put("Blue Steel","Medium Blue");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Khaki","Medium Brown");
		COLOR_MAP.put("Camo","Camouflage Brown");
		COLOR_MAP.put("Clay","Light Brown");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Pink Champagne","Medium Pink");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Mocha","Medium Brown");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Sungold","Medium Yellow");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Matte White","Medium White");
		COLOR_MAP.put("Matte Blue","Medium Blue");
		COLOR_MAP.put("Vista Gray","Medium Gray");
		COLOR_MAP.put("Stone","Light Gray");
		COLOR_MAP.put("Nomad Red","Medium Red");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Aero Blue","Medium Blue");
		COLOR_MAP.put("Gym Blue","Medium Blue");
		COLOR_MAP.put("Nickel","Nickel Metal");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Hi-Vis Orange","Bright Orange");
		COLOR_MAP.put("Volt Green","Medium Green");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Magnetic Blue","Bright Blue");
		COLOR_MAP.put("Quiet Shade","Medium Gray");
		COLOR_MAP.put("Sand","Light Brown");
		COLOR_MAP.put("Lavender","Medium Purple");
		COLOR_MAP.put("True Navy Heather","Dark Blue");
		COLOR_MAP.put("Blue Wake Heather","Bright Blue");
		COLOR_MAP.put("Cardinal Heather","Medium Red");
		COLOR_MAP.put("Cobalt Heather","Medium Blue");
		COLOR_MAP.put("Deep Orange Heather","Dark Orange");
		COLOR_MAP.put("Forest Green Heather","Dark Green");
		COLOR_MAP.put("Graphite Heather","Medium Gray");
		COLOR_MAP.put("Scarlet Heather","Dark Red");
		COLOR_MAP.put("Turf Green Heather","Bright Green");
		COLOR_MAP.put("Varsity Purple Heather","Medium Purple");
		COLOR_MAP.put("Vintage Heather","Medium Gray");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Hunter Green","Dark Green");
		COLOR_MAP.put("Royal Blue","Dark Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Natural Tan","Light Brown");
		COLOR_MAP.put("Lime","Light Green");
		COLOR_MAP.put("Coastal Blue","Medium Blue");
		COLOR_MAP.put("Chocolate","Medium Brown");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("Vegas Gold","Dark Yellow");
		COLOR_MAP.put("Texas Orange","Medium Orange");
		COLOR_MAP.put("Gray Concrete","Medium Gray");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Blue Lake","Medium Blue");
		COLOR_MAP.put("Deep Orange","Dark Orange");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Iron Gray","Dark Gray");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Tropic Blue","Medium Green");
		COLOR_MAP.put("True Red","Medium Red");
		COLOR_MAP.put("True Royal","Medium Blue");
		COLOR_MAP.put("True Navy","Dark Blue");
		COLOR_MAP.put("Pink Raspberry Heather","Dark Pink");
		COLOR_MAP.put("Diesel Grey","Medium Gray");
		COLOR_MAP.put("Teal Spark","Light Blue");
		COLOR_MAP.put("Pink Luxe","Medium Pink");
		COLOR_MAP.put("Provence Blue","Light Blue");
		COLOR_MAP.put("Salsa Red","Medium Red");
		COLOR_MAP.put("Smoked Pearl","Light Gray");
		COLOR_MAP.put("Classic Charcoal","Medium Gray");
		COLOR_MAP.put("Watermelon","Light Red");
		COLOR_MAP.put("Purple Slate","Medium Purple");
		COLOR_MAP.put("Red Violet","Medium Red");
		COLOR_MAP.put("Base Grey","Medium Gray");
		COLOR_MAP.put("Coral","Medium Pink");
		COLOR_MAP.put("Plum","Medium Purple");
		COLOR_MAP.put("Grey","Medium Gray");
		COLOR_MAP.put("Marine","Light Blue");
		COLOR_MAP.put("British Khaki","Light Brown");
		COLOR_MAP.put("Steel Blue","Bright Blue");
		COLOR_MAP.put("Sandstone","Medium Yellow");
		COLOR_MAP.put("Storm Blue","Bright Blue");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Team Red","Medium Red");
		COLOR_MAP.put("Mint","Medium Green");
		COLOR_MAP.put("Frost Blue","Light Blue");
		COLOR_MAP.put("Fruit Punch","Medium Red");
		COLOR_MAP.put("Seaswell","Medium Green");
		COLOR_MAP.put("Shock Red","Bright Red");
		COLOR_MAP.put("Jacaranda","Medium Purple");
		COLOR_MAP.put("Shock Mint","Medium Green");
		COLOR_MAP.put("French Navy","Dark Blue");
		COLOR_MAP.put("Eucalyptus","Medium Green");
		COLOR_MAP.put("Mist","Light Blue");
		COLOR_MAP.put("Chemical Turquoise","Medium Green");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Bahia Blue","Bright Blue");
		COLOR_MAP.put("Nylon Lime","Bright Green");
		COLOR_MAP.put("Nomad Orange","Medium Orange");
		COLOR_MAP.put("EQT Blue","Medium Blue");
		COLOR_MAP.put("Shock Blue","Bright Blue");
		COLOR_MAP.put("Eqt Pink","Medium Pink");
		COLOR_MAP.put("Sharp Lemon","Medium Yellow");
		COLOR_MAP.put("Grasshopper","Medium Green");
		COLOR_MAP.put("Mineral Blue","Medium Blue");
		COLOR_MAP.put("Sea Lettuce","Medium Green");
		COLOR_MAP.put("Full Custom - Black","Medium Black");
		COLOR_MAP.put("Full Custom - White","Medium White");
		COLOR_MAP.put("Matte Gray","Medium Gray");
		COLOR_MAP.put("Crimson","Dark Red");
		COLOR_MAP.put("White (Polka Dot)","Medium White");
		COLOR_MAP.put("Rainbow","Multi Color");
		COLOR_MAP.put("Court Purple","Medium Purple");
		COLOR_MAP.put("Lucky Green","Medium Green");
		COLOR_MAP.put("Blue Sapphire","Medium Blue");
		COLOR_MAP.put("Flint Gray","Medium Gray");
		COLOR_MAP.put("Midnight Navy","Dark Blue");
		COLOR_MAP.put("Brown Plaid","Medium Brown");
		COLOR_MAP.put("Vivid Green","Medium Green");
		COLOR_MAP.put("Olive Khaki","Dark Green");
		COLOR_MAP.put("Orange Blaze","Medium Orange");
		COLOR_MAP.put("Pro Red","Medium Red");
		COLOR_MAP.put("University Blue","Light Blue");
		COLOR_MAP.put("Varsity Purple","Medium Purple");
		COLOR_MAP.put("Varsity Royal","Medium Blue");
		COLOR_MAP.put("Carbon","Medium Gray");
		COLOR_MAP.put("Insignia Blue","Medium Blue");
		COLOR_MAP.put("Light Blueberry","Light Blue");
		COLOR_MAP.put("Chlorophyll","Medium Green");
		COLOR_MAP.put("Pro Blue","Medium Blue");
		COLOR_MAP.put("Varsity Red","Medium Red");
		COLOR_MAP.put("Vibrant Blue","Medium Blue");
		COLOR_MAP.put("Light Game Royal Heather","Medium Blue");
		COLOR_MAP.put("Black Heather","Medium Black");
		COLOR_MAP.put("Carbon Heather","Other");
		COLOR_MAP.put("Monsoon Heather","Medium Blue");
		COLOR_MAP.put("Oatmeal","Light Brown");
		COLOR_MAP.put("Tortoise","Light Green");
		COLOR_MAP.put("Solar Orange","Medium Orange");
		COLOR_MAP.put("Anthracite","Medium Gray");
		COLOR_MAP.put("Pacific Blue","Medium Blue");
		COLOR_MAP.put("French Blue","Medium Blue");
		COLOR_MAP.put("Skyline Blue","Medium Blue");
		COLOR_MAP.put("Signal Blue","Medium Blue");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Pastel Pink","Medium Pink");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Pine Green","Medium Green");
		COLOR_MAP.put("Bright Blue","Bright Blue");
		COLOR_MAP.put("Optic Orange","Medium Orange");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Brushed Nickel","Nickel Metal");
		COLOR_MAP.put("Petrol","Other");
		COLOR_MAP.put("Action Green","Medium Green");
		COLOR_MAP.put("Volt","Medium Green");
		COLOR_MAP.put("Cool Grey","Light Gray");
		COLOR_MAP.put("Blustery","Medium Green");
		COLOR_MAP.put("Old Royal","Dark Blue");
		COLOR_MAP.put("University Red","Medium Red");
		COLOR_MAP.put("Brisk Blue","Medium Blue");
		COLOR_MAP.put("Pink Fire","Medium Pink");
		COLOR_MAP.put("Chartreuse","Medium Green");
		COLOR_MAP.put("Deep Royal Blue","Light Blue");
		COLOR_MAP.put("Dark Grey","Light Gray");
		COLOR_MAP.put("Light Photo Blue","Dark Blue");
		COLOR_MAP.put("Gym Red","Medium Red");
		COLOR_MAP.put("Wasabe Green","Medium Green");
		COLOR_MAP.put("Challenge Red","Medium Red");
		COLOR_MAP.put("College Navy","Dark Blue");
		COLOR_MAP.put("Bright Crimson","Bright Red");
		COLOR_MAP.put("Pink Pow","Medium Pink");
		COLOR_MAP.put("Shiny Nickel","Nickel Metal");
		COLOR_MAP.put("Antique Bronze","Bronze Metal");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Antique Nickel","Medium Gray");
		COLOR_MAP.put("Bronze","Medium Brown");
		COLOR_MAP.put("Dark Yellow","Dark Yellow");
		COLOR_MAP.put("Medium Blue","Medium Blue");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Metallic Yellow","Metallic Yellow");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("Passion Fruit","Medium Pink");
		COLOR_MAP.put("Light Purple","Medium Purple");
		COLOR_MAP.put("Cranberry","Medium Red");
		COLOR_MAP.put("Dark Purple","Medium Purple");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Carnival Mix","Multi Color");
		COLOR_MAP.put("Designer Mix","Multi Color");
		COLOR_MAP.put("Neon Mix","Multi Color");
		COLOR_MAP.put("Regular Mix","Multi Color");
		COLOR_MAP.put("Tropical Mix","Multi Color");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Power Red","Medium Red");
		COLOR_MAP.put("Equipment Blue","Medium Blue");
		COLOR_MAP.put("Bright Royal","Bright Blue");
		COLOR_MAP.put("Sesame","Medium Yellow");
		COLOR_MAP.put("Mid Gray","Medium Gray");
		COLOR_MAP.put("Amazon","Medium Green");
		COLOR_MAP.put("Tawny Port","Light Brown");
		COLOR_MAP.put("Heather Grey","Medium Gray");
		COLOR_MAP.put("CornSilk","Medium Yellow");
		COLOR_MAP.put("Team Orange","Medium Orange");
		COLOR_MAP.put("Fusion Pink","Medium Pink");
		COLOR_MAP.put("Night Purple","Medium Purple");
		COLOR_MAP.put("Mean Green","Medium Green");
		COLOR_MAP.put("Tidal Blue","Light Blue");
		COLOR_MAP.put("Aluminum Pink","Medium Pink");
		COLOR_MAP.put("Lawn","Light Green");
		COLOR_MAP.put("Valor Blue","Light Blue");
		COLOR_MAP.put("Team Green","Medium Green");
		COLOR_MAP.put("Trails End Brown","Medium Brown");
		COLOR_MAP.put("Midnight Navy Blue","Dark Blue");
		COLOR_MAP.put("Pinenut","Light Brown");
		COLOR_MAP.put("Flamingo","Bright Pink");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Magenta","Medium pink");
		COLOR_MAP.put("Fire","Medium Red");
		COLOR_MAP.put("True White","Medium White");
		COLOR_MAP.put("Dark Khaki","Medium Brown");
		COLOR_MAP.put("Deep Black","Medium Black");
		COLOR_MAP.put("Deep Navy","Dark Blue");
		COLOR_MAP.put("Grey Stripe","Medium Gray");
		COLOR_MAP.put("Bright Lime","Bright Green");
		COLOR_MAP.put("Red-White Stripe","Medium Red");
		COLOR_MAP.put("White Stripe","Medium White");
		COLOR_MAP.put("Black Stripe","Medium Black");
		COLOR_MAP.put("Highrise","Medium Gray");
		COLOR_MAP.put("Silver Lining","Silver Metal");
		COLOR_MAP.put("Riviera Blue","Light Blue");
		COLOR_MAP.put("New Blue","Medium Blue");
		COLOR_MAP.put("Varsity Royal-White","Medium Blue");
		COLOR_MAP.put("Varsity Red-Black","Medium Red");
		COLOR_MAP.put("Cobalt","Medium Blue");
		COLOR_MAP.put("Fracture","Dark Gray");
		COLOR_MAP.put("Griddle","Medium Black");
		COLOR_MAP.put("Metallic","Assorted");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Silver-Black","Medium Gray");
		COLOR_MAP.put("Noble Green","Medium Green");
		COLOR_MAP.put("Lake Blue","Light Blue");
		COLOR_MAP.put("Sport Red","Medium Red");
		COLOR_MAP.put("Olive","Medium Green");
		COLOR_MAP.put("Heather Gray","Medium Gray");
		COLOR_MAP.put("Storm Gray","Medium Gray");
		COLOR_MAP.put("Sunset","Medium Purple");
		COLOR_MAP.put("Terra","Other");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Gun Metal","Medium Gray");
		COLOR_MAP.put("Heather Charcoal","Medium Gray");
		COLOR_MAP.put("Berry","Medium Pink");
		COLOR_MAP.put("Mid Blue","Medium Blue");
		COLOR_MAP.put("Jade","Medium Green");
		COLOR_MAP.put("Cream","Medium White");
		COLOR_MAP.put("Fushia","Medium Purple");
		COLOR_MAP.put("Neon Green(Solid or Clear)","Medium Green");
		COLOR_MAP.put("Pewter","Medium Gray");
		COLOR_MAP.put("Neon Pink (Solid or Clear)","Medium Pink");
		COLOR_MAP.put("Neon Orange(Solid or Clear)","Medium Orange");
		COLOR_MAP.put("Pink Rush","Medium Pink");
		COLOR_MAP.put("Citron","Medium Yellow");
		COLOR_MAP.put("Blue Wake","Medium Green");
		COLOR_MAP.put("Carolina Blue","Medium Blue");
		COLOR_MAP.put("Neon Orange (Solid or Clear)","Medium Orange");
		COLOR_MAP.put("Clear Neon Yellow","Medium Yellow");
		COLOR_MAP.put("Neon Green (Solid or Clear)","Medium Green");
		COLOR_MAP.put("Brass","Dark Yellow");
		COLOR_MAP.put("Fuschia","Medium Purple");
		COLOR_MAP.put("Peach","Medium Orange");
		COLOR_MAP.put("Light Pink","Light Pink");
		COLOR_MAP.put("Pink Raspberry","Dark Pink");
		COLOR_MAP.put("Carrot","Medium Orange");
		COLOR_MAP.put("Vibrant Green","Medium Green");
		COLOR_MAP.put("Purple Magic","Medium Purple");
		COLOR_MAP.put("Zinfandel","Medium Purple");
		COLOR_MAP.put("Bright White","Bright White");
		COLOR_MAP.put("Equipment Green","Medium Green");
		COLOR_MAP.put("Equipment Pink","Medium Pink");
		COLOR_MAP.put("Light Yellow","Light Yellow");
		COLOR_MAP.put("Chili Pepper","Medium Red");
		COLOR_MAP.put("Mandarin Orange","Medium Orange");
		COLOR_MAP.put("Paisley Purple","Medium Purple");
		COLOR_MAP.put("Blue Atoll","Bright Blue");
		COLOR_MAP.put("Bird of Paradise","Multi Color");
		COLOR_MAP.put("Paradise","Light Blue");
		COLOR_MAP.put("Parakeet","Medium Green");
		COLOR_MAP.put("Griffin Gray","Medium Gray");
		COLOR_MAP.put("Pool Blue","Medium Blue");
		COLOR_MAP.put("Rebel Red","Medium Red");
		COLOR_MAP.put("Purple Luxe","Medium Purple");
		COLOR_MAP.put("Blue Indigo","Medium Blue");
		COLOR_MAP.put("Royal Enamel","Bright Blue");
		COLOR_MAP.put("Blacktop","Medium Black");
		COLOR_MAP.put("Hunter","Dark Green");
		COLOR_MAP.put("Metallic Silver","Silver Metal");
		COLOR_MAP.put("Caviar Black","Medium Black");
		COLOR_MAP.put("Palace Blue","Light Blue");
		COLOR_MAP.put("Gray Heather","Medium Gray");
		COLOR_MAP.put("Taupia","Medium Brown");
		COLOR_MAP.put("Clear Blue","Light Blue");
		COLOR_MAP.put("Navy Heather","Dark Blue");
		COLOR_MAP.put("Lucky Blue","Medium Blue");
		COLOR_MAP.put("Bright Orange","Bright Orange");
		COLOR_MAP.put("Dark Slate","Dark Gray");
		COLOR_MAP.put("Blast Blue","Medium Blue");
		COLOR_MAP.put("Core Blue","Medium Blue");
		COLOR_MAP.put("Light Aqua","Light Blue");
		COLOR_MAP.put("Scarlet","Medium Red");
		COLOR_MAP.put("Ultra Beauty","Other");
		COLOR_MAP.put("Shock Pink","Medium Pink");
		COLOR_MAP.put("Energy","Other");
		COLOR_MAP.put("Vivid Yellow","Bright Yellow");
		COLOR_MAP.put("Solar Lime","Bright Green");
		COLOR_MAP.put("white plain toe","Medium White");
		COLOR_MAP.put("black plain toe saddle","Medium Black");
		COLOR_MAP.put("brown plain toe saddle","Medium Brown");
		COLOR_MAP.put("tan cvo pattern","Medium Brown");
		COLOR_MAP.put("dark blue cvo pattern","Medium Blue");
		COLOR_MAP.put("charcoal cvo pattern","Medium Gray");
		COLOR_MAP.put("dark brown wallaby","Medium Brown");
		COLOR_MAP.put("black wallaby","Medium Black");
		COLOR_MAP.put("Ocean","Light Blue");
		COLOR_MAP.put("Estate Blue","Medium Blue");
		COLOR_MAP.put("Battleship Gray","Medium Gray");
		COLOR_MAP.put("Garnet","Other");
		COLOR_MAP.put("Posh Purple","Medium Purple");
		COLOR_MAP.put("True Royal Heather","Bright Blue");
		COLOR_MAP.put("Charge Green","Medium Green");
		COLOR_MAP.put("Charcoal Gray Heather","Medium Gray");
		COLOR_MAP.put("Charcoal Grey","Medium Gray");
		COLOR_MAP.put("Medium Gray Heather","Medium Gray");
		COLOR_MAP.put("Raspberry Rose Heather","Medium Pink");
		COLOR_MAP.put("Wild Orchid Heather","Medium Pink");
		COLOR_MAP.put("Sunset Coral Heather","Medium Orange");
		COLOR_MAP.put("Deep Blue Heather","Dark Blue");
		COLOR_MAP.put("Baja Blue Heather","Bright Blue");
		COLOR_MAP.put("Green Glen","Medium Green");
		COLOR_MAP.put("Vine Green","Medium Green");
		COLOR_MAP.put("Autumn Orange","Medium Orange");
		COLOR_MAP.put("Gray Smoke","Medium Gray");
		COLOR_MAP.put("Hyper Blue","Medium Blue");
		COLOR_MAP.put("Ocean Blue","Medium Blue");
		COLOR_MAP.put("Rich Red","Medium Red");
		COLOR_MAP.put("Violet Purple","Medium Purple");
		COLOR_MAP.put("white traditional saddle","Medium White");
		COLOR_MAP.put("tan suede","Medium Brown");
		COLOR_MAP.put("navy suede","Dark Blue");
		COLOR_MAP.put("chocolate brown","Medium Brown");
		COLOR_MAP.put("antique tan driving moc","Medium Brown");
		COLOR_MAP.put("black driving moc","Medium Black");
		COLOR_MAP.put("white velcro athletic","Medium White");
		COLOR_MAP.put("white athletic","Medium White");
		COLOR_MAP.put("fj cascade boot","Other");
		COLOR_MAP.put("dark taupe sandal","Medium Brown");
		COLOR_MAP.put("black slide","Medium Black");
		COLOR_MAP.put("english tan cap toe","Medium Brown");
		COLOR_MAP.put("black cap toe","Medium Black");
		COLOR_MAP.put("black moc toe","Medium Black");
		COLOR_MAP.put("cognac moc toe","Medium Brown");
		COLOR_MAP.put("graffiti print moe toe velcro","Medium Black");
		COLOR_MAP.put("zebra/fuschia U-throat","Medium Purple");
		COLOR_MAP.put("cheetah/dark brown U-throat","Dark Brown");
		COLOR_MAP.put("white sport contrast stitch","Medium White");
		COLOR_MAP.put("chablis sport contrast stitch","Other");
		COLOR_MAP.put("deep blue sport contrast stitch","Medium Blue");
		COLOR_MAP.put("black sport contrast stitch","Medium Black");
		COLOR_MAP.put("tan sport contrast stitch","Medium Brown");
		COLOR_MAP.put("white bicycle toe","Medium White");
		COLOR_MAP.put("white U-throat umbrella","Medium White");
		COLOR_MAP.put("red U-throat umbrella","Medium Red");
		COLOR_MAP.put("navy U-throat umbrella","Dark Blue");
		COLOR_MAP.put("rainbow swept back saddle","Medium White");
		COLOR_MAP.put("pink rose engineered mesh","Medium Pink");
		COLOR_MAP.put("sea foam engineered mesh","Medium Green");
		COLOR_MAP.put("pool blue engineered mesh","Medium Blue");
		COLOR_MAP.put("grey mist engineered mesh","Medium Gray");
		COLOR_MAP.put("Brilliant Blue","Medium Blue");
		COLOR_MAP.put("Bright Purple","Medium Purple");
		COLOR_MAP.put("Neon Yellow","Medium Yellow");
		COLOR_MAP.put("Steel Gray","Medium Gray");
		COLOR_MAP.put("Teal Green","Medium Green");
		COLOR_MAP.put("Dress Blue Navy","Dark Blue");
		COLOR_MAP.put("Running Core Core Black","Medium White");
		COLOR_MAP.put("Core Silver Metallic","Silver Metal");
		COLOR_MAP.put("Running White","Medium White");
		COLOR_MAP.put("Birch","Light Gray");
		COLOR_MAP.put("Acid","Light Green");
		COLOR_MAP.put("Dark Gray Heather","Medium Gray");
		COLOR_MAP.put("Obsidian","Medium Blue");
		COLOR_MAP.put("Game Royal","Medium Blue");
		COLOR_MAP.put("Gridiron Green","Medium Green");
		COLOR_MAP.put("Signal Red","Medium Red");
		COLOR_MAP.put("Electric Blue","Bright Blue");
		COLOR_MAP.put("Yield Yellow","Light Yellow");
		COLOR_MAP.put("Blue Spark","Medium Blue");
		COLOR_MAP.put("Fair Blue","Light Blue");
		COLOR_MAP.put("Clorophyll","Medium Green");
		COLOR_MAP.put("Urban Haze","Light Green");
		COLOR_MAP.put("Tour Yellow","Medium Yellow");
		COLOR_MAP.put("Photo Blue","Medium Blue");
		COLOR_MAP.put("Blueprint","Medium Blue");
		COLOR_MAP.put("Diesel Gray","Medium Gray");
		COLOR_MAP.put("Acid Green","Medium Green");
		COLOR_MAP.put("Sky Blue","Light Blue");
		COLOR_MAP.put("Slate","Light Gray");
		COLOR_MAP.put("Brick Red","Medium Red");
		COLOR_MAP.put("Burnt Orange","Medium Orange");
		COLOR_MAP.put("Mustard","Medium Yellow");
		COLOR_MAP.put("Wasabe","Light Green");
		COLOR_MAP.put("CHALK BLUE","Medium Blue");
		COLOR_MAP.put("Fern Green","Medium Green");
		COLOR_MAP.put("Nine Iron","Medium Gray");
		COLOR_MAP.put("Marine Blue","Dark Blue");
		COLOR_MAP.put("Legend Blue","Medium Blue");
		COLOR_MAP.put("Clay Green","Medium Green");
		COLOR_MAP.put("navy/blue","Medium White");
		COLOR_MAP.put("bone","Medium White");
		COLOR_MAP.put("Deep Royal","Dark Blue");
		COLOR_MAP.put("Cardinal","Medium Red");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Steel","Medium Gray");
		COLOR_MAP.put("Nautical Blue","Medium Blue");
		COLOR_MAP.put("Reef Blue","Bright Blue");
		COLOR_MAP.put("Vivid Pink","Medium Pink");
		COLOR_MAP.put("Olive Camo","Medium Green");
		COLOR_MAP.put("Matte Silver","Silver Metal");
		COLOR_MAP.put("Vibrant Orange","Medium Orange");
		COLOR_MAP.put("High Risk Red","Medium Red");
		COLOR_MAP.put("Atomic Blue","Medium Blue");
		COLOR_MAP.put("Columbia","Medium Green");
		COLOR_MAP.put("Quarry","Medium Gray");
		COLOR_MAP.put("Peacoat Heather","Dark Blue");
		COLOR_MAP.put("Light Grey Heather","Medium Gray");
		COLOR_MAP.put("Blue Heaven","Medium Blue");
		COLOR_MAP.put("Omphalodes","Light Blue");
		COLOR_MAP.put("Green Gecko","Medium Green");
		COLOR_MAP.put("Zinnia","Medium Orange");
		COLOR_MAP.put("Orchid Bloom","Medium Purple");
		COLOR_MAP.put("Rose Red","Medium Red");
		COLOR_MAP.put("Bering Sea","Dark Blue");
		COLOR_MAP.put("Cool Blue","Light Blue");
		COLOR_MAP.put("Mint Leaf","Medium Green");
		COLOR_MAP.put("Cherry Tomato","Medium Red");
		COLOR_MAP.put("Purple Cactus Flower","Medium Purple");
		COLOR_MAP.put("Fluro Peach","Bright Orange");
		COLOR_MAP.put("Dazzling Blue","Bright Blue");
		COLOR_MAP.put("Light Gray Heather","Medium Gray");
		COLOR_MAP.put("Peacoat","Dark Blue");
		COLOR_MAP.put("Surf the Web","Medium Blue");
		COLOR_MAP.put("Shock Green","Bright Green");
		COLOR_MAP.put("Voltage Blue","Medium Blue");
		COLOR_MAP.put("Pink Crush","Bright Pink");
		COLOR_MAP.put("Alloy Green","Medium Green");
		COLOR_MAP.put("Black Top","Medium Black");
		COLOR_MAP.put("Blue Ribbon","Medium Blue");
		COLOR_MAP.put("Piston Purple","Dark Purple");
		COLOR_MAP.put("Blue Print","Medium Blue");
		COLOR_MAP.put("Berry Burst","Medium Purple");
		COLOR_MAP.put("Violet","Medium Purple");
		COLOR_MAP.put("Asphalt","Medium Black");
		COLOR_MAP.put("Coral Sunset","Medium Orange");
		COLOR_MAP.put("Petrol Gray","Medium Gray");
		COLOR_MAP.put("Cargo Brown","Medium Brown");
		COLOR_MAP.put("Astro Green","Medium Green");
		COLOR_MAP.put("Purple Haze","Medium Purple");
		COLOR_MAP.put("Pink Rouge","Bright Pink");
		COLOR_MAP.put("Blue Enamel","Medium Blue");
		COLOR_MAP.put("Flare Orange","Medium Orange");
		COLOR_MAP.put("Matte Black","Medium Black");
		COLOR_MAP.put("Met Silver","Medium Gray");
		COLOR_MAP.put("Marlin","Light Blue");
		COLOR_MAP.put("Surf","Light Blue");
		COLOR_MAP.put("Ivory","Medium White");
		COLOR_MAP.put("Mocha Black","Medium Black");
		COLOR_MAP.put("Oat","Light Brown");
		COLOR_MAP.put("Black w/ Gray Border","Medium Black");
		COLOR_MAP.put("Cool Gray","Medium Gray");
		COLOR_MAP.put("Heather Light Blue","Light Blue");
		COLOR_MAP.put("Stone Blue","Medium Blue");
		COLOR_MAP.put("Old Moss Heather","Medium Brown");
		COLOR_MAP.put("Starlight","Dark Blue");
		COLOR_MAP.put("Charcoal Gray","Medium Gray");
		COLOR_MAP.put("Dusty Rose","Medium Pink");
		COLOR_MAP.put("Iris Purple","Medium Purple");
		COLOR_MAP.put("Hot Coral","Medium Pink");
		COLOR_MAP.put("Pink Rush Heather","Medium Pink");
		COLOR_MAP.put("Orange Ice","Medium Orange");
		COLOR_MAP.put("Ice Blue","Light Blue");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Seafoam","Medium Green");
		COLOR_MAP.put("Poppy Red","Medium Red");
		COLOR_MAP.put("Orchid","Medium Purple");
		COLOR_MAP.put("Glacier Gray","Medium Gray");
		COLOR_MAP.put("Pink Dogwood","Medium Pink");
		COLOR_MAP.put("Periscope","Medium Gray");
		COLOR_MAP.put("Virtual Pink","Medium Pink");
		COLOR_MAP.put("TradeWinds","Other");
		COLOR_MAP.put("Rich Green","Medium Green");
		COLOR_MAP.put("Clear Gray","Clear Gray");
		COLOR_MAP.put("Joy Blue","Medium Blue");
		COLOR_MAP.put("Collegiate Royal","Medium Blue");
		COLOR_MAP.put("Dark Navy","Dark Blue");
		COLOR_MAP.put("Peacoat Navy","Dark Blue");
		COLOR_MAP.put("Tango Red","Medium Red");
		COLOR_MAP.put("Limoges","Multi Color");
		COLOR_MAP.put("Monument","Multi Color");
		COLOR_MAP.put("Caviar Heather","Other");
		COLOR_MAP.put("Dynasty Green Heather","Medium Green");
		COLOR_MAP.put("Limoges Heather","Other");
		COLOR_MAP.put("stripe","Medium Black");
		COLOR_MAP.put("Blueprint Heather","Medium Blue");
		COLOR_MAP.put("Highrise Heather","Medium Gray");
		COLOR_MAP.put("Castlerock Heather","Medium Gray");
		COLOR_MAP.put("Tan","Medium Brown");
		COLOR_MAP.put("all over black cap toe","Medium Black");
		COLOR_MAP.put("all over tan cap toe","Medium Brown");
		COLOR_MAP.put("all over brown cap toe","Medium Brown");
		COLOR_MAP.put("white sport speed saddle","Medium White");
		COLOR_MAP.put("black sport speed saddle","Medium Black");
		COLOR_MAP.put("Tmag Equipment Blue Heather","Medium Blue");
		COLOR_MAP.put("Tmag Mineral Blue Heather","Medium Green");
		COLOR_MAP.put("Graphite Gray","Medium Gray");
		COLOR_MAP.put("Stadium Green","Medium Green");
		COLOR_MAP.put("Grey Heather","Medium Gray");
		COLOR_MAP.put("Dark Smoke Gray","Medium Gray");
		COLOR_MAP.put("Wild Orchid","Medium Purple");
		COLOR_MAP.put("Blushing Pink","Medium Pink");
		COLOR_MAP.put("Sunny Lime Heather","Medium Yellow");
		COLOR_MAP.put("Soft Blue","Light Blue");
		COLOR_MAP.put("Mint Burst Heather","Medium Green");
		COLOR_MAP.put("black bicycle toe saddle","Medium Black");
		COLOR_MAP.put("cloud sandal","Medium Gray");
		COLOR_MAP.put("blue sandal","Medium Blue");
		COLOR_MAP.put("grey mist enJoy","Medium Gray");
		COLOR_MAP.put("Lavender enJoy","Medium Purple");
		COLOR_MAP.put("Neutral","Medium Brown");
		COLOR_MAP.put("ANTHRACITE/COOL GREY","Medium Black");
		COLOR_MAP.put("WOLF PURE PLATINUM/DARK ","Medium Gray");
		COLOR_MAP.put("PHOTO BLUE/SUMMIT DEEP ROYAL","Medium Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/TEAM RED","Medium Red");
		COLOR_MAP.put("PURE PLATINUM/ANTHRACITE","Medium Gray");
		COLOR_MAP.put("MIDNIGHT NAVY/BRIGHT CRIMSON/DARK","Dark Blue");
		COLOR_MAP.put("OMEGA BLUE","Medium White");
		COLOR_MAP.put("WOLF BETA BLUE","Medium Gray");
		COLOR_MAP.put("COPA/DARK GREY","Medium Black");
		COLOR_MAP.put("COOL MTLC COOL GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/COOL ANTHRACITE/","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/MTLC COOL GREY","Medium White");
		COLOR_MAP.put("UNIVERSITY RED/WOLF METALLIC","Medium White");
		COLOR_MAP.put("WOLF RACER BLUE","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/COOL VIVID","Medium Gray");
		COLOR_MAP.put("COOL METALLIC SILVER","Medium Black");
		COLOR_MAP.put("PURE PLATINUM","Medium White");
		COLOR_MAP.put("OBSIDIAN/BRIGHT CRIMSON","Medium White");
		COLOR_MAP.put("PURE PLATINUM/PHOTO BLUE","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/COOL RAGE GREEN","Medium Gray");
		COLOR_MAP.put("WOLF ANTHRACITE","Medium Gray");
		COLOR_MAP.put("GUM YELLOW/MIDNIGHT NAVY","Medium White");
		COLOR_MAP.put("LIGHT BONE/DUST/UNIVERSITY RED","Medium Brown");
		COLOR_MAP.put("PURE PLATINUM/SAIL/ACTION RED","Medium Gray");
		COLOR_MAP.put("BRIGHT CRIMSON/METALLIC SILVER","Medium White");
		COLOR_MAP.put("MTLC COOL GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON/","Medium White");
		COLOR_MAP.put("DEEP ROYAL BLUE/MIDNIGHT NAVY/BRIGHT","Bright Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/UNIVERSITY RED/","Medium White");
		COLOR_MAP.put("VIVID ORANGE/HYPER PINK","Medium White");
		COLOR_MAP.put("BRIGHT CRIMSON/HYPER ORANGE/MIDNIGHT","Medium Red");
		COLOR_MAP.put("MIDNIGHT NAVY/CHALK BLUE/BRIGHT","Dark Blue");
		COLOR_MAP.put("COSMIC PURPLE/VIVID ORANGE","Medium Purple");
		COLOR_MAP.put("WOLF GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON/MIDNIGHT","Medium Gray");
		COLOR_MAP.put("COSMIC PURPLE/ANTHRACITE","Medium White");
		COLOR_MAP.put("COOL ANTHRACITE","Medium White");
		COLOR_MAP.put("BRIGHT CRIMSON/FIERCE PURPLE/","Medium White");
		COLOR_MAP.put("PURE PLATINUM/COSMIC PURPLE/DIGITAL PINK/","Medium Gray");
		COLOR_MAP.put("DARK MTLC DARK GREY","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/DARK COOL","Medium Gray");
		COLOR_MAP.put("PURE PLATINUM/BRIGHT CRIMSON","Medium Gray");
		COLOR_MAP.put("CHALK BLUE/MIDNIGHT NAVY","Medium Blue");
		COLOR_MAP.put("HYPER TURQ","Medium Black");
		COLOR_MAP.put("PURE PLATINUM/HYPER PINK","Medium White");
		COLOR_MAP.put("DEEP ROYAL BLUE/BRIGHT CRIMSON/SAIL","Bright Blue");
		COLOR_MAP.put("ANTHRACITE/VOLTAGE GREEN","Medium Gray");
		COLOR_MAP.put("PHOTO BLUE/PHOTO BLUE","Medium White");
		COLOR_MAP.put("VOLTAGE GREEN","Medium Green");
		COLOR_MAP.put("HYPER COBALT/WOLF WOLF GREY","Medium Blue");
		COLOR_MAP.put("HYPER COBALT/WOLF GREY","Medium Blue");
		COLOR_MAP.put("BLUE OCEAN FOG","Medium Blue");
		COLOR_MAP.put("BRIGHT CRIMSON/UNIVERSITY RED","Medium Red");
		COLOR_MAP.put("MIDNIGHT NAVY/HYPER COBALT","Dark Blue");
		COLOR_MAP.put("TARP GREEN/SQUADRON BLUE","Medium White");
		COLOR_MAP.put("STADIUM GREY","Medium White");
		COLOR_MAP.put("NIGHT STADIUM","Medium White");
		COLOR_MAP.put("MED BASE GREY","Medium Black");
		COLOR_MAP.put("DK GREY HEATHER/DARK BASE GREY","Medium Gray");
		COLOR_MAP.put("CLASSIC STONE/BAROQUE BROWN","Medium Brown");
		COLOR_MAP.put("IRON ORE","Medium White");
		COLOR_MAP.put("DARK CHINO HTR","Medium Gray");
		COLOR_MAP.put("BIRCH HEATHER/CHALK BLUE/MIDNIGHT NAVY","Medium Brown");
		COLOR_MAP.put("BIRCH HEATHER/CARBON HEATHER/OBSIDIAN","Medium Brown");
		COLOR_MAP.put("LT CRIMSON","Medium White");
		COLOR_MAP.put("VIOLET SHADE","Medium White");
		COLOR_MAP.put("TURF ORANGE","Medium White");
		COLOR_MAP.put("HYPER PINK/MEDIUM OLIVE","Medium Pink");
		COLOR_MAP.put("Camouflage","Multi Color");
		COLOR_MAP.put("Stars/Stripes","Dark Blue");
		COLOR_MAP.put("Full Custom - Navy","Dark Blue");
		COLOR_MAP.put("SILVER/GYM RED","Medium Gray");
		COLOR_MAP.put("DARK OBSIDIAN/SILVER/PHOTO BLUE","Medium Blue");
		COLOR_MAP.put("MEDIUM OLIVE/SILVER/BRIGHT CRIMSON","Medium Green");
		COLOR_MAP.put("Blue Azure","Medium Blue");
		COLOR_MAP.put("Titanium","Titanium Metal");
		COLOR_MAP.put("Emerald Green","Medium Green");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Folkstone Gray","Medium Gray");
		COLOR_MAP.put("Aurora","Medium Yellow");
		COLOR_MAP.put("Vivid Viola","Medium Purple");
		COLOR_MAP.put("Hawaiian Ocean","Light Blue");
		COLOR_MAP.put("Strong Blue","Bright Blue");
		COLOR_MAP.put("Puma Red","Medium Red");
		COLOR_MAP.put("Bright Green","Medium Green");
		COLOR_MAP.put("Maroon Heather","Dark Red");
		COLOR_MAP.put("Oatmeal Heather","Copper Metal");
		COLOR_MAP.put("footwear footwear core black","Medium White");
		COLOR_MAP.put("core core iron met","Medium Black");
		COLOR_MAP.put("core dark silver metallic/red","Medium Black");
		COLOR_MAP.put("footwear silver metallic/core black","Medium White");
		COLOR_MAP.put("footwear mineral blue/shock blue","Medium White");
		COLOR_MAP.put("footwear dark silver metallic/solar yellow","Medium White");
		COLOR_MAP.put("dark silver metallic","Medium White");
		COLOR_MAP.put("iron/running black","Medium Gray");
		COLOR_MAP.put("onix/iron met/solar yellow","Medium Gray");
		COLOR_MAP.put("core core ftwr white","Medium Black");
		COLOR_MAP.put("ht grey heather solid light grey heather solid foo","Medium Gray");
		COLOR_MAP.put("footwear footwear gum","Medium White");
		COLOR_MAP.put("onix/light onix/footwear whtie","Medium Gray");
		COLOR_MAP.put("core core footwear white","Medium Black");
		COLOR_MAP.put("brown/footwear equipment green","Medium Brown");
		COLOR_MAP.put("footwear silver metallic/baja blue","Medium White");
		COLOR_MAP.put("core dark grey heater solid sunset coral","Medium Gray");
		COLOR_MAP.put("footwear matte silver/wild orchid","Medium White");
		COLOR_MAP.put("baja blue/shock red/baja blue","Medium Blue");
		COLOR_MAP.put("mint burst/lavender mist/silver met","Medium Green");
		COLOR_MAP.put("footwear light onix/silver met","Medium White");
		COLOR_MAP.put("Project X LZ Pro","Other");
		COLOR_MAP.put("Project X SD","Other");
		COLOR_MAP.put("silver metallic/flash red","Medium White");
		COLOR_MAP.put("clear onix/running solar red","Clear");
		COLOR_MAP.put("footwear core bold red","Medium White");
		COLOR_MAP.put("footwear matte silver/raspberry rose","Clear");
		COLOR_MAP.put("monk's robe-team gold","Dark Yellow");
		COLOR_MAP.put("drizzle","Medium White");
		COLOR_MAP.put("chipmunk-peacoat","Medium Brown");
		COLOR_MAP.put("turbulence-high risk red","Medium White");
		COLOR_MAP.put("Black Pearl","Medium Black");
		COLOR_MAP.put("Pine","Silver Metal");
		COLOR_MAP.put("pink/ribbon","Medium Pink");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("khaki/green","Medium Brown");
		COLOR_MAP.put("navy/red","Dark Blue");
		COLOR_MAP.put("charcoal/red","Medium Gray");
		COLOR_MAP.put("Royal Blue/charcoal","Bright Blue");
		COLOR_MAP.put("Gray/Aqua","Medium Gray");
		COLOR_MAP.put("Black Polka Dot","Medium Black");
		COLOR_MAP.put("Shaft - Project X LZ","Other");
		COLOR_MAP.put("tradewinds-green gecko","Medium Green");
		COLOR_MAP.put("quicksilver-cayenne","Medium Gray");
		COLOR_MAP.put("turbulence","Medium Black");
		COLOR_MAP.put("white swan","Medium White");
		COLOR_MAP.put("bison brown","Medium Brown");
		COLOR_MAP.put("limestone gray","Medium White");
		COLOR_MAP.put("cloisonne","Medium Black");
		COLOR_MAP.put("spicy orange","Bright Orange");
		COLOR_MAP.put("gray violet","Light Purple");
		COLOR_MAP.put("puma silver","Light Gray");
		COLOR_MAP.put("high-rise-fluo peach","Medium Orange");
		COLOR_MAP.put("cactus flower-orchid bloom purple","Medium White");
		COLOR_MAP.put("Optic Pink","Medium Pink");
		COLOR_MAP.put("Optic Yellow","Medium Yellow");
		COLOR_MAP.put("Shaft - Project X LZ Pro","Other");
		COLOR_MAP.put("","");

	}
	public static String getColorGroup(String colorName){
		return COLOR_MAP.get(colorName);
	}
}
