package parser.FITSAccessories;

import java.util.HashMap;
import java.util.Map;

public class FITSColorMapping {
public static Map<String, String> COLOR_MAP =new HashMap<String, String>();
	
	static{
		COLOR_MAP.put("Washed Black","Medium Black");
		COLOR_MAP.put("Blue Black","Dark Black");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Azure Blue","Medium Blue");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Heather Gray","Medium Gray");
		COLOR_MAP.put("Khaki","Medium Brown");
		COLOR_MAP.put("Stone","Light Brown");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Frosted","Clear");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Olive","Medium Green");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Translucent","Clear");
		COLOR_MAP.put("Metallic Silver","Silver Metal");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Black-Gray","Pewter Metal");
		COLOR_MAP.put("Black-Black","Multi Color");
		COLOR_MAP.put("Navy-Black","Multi Color");
		COLOR_MAP.put("Custom Colors","Assorted");
		COLOR_MAP.put("Lime","Bright Green");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Grey","Medium Gray");
		COLOR_MAP.put("Camouflage","Multi Color");
		COLOR_MAP.put("Blaze Orange","Bright Orange");
		COLOR_MAP.put("Black-Medium Gray-Gray","Multi Color");
		COLOR_MAP.put("Navy-Steel Blue-Gray","Multi Color");
		COLOR_MAP.put("Black-Red-White","Multi Color");
		COLOR_MAP.put("Purple-Black","Medium Purple");
		COLOR_MAP.put("Charcoal-Black","Multi Color");
		COLOR_MAP.put("Black-Charcoal-Gray","Multi Color");
		COLOR_MAP.put("Black-Royal-Gray","Multi Color");
		COLOR_MAP.put("Black-Gray-Lime","Medium Black");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Tan","Light Brown");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("Red-Black","Multi Color");
		COLOR_MAP.put("Red-White","Multi Color");
		COLOR_MAP.put("Black-White","Multi Color");
		COLOR_MAP.put("Black-Red","Multi Color");
		COLOR_MAP.put("Mustard-Navy","Silver Metal");
		COLOR_MAP.put("Navy-White","Multi Color");
		COLOR_MAP.put("Navy-Red","Multi Color");
		COLOR_MAP.put("Orange-Navy","Multi Color");
		COLOR_MAP.put("Stone-Black","Multi Color");
		COLOR_MAP.put("Stone-Navy","Multi Color");
		COLOR_MAP.put("Navy-Stone","Multi Color");
		COLOR_MAP.put("Black-Baby Blue","Multi Color");
		COLOR_MAP.put("Black-Stone","Multi Color");
		COLOR_MAP.put("Gun Metal-Stone","Silver Metal");
		COLOR_MAP.put("Gun Metal-Navy","Dark Blue");
		COLOR_MAP.put("Stone-Red","Multi Color");
		COLOR_MAP.put("Stone-Gunmetal","Multi Color");
		COLOR_MAP.put("Mustard","Medium Yellow");
		COLOR_MAP.put("Kelly Green","Medium Green");
		COLOR_MAP.put("Fuschia","Dark Pink");
		COLOR_MAP.put("Mustard-Black","Multi Color");
		COLOR_MAP.put("Royal-Stone","Multi Color");
		COLOR_MAP.put("Royal-White","Multi Color");
		COLOR_MAP.put("Navy-Orange","Multi Color");
		COLOR_MAP.put("White-Black","Multi Color");
		COLOR_MAP.put("White-Navy","Multi Color");
		COLOR_MAP.put("Black-Navy-White","Multi Color");
		COLOR_MAP.put("Black-Red-Charcoal","Multi Color");
		COLOR_MAP.put("Medium Gray-Gray","Medium Gray");
		COLOR_MAP.put("Natural","Light Brown");
		COLOR_MAP.put("Lilac","Light Purple");
		COLOR_MAP.put("Baby Blue","Light Blue");
		COLOR_MAP.put("Burgandy","Dark Red");
		COLOR_MAP.put("Light Olive","Light Green");
		COLOR_MAP.put("Vintage Red","Medium Red");
		COLOR_MAP.put("Gun Metal","Medium Gray");
		COLOR_MAP.put("Black-Royal","Multi Color");
		COLOR_MAP.put("Navy-Baby Blue","Multi Color");
		COLOR_MAP.put("Navy-Gray","Multi Color");
		COLOR_MAP.put("Beige","Light Brown");
		COLOR_MAP.put("Black-Fuschia","Medium Black");
		COLOR_MAP.put("Royal-Black","Multi Color");
		COLOR_MAP.put("Black-Purple","Multi Color");
		COLOR_MAP.put("Brown-Brown","Multi Color");
		COLOR_MAP.put("Charcoal-Purple","Multi Color");
		COLOR_MAP.put("Lime-Beige","Multi Color");
		COLOR_MAP.put("Black-Charcoal-White","Multi Color");
		COLOR_MAP.put("Gray-Black","Multi Color");
		COLOR_MAP.put("Royal-Gray","Multi Color");
		COLOR_MAP.put("Black-Charcoal Gray","Multi Color");
		COLOR_MAP.put("Royal-Light Gray","Multi Color");
		COLOR_MAP.put("Black-Fuchsia","Multi Color");
		COLOR_MAP.put("Charcoal-Aqua","Multi Color");
		COLOR_MAP.put("Charcoal-Red","Multi Color");
		COLOR_MAP.put("Purple-Fuschia","Medium Purple");
		COLOR_MAP.put("Black-Aqua","Multi Color");
		COLOR_MAP.put("Charcoal-Pink","Multi Color");
		COLOR_MAP.put("Navy-Yellow","Multi Color");
		COLOR_MAP.put("Black-Charcoal","Multi Color");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Navy-Charcoal","Multi Color");
		COLOR_MAP.put("Black-Yellow","Multi Color");
		COLOR_MAP.put("Camo/Khaki","Camouflage Brown");
		COLOR_MAP.put("Camo/Green","Camouflage Green");
	}
	public static String getColorGroup(String colorName){
		//return COLOR_MAP.get(colorName.toUpperCase());
		String group = COLOR_MAP.get(colorName);
		return group == null?"Other":group;
	}
}
