package parser.AccessLine;

import java.util.Map;
import java.util.TreeMap;

public class AccesslineLookupData {

	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
	
	static{
		
		
		COLOR_MAP.put("Name","Color Group");
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Clear Black","Clear Black");
		COLOR_MAP.put("Metallic Black","Metallic Black");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Translucent Red","Clear Red");
		COLOR_MAP.put("Translucent Green","Clear Green");
		COLOR_MAP.put("Translucent Blue","Clear Blue");
		COLOR_MAP.put("Translucent Clear","Clear");
		COLOR_MAP.put("Translucent Purple","Clear Purple");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Metallic Green","Metallic Green");
		COLOR_MAP.put("Clear Green","Clear Green");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Electric Violet","Bright Purple");
		COLOR_MAP.put("Blue","Medium Blue");
		COLOR_MAP.put("Clear Blue","Clear Blue");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Metallic Blue","Metallic Blue");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Maroon","Dark Red");
		COLOR_MAP.put("Pink","Medium Pink");
		COLOR_MAP.put("Clear Pink","Clear Pink");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Dark Red","Dark Red");
		COLOR_MAP.put("Clear Red","Clear Red");
		COLOR_MAP.put("Metallic Red","Metallic Red");
		COLOR_MAP.put("Clear","Clear");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Translucent Light Blue","Clear Blue");
		COLOR_MAP.put("Translucent  Green","Clear Green");
		COLOR_MAP.put("Translucent Orange","Clear Orange");
		COLOR_MAP.put("Translucent Pink","Clear Pink");
		COLOR_MAP.put("Translucent Yellow","Clear Yellow");
		COLOR_MAP.put("Dark Green","Dark Green");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Ivory","Medium White");
		COLOR_MAP.put("Light Gray","Light Gray");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Neon Orange","Bright Orange");
		COLOR_MAP.put("Neon Yellow","Bright Yellow");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Sun Yellow Close to PMS 121C","Medium Yellow");
		COLOR_MAP.put("Pencil Yellow Close to PMS 143C","Dark Yellow");
		COLOR_MAP.put("Medium Green Close to PMS 349","Medium Green");
		COLOR_MAP.put("Light Green Close to PMS 360C","Medium Green");
		COLOR_MAP.put("Dark Green Close to PMS 3308 C","Medium Green");
		COLOR_MAP.put("Light Blue Close to 3015C","Medium Blue");
		COLOR_MAP.put("Medium Blue Close to 280C","Bright Blue");
		COLOR_MAP.put("Dark Blue Close to PMS 2768C","Dark Blue");
		COLOR_MAP.put("Teal Close to PMS 3282C","Medium Green");
		COLOR_MAP.put("Orange Close to 1585C","Medium Orange");
		COLOR_MAP.put("Red Close to 187C","Dark Yellow");
		COLOR_MAP.put("Purple Close to PMS 519","Medium Purple");
		COLOR_MAP.put("Burgundy Close to PMS 7644","Dark Red");
		COLOR_MAP.put("Silver Close PMS 877C","Medium Gray");
		COLOR_MAP.put("Pewter","Pewter Metal");
		COLOR_MAP.put("Multi color","Multi Color");
		COLOR_MAP.put("Cream Close to PMS 7507 C","Brass Metal");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Clear Purple","Clear Purple");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Amber","Medium Yellow");
		COLOR_MAP.put("Smoke","Medium Gray");
		COLOR_MAP.put("Translucent  Gold","Clear Yellow");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Solid Blue","Medium Blue");
		COLOR_MAP.put("Translucent Smoke","Clear Gray");
		COLOR_MAP.put("Magenta","Bright Pink");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Fuchsia","Light Purple");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Translucent Amber","Clear Yellow");
		COLOR_MAP.put("Recycled","Medium Brown");
		COLOR_MAP.put("Fucsia","Dark Pink");
		COLOR_MAP.put("Translucent Lavender","Clear Purple");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Tanslucent Dark Blue","Dark Blue");
		COLOR_MAP.put("Tanslucent Light Blue","Light Blue");
		COLOR_MAP.put("Tanslucent  Red","Clear Red");
		COLOR_MAP.put("Tanslucent Green","Clear Green");
		COLOR_MAP.put("Tanslucent Orange","Clear Orange");
		COLOR_MAP.put("Tanslucent Purple","Clear Purple");
		COLOR_MAP.put("Pastel Pink","Light Pink");
		COLOR_MAP.put("Pastel Green","Light Green");
		COLOR_MAP.put("Pastel Peach","Light Orange");
		COLOR_MAP.put("Pastel Gray","Light Gray");
		COLOR_MAP.put("Pastel Blue","Light Blue");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Metallic Silver","Silver Metal");
		COLOR_MAP.put("Chrome","Chrome Metal");
		COLOR_MAP.put("Translucent White","Medium White");
		COLOR_MAP.put("Teal","Light Green");
		COLOR_MAP.put("Tanslucent Teal","Clear Green");
		COLOR_MAP.put("Lime","Light Green");
		COLOR_MAP.put("Royal Blue","Bright Blue");
		COLOR_MAP.put("Frosty Blue","Medium Blue");
		COLOR_MAP.put("Frosty Green","Medium Green");
		COLOR_MAP.put("Frosty Red","Medium Red");
		COLOR_MAP.put("Frosty Orange","Medium Orange");
		COLOR_MAP.put("Frosty Yellow","Medium Yellow");
		COLOR_MAP.put("Translucent Black","Clear Black");
		COLOR_MAP.put("Aqua","Light Blue");
		COLOR_MAP.put("Copper","Copper Metal");
		COLOR_MAP.put("Rose","Medium Red");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Gun Metal","Aluminum Metal");
		COLOR_MAP.put("Pastel Purple","Light Purple");
		COLOR_MAP.put("Pastel Silver","Light Gray");
		COLOR_MAP.put("Pastel Orange","Light Orange");
		COLOR_MAP.put("Lime Green","Light Green");
		COLOR_MAP.put("Gunmetal","Metallic Gray");
		COLOR_MAP.put("Assorted","Assorted");
		COLOR_MAP.put("Neon Blue","Medium Blue");
		COLOR_MAP.put("Taupe","Medium White");
		COLOR_MAP.put("White with Black Trim","Medium White");
		COLOR_MAP.put("White with Blue Trim","Medium White");
		COLOR_MAP.put("White with Red Trim","Medium White");
		COLOR_MAP.put("White with Black","Medium White");
		COLOR_MAP.put("White with White","Medium White");
		COLOR_MAP.put("White with Red","Medium White");
		COLOR_MAP.put("White with Blue","Medium White");
		COLOR_MAP.put("solid red","Medium Red");
		COLOR_MAP.put("green khaki","Other");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("forest green","Dark Green");
		COLOR_MAP.put("natural","Other");
		COLOR_MAP.put("all natural","Other");
		COLOR_MAP.put("Colored Black Barrel-Black Grip","Medium Black");
		COLOR_MAP.put("Camel","Medium Brown");
		COLOR_MAP.put("Royal","Bright Blue");
		COLOR_MAP.put("KH","Other");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Fuscia","Medium Pink");
		COLOR_MAP.put("Translucent Blue 2747","Medium Blue");
		COLOR_MAP.put("Translucent Green 7484","Medium Green");
		COLOR_MAP.put("Translucent Orange 165","Medium Orange");
		COLOR_MAP.put("Translucent Red 201","Medium Red");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Green 2245","Medium Green");
		COLOR_MAP.put("Light Blue 2144","Light Blue");
		COLOR_MAP.put("Lime 2421","Light Green");
		COLOR_MAP.put("Orange 165","Medium Orange");
		COLOR_MAP.put("Chartreuse 368","Medium Green");
		COLOR_MAP.put("Green 356","Medium Green");
		COLOR_MAP.put("Orange 1645","Medium Orange");
		COLOR_MAP.put("Purple 268","Medium Purple");
		COLOR_MAP.put("Red 201","Medium Red");
		COLOR_MAP.put("Blue 633","Medium Blue");
		COLOR_MAP.put("Rose 2042","Medium Red");
		COLOR_MAP.put("Blue 2736","Medium Blue");
		COLOR_MAP.put("Purple 267","Medium Purple");
		COLOR_MAP.put("Red 187","Medium Red");
		COLOR_MAP.put("Blue 7687","Medium Blue");
		COLOR_MAP.put("Green 342","Medium Green");
		COLOR_MAP.put("Blue 2747","Medium Blue");
		COLOR_MAP.put("Green 7727","Medium Green");
		COLOR_MAP.put("Orange 171","Medium Orange");
		COLOR_MAP.put("Chartreuse 375","Medium Green");
		COLOR_MAP.put("Pink 234","Medium Pink");
		COLOR_MAP.put("Purple 2617","Medium Purple");	
		
	}

	
}
