package parser.riverend;

import java.util.Map;
import java.util.TreeMap;

public class MappingClass {
	
	public static Map<String, String> COLOR_MAP =new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);//new HashMap<String, String>();
	static {
		COLOR_MAP.put("Black","Medium Black");
		COLOR_MAP.put("Brown","Medium Brown");
		COLOR_MAP.put("Forest Green","Medium Green");
		COLOR_MAP.put("Navy","Dark Blue");
		COLOR_MAP.put("Gray Heather","Medium Gray");
		COLOR_MAP.put("Cobalt","Medium Blue");
		COLOR_MAP.put("Dark Berry","Medium Red");
		COLOR_MAP.put("True Navy","Dark Blue");
		COLOR_MAP.put("Pewter Gray","Other");
		COLOR_MAP.put("Blueprint","Medium Blue");
		COLOR_MAP.put("Graphite","Medium Gray");
		COLOR_MAP.put("Seasalt White","Medium White");
		COLOR_MAP.put("Purple Dahlia","Medium Purple");
		COLOR_MAP.put("Rocket Red","Medium Red");
		COLOR_MAP.put("Graphite Gray","Medium Gray");
		COLOR_MAP.put("Azul Blue","Medium Blue");
		COLOR_MAP.put("Gray","Medium Gray");
		COLOR_MAP.put("Charcoal Gray","Medium Gray");
		COLOR_MAP.put("Columbia Navy-Gold","Dark Blue");
		COLOR_MAP.put("Red Element-Black","Dark Red");
		COLOR_MAP.put("Rouge","Medium Red");
		COLOR_MAP.put("White","Medium White");
		COLOR_MAP.put("Charcoal","Medium Gray");
		COLOR_MAP.put("Columbia Navy","Dark Blue");
		COLOR_MAP.put("Winter White","Medium White");
		COLOR_MAP.put("Black-Charcoal","Multi Color");
		COLOR_MAP.put("Columbia Navy-Charcoal","Multi Color");
		COLOR_MAP.put("Tusk-Charcoal","Multi Color");
		COLOR_MAP.put("Azul","Medium Blue");
		COLOR_MAP.put("Fossil","Light Brown");
		COLOR_MAP.put("White Cap","Medium White");
		COLOR_MAP.put("Foxglove","Medium Pink");
		COLOR_MAP.put("Vivid Blue","Medium Blue");
		COLOR_MAP.put("Gulf Stream","Light Green");
		COLOR_MAP.put("Sail","Medium Blue");
		COLOR_MAP.put("Sunlit","Medium Yellow");
		COLOR_MAP.put("Sunset Red","Medium Red");
		COLOR_MAP.put("Lemon Whip","Medium Yellow");
		COLOR_MAP.put("Sage","Medium Green");
		COLOR_MAP.put("Bright Rose","Medium Pink");
		COLOR_MAP.put("Clear Blue","Clear Blue");
		COLOR_MAP.put("Bright Peach","Medium Orange");
		COLOR_MAP.put("Key West","Other");
		COLOR_MAP.put("Medium White","Medium White");
		COLOR_MAP.put("Azul-Black","Medium Blue");
		COLOR_MAP.put("Red-Black","Multi Color");
		COLOR_MAP.put("Mojito","Medium Green");
		COLOR_MAP.put("Summer Sky Blue","Bright Blue");
		COLOR_MAP.put("Deep Indigo","Dark Blue");
		COLOR_MAP.put("Classic Red","Medium Red");
		COLOR_MAP.put("Orange Crush","Medium Orange");
		COLOR_MAP.put("Heather Gray","Light Gray");
		COLOR_MAP.put("Red","Medium Red");
		COLOR_MAP.put("Royal Blue","Medium Blue");
		COLOR_MAP.put("Safety Green","Medium Green");
		COLOR_MAP.put("Safety Orange","Bright Orange");
		COLOR_MAP.put("Ash","Light Green");
		COLOR_MAP.put("Cactus Green","Light Green");
		COLOR_MAP.put("Caribbean Blue","Medium Blue");
		COLOR_MAP.put("Carolina Blue","Light Blue");
		COLOR_MAP.put("Charity Pink","Light Pink");
		COLOR_MAP.put("Chocolate","Medium Brown");
		COLOR_MAP.put("City Green","Medium Green");
		COLOR_MAP.put("Cobblestone","Light Brown");
		COLOR_MAP.put("Gold","Gold Metal");
		COLOR_MAP.put("Green Apple","Medium Green");
		COLOR_MAP.put("Heather Dark Gray","Dark Gray");
		COLOR_MAP.put("Hot Pink","Bright Pink");
		COLOR_MAP.put("Independence Red","Medium Red");
		COLOR_MAP.put("Kelly Green","Bright Green");
		COLOR_MAP.put("Key Lime","Medium Green");
		COLOR_MAP.put("Lake","Other");
		COLOR_MAP.put("Lemon Zest","Bright Yellow");
		COLOR_MAP.put("Blue","Light Blue");
		COLOR_MAP.put("Moss","Medium Green");
		COLOR_MAP.put("Neon Blue","Assorted");
		COLOR_MAP.put("Neon Green","Bright Green");
		COLOR_MAP.put("Neon Pink","Bright Pink");
		COLOR_MAP.put("Orange","Medium Orange");
		COLOR_MAP.put("Pool Blue","Medium Blue");
		COLOR_MAP.put("Purple","Medium Purple");
		COLOR_MAP.put("Storm Gray","Other");
		COLOR_MAP.put("Black-Sport Gray","Multi Color");
		COLOR_MAP.put("Black-Red","Multi Color");
		COLOR_MAP.put("Navy-Sport Gray","Multi Color");
		COLOR_MAP.put("Navy-Gold","Multi Color");
		COLOR_MAP.put("Red-Sport Gray","Medium Red");
		COLOR_MAP.put("Royal-Sport Gray","Multi Color");
		COLOR_MAP.put("Sport Gray-Black","Multi Color");
		COLOR_MAP.put("Sport Gray","Other");
		COLOR_MAP.put("Royal","Medium Blue");
		COLOR_MAP.put("Blackberry","Medium Black");
		COLOR_MAP.put("Meadow","Medium Green");
		COLOR_MAP.put("Russet","Medium Brown");
		COLOR_MAP.put("Tweed","Light Brown");
		COLOR_MAP.put("Cherry Red","Medium Red");
		COLOR_MAP.put("RS Sport Gray","Other");
		COLOR_MAP.put("Azalea","Medium Pink");
		COLOR_MAP.put("Black-Steel","Multi Color");
		COLOR_MAP.put("Navy-Steel","Multi Color");
		COLOR_MAP.put("Sapphire","Medium Blue,Dark Blue");
		COLOR_MAP.put("Titanium","Medium Gray");
		COLOR_MAP.put("Ocean Blue","Medium Blue");
		COLOR_MAP.put("Cactus","Medium Green");
		COLOR_MAP.put("Baltic","Medium Blue");
		COLOR_MAP.put("French Blue","Medium Blue");
		COLOR_MAP.put("Hunter Green","Dark Green");
		COLOR_MAP.put("Khaki","Medium Brown");
		COLOR_MAP.put("Lemon","Medium Yellow");
		COLOR_MAP.put("Lawn","Light Green");
		COLOR_MAP.put("Wine","Medium Red");
		COLOR_MAP.put("Lagoon Blue","Medium Blue");
		COLOR_MAP.put("Solstice","Medium White");
		COLOR_MAP.put("Brick Red","Medium Red");
		COLOR_MAP.put("Navy-Putty","Multi Color");
		COLOR_MAP.put("Putty-Black","Multi Color");
		COLOR_MAP.put("Red-Navy","Multi Color");
		COLOR_MAP.put("Black-Putty","Multi Color");
		COLOR_MAP.put("Plum","Medium Red");
		COLOR_MAP.put("Palm","Medium Green");
		COLOR_MAP.put("Navy Blue","Dark Blue");
		COLOR_MAP.put("Pine","Medium Green");
		COLOR_MAP.put("Stone","Medium White");
		COLOR_MAP.put("Green","Medium Green");
		COLOR_MAP.put("Navy-Denim","Multi Color");
		COLOR_MAP.put("Rope","Light Brown");
		COLOR_MAP.put("Steel","Silver Metal");
		COLOR_MAP.put("Dark Navy","Dark Blue");
		COLOR_MAP.put("Blue Stripe","Medium Blue");
		COLOR_MAP.put("Gecko Green","Medium Green");
		COLOR_MAP.put("White-Dark Navy","Multi Color");
		COLOR_MAP.put("Olympic Blue","Medium Blue");
		COLOR_MAP.put("Light Blue","Light Blue");
		COLOR_MAP.put("Birch-Black","Multi Color");
		COLOR_MAP.put("Midnight-Birch","Multi Color");
		COLOR_MAP.put("Moss-Midnight","Multi Color");
		COLOR_MAP.put("Bahama Blue-Midnight","Multi Color");
		COLOR_MAP.put("Deep Red-Birch","Multi Color");
		COLOR_MAP.put("Loden-Birch","Multi Color");
		COLOR_MAP.put("Black-Birch","Multi Color");
		COLOR_MAP.put("White-Black","Multi Color");
		COLOR_MAP.put("True Khaki-Black","Multi Color");
		COLOR_MAP.put("Dark Brown","Dark Brown");
		COLOR_MAP.put("Deep Blue","Medium Blue");
		COLOR_MAP.put("Classic Pink","Medium Pink");
		COLOR_MAP.put("Chili","Medium Red");
		COLOR_MAP.put("Dusk","Other");
		COLOR_MAP.put("Lavender","Light Purple");
		COLOR_MAP.put("Sky","Light Blue");
		COLOR_MAP.put("Ciel Blue","Light Blue");
		COLOR_MAP.put("Dark Chocolate","Medium Brown");
		COLOR_MAP.put("Military Green","Medium Green");
		COLOR_MAP.put("Scrub Green","Light Green");
		COLOR_MAP.put("Coffee","Medium Brown");
		COLOR_MAP.put("Electric Blue","Bright Blue");
		COLOR_MAP.put("Coal","Medium Black");
		COLOR_MAP.put("Canary Yellow","Medium Yellow");
		COLOR_MAP.put("Ash Gray","Light Gray");
		COLOR_MAP.put("Dark Heather","Dark Gray");
		COLOR_MAP.put("Pink","Light Pink");
		COLOR_MAP.put("Maroon","Medium Red");
		COLOR_MAP.put("Birch","Light Gray");
		COLOR_MAP.put("Birch-Midnight","Multi Color");
		COLOR_MAP.put("Iron-Birch","Multi Color");
		COLOR_MAP.put("White-Midnight","Multi Color");
		COLOR_MAP.put("Regatta Blue","Medium Blue");
		COLOR_MAP.put("Irish Green","Medium Green");
		COLOR_MAP.put("Sand","Silver Metal");
		COLOR_MAP.put("Heliconia","Other");
		COLOR_MAP.put("Iris","Medium Purple");
		COLOR_MAP.put("Pistachio","Light Green");
		COLOR_MAP.put("Cardinal Red","Medium Red");
		COLOR_MAP.put("Daisy","Medium Yellow");
		COLOR_MAP.put("Indigo Blue","Medium Blue");
		COLOR_MAP.put("Jade Dome","Medium Green");
		COLOR_MAP.put("Kiwi","Medium Green");
		COLOR_MAP.put("Lime","Light Green");
		COLOR_MAP.put("Prairie Dust","Medium Brown");
		COLOR_MAP.put("Texas Orange","Medium Orange");
		COLOR_MAP.put("Natural","DARK WHITE");
		COLOR_MAP.put("Medium Purple","Medium Purple");
		COLOR_MAP.put("Garnet","Other");
		COLOR_MAP.put("Orchid","Light Purple");
		COLOR_MAP.put("Paprika","Other");
		COLOR_MAP.put("Tan","Light Brown");
		COLOR_MAP.put("Tennessee Orange","Medium Orange");
		COLOR_MAP.put("Light Charcoal","Light Gray");
		COLOR_MAP.put("Oxford Blue","Multi Color");
		COLOR_MAP.put("Athletic Heather","Medium Gray");
		COLOR_MAP.put("Goldenrod","Dark Yellow");
		COLOR_MAP.put("White-Bahama Blue","Multi Color");
		COLOR_MAP.put("White-Taffy","Multi Color");
		COLOR_MAP.put("Midnight","Silver Metal");
		COLOR_MAP.put("True Khaki","Light Brown");
		COLOR_MAP.put("Midnight-White","Multi Color");
		COLOR_MAP.put("Black-White","Multi Color");
		COLOR_MAP.put("Cobalt-White","Multi Color");
		COLOR_MAP.put("Metal","Other");
		COLOR_MAP.put("Camo-Advantage Max-4","Multi Color");
		COLOR_MAP.put("Bark","Medium Brown");
		COLOR_MAP.put("Jet","Medium Gray");
		COLOR_MAP.put("Denim","Medium Blue");
		COLOR_MAP.put("Medium Wash Denim","Medium Blue");
		COLOR_MAP.put("Mocha","Medium Brown");
		COLOR_MAP.put("River Blue","Medium Blue");
		COLOR_MAP.put("Frosted Pink","Medium Pink");
		COLOR_MAP.put("Sky Blue","Light Blue");
		COLOR_MAP.put("Baltic Blue","Medium Blue");
		COLOR_MAP.put("Pebble","Light Brown");
		COLOR_MAP.put("Aubergine","Medium Purple");
		COLOR_MAP.put("Berry","Medium Pink");
		COLOR_MAP.put("Brown Savana","Medium Brown");
		COLOR_MAP.put("Coral Silk","Medium Pink");
		COLOR_MAP.put("Gravel","Medium Gray");
		COLOR_MAP.put("Old Gold","Gold Metal");
		COLOR_MAP.put("Turf Green","Medium Green");
		COLOR_MAP.put("Violet","Medium Purple");
		COLOR_MAP.put("Yellow Haze","Medium Yellow");
		COLOR_MAP.put("Antique Cherry Red","Medium Red");
		COLOR_MAP.put("Antique Irish Green","Medium Green");
		COLOR_MAP.put("Antique Jade Dome","Medium Green");
		COLOR_MAP.put("Antique Orange","Medium Orange");
		COLOR_MAP.put("Antique Sapphire","Medium Blue");
		COLOR_MAP.put("Heather Military Green","Medium Green");
		COLOR_MAP.put("Heather Red","Medium Red");
		COLOR_MAP.put("Heather Sapphire","Multi Color");
		COLOR_MAP.put("Medium Black","Medium Black");
		COLOR_MAP.put("Raspberry","Medium Red");
		COLOR_MAP.put("Dark Navy-Iron","Multi Color");
		COLOR_MAP.put("Iron-Black","Multi Color");
		COLOR_MAP.put("Brick-Iron","Medium Black");
		COLOR_MAP.put("Black-Iron","Multi Color");
		COLOR_MAP.put("Jupiter","Medium Orange");
		COLOR_MAP.put("Commando","Dark Gray");
		COLOR_MAP.put("Haute Pink","Medium Pink");
		COLOR_MAP.put("Antique Heliconia","Medium Red");
		COLOR_MAP.put("Iron-Black-Gold Leaf","Multi Color");
		COLOR_MAP.put("Black-Iron-Reflex Blue","Multi Color");
		COLOR_MAP.put("Dark Navy-Iron-Tangelo","Multi Color");
		COLOR_MAP.put("Light Blue Pencil Stripe","Light Blue");
		COLOR_MAP.put("Medium Red","Medium Red");
		COLOR_MAP.put("Medium Blue","Medium Blue");
		COLOR_MAP.put("Dark Gray","Dark Gray");
		COLOR_MAP.put("Medium Green","Medium Green");
		COLOR_MAP.put("Multi Color","Multi Color");
		COLOR_MAP.put("Dark Blue","Dark Blue");
		COLOR_MAP.put("Light Green","Light Green");
		COLOR_MAP.put("Medium Brown","Medium Brown");
		COLOR_MAP.put("Medium Orange","Medium Orange");
		COLOR_MAP.put("Silver Metal","Silver Metal");
		COLOR_MAP.put("Slate","Light Gray,Medium Gray");
		COLOR_MAP.put("Pumice","Medium Gray");
		COLOR_MAP.put("Union Blue","Medium Blue");
		COLOR_MAP.put("Silverton","Medium Gray");
		COLOR_MAP.put("Crimson Red","Medium Red");
		COLOR_MAP.put("Peony","Other");
		COLOR_MAP.put("Snow","Medium White");
		COLOR_MAP.put("Olive","Medium Green");
		COLOR_MAP.put("Tobacco","Medium Brown");
		COLOR_MAP.put("Gipsy Blue","Medium Blue");
		COLOR_MAP.put("Chlorophyll Green","Medium Green");
		COLOR_MAP.put("Bordeaux","Dark Red");
		COLOR_MAP.put("Flamingo","Medium Pink");
		COLOR_MAP.put("Cloud","Medium Blue");
		COLOR_MAP.put("Stingray","Medium Gray");
		COLOR_MAP.put("Black/White","Medium Black");
		COLOR_MAP.put("Classic Red/Black","Medium Red");
		COLOR_MAP.put("Dark Navy/White","Dark Blue");
		COLOR_MAP.put("Pumice/Black","Medium White");
		COLOR_MAP.put("Stingray/Black","Medium Gray");
		COLOR_MAP.put("Chocolate Brown","Medium Brown");
		COLOR_MAP.put("Blaze Orange","Bright Orange");
		COLOR_MAP.put("Admiral Navy","Dark Blue");
		COLOR_MAP.put("Turf","Medium Green");
		COLOR_MAP.put("Iron","Medium Black");
		COLOR_MAP.put("Field Khaki","Light Brown");
		COLOR_MAP.put("Clay","Light Brown");
		COLOR_MAP.put("Saddle","Light Brown");
		COLOR_MAP.put("Realtree(AP)","Multi Color");
		COLOR_MAP.put("Gold Leaf","Dark Yellow");
		COLOR_MAP.put("True Turquoise","Medium Green");
		COLOR_MAP.put("Peri Blue","Medium Blue");
		COLOR_MAP.put("Orange Peel","Medium Orange");
		COLOR_MAP.put("Tennesse Orange","Medium Orange");
		COLOR_MAP.put("Tangerine","Medium Orange");
		COLOR_MAP.put("Camo - Realtree Xtra","Multi Color");
		COLOR_MAP.put("Black-Black","Multi Color");
		COLOR_MAP.put("Storm Blue-Black","Multi Color");
		COLOR_MAP.put("Vintage Brown","Medium Brown");
		COLOR_MAP.put("Citron","Light Yellow");
		COLOR_MAP.put("Charcoal Heather","Medium Gray");
		COLOR_MAP.put("Deep Red","Medium Red");
		COLOR_MAP.put("Charcoal-White","Multi Color");
		COLOR_MAP.put("Leaf-White","Multi Color");
		COLOR_MAP.put("Petal-White","Multi Color");
		COLOR_MAP.put("Classic Red-White","Multi Color");
		COLOR_MAP.put("Dark Navy-White","Multi Color");
		COLOR_MAP.put("Reflex Blue-White","Multi Color");
		COLOR_MAP.put("Bahama Blue","Medium Blue");
		COLOR_MAP.put("Natural-Black","Multi Color");
		COLOR_MAP.put("Natural-Red","Multi Color");
		COLOR_MAP.put("Natural-Navy","Multi Color");
		COLOR_MAP.put("Natural-Royal","Multi Color");
		COLOR_MAP.put("Pewter","Pewter Metal");
		COLOR_MAP.put("Navy-Ivory","Multi Color");
		COLOR_MAP.put("Ivory-Navy","Multi Color");
		COLOR_MAP.put("Royal-Black","Multi Color");
		COLOR_MAP.put("Grape","Medium Purple");
		COLOR_MAP.put("Submarine","Medium Yellow");
		COLOR_MAP.put("Wave","Medium Green");
		COLOR_MAP.put("Black-White-Regal Purple-Zinc","Multi Color");
		COLOR_MAP.put("White-Steel Gray-Black-Zinc","Multi Color");
		COLOR_MAP.put("Reflex Blue-White-Black-Zinc","Multi Color");
		COLOR_MAP.put("Teal","Medium Green");
		COLOR_MAP.put("French Blue Stripe","Medium Blue");
		COLOR_MAP.put("Camouflage","Multi Color");
		COLOR_MAP.put("Blaze","Bright Orange");
		COLOR_MAP.put("Burgundy","Dark Red");
		COLOR_MAP.put("Forest","Dark Green");
		COLOR_MAP.put("Steel Blue","Medium Blue");
		COLOR_MAP.put("Espresso","Medium Brown");
		COLOR_MAP.put("Teal Green","Medium Green");
		COLOR_MAP.put("Sangria","Other");
		COLOR_MAP.put("Deep Coral","Multi Color");
		COLOR_MAP.put("Eggplant","Medium Purple");
		COLOR_MAP.put("Santa Fe Blue","Medium Blue");
		COLOR_MAP.put("Charcoal Stripe","Medium Gray");
		COLOR_MAP.put("Blue Dusk","Medium Blue");
		COLOR_MAP.put("Chestnut","Medium Brown");
		COLOR_MAP.put("Galapagos Blue","Medium Blue");
		COLOR_MAP.put("Honey","Light Yellow");
		COLOR_MAP.put("Ice Gray","Light Gray");
		COLOR_MAP.put("Metro Blue","Medium Blue");
		COLOR_MAP.put("Prarie Dust","Light Brown");
		COLOR_MAP.put("Rusty Bronze","Medium Brown");
		COLOR_MAP.put("Serene Green","Medium Green");
		COLOR_MAP.put("Stone Blue","Medium Blue");
		COLOR_MAP.put("Vegas Gold","Gold Metal");
		COLOR_MAP.put("Antique Royal","Dark Blue");
		COLOR_MAP.put("Heather Cardinal","Medium Red");
		COLOR_MAP.put("Heather Indigo","Medium Blue");
		COLOR_MAP.put("Heather Navy","Medium Blue");
		COLOR_MAP.put("Safety Pink","Medium Pink");
		COLOR_MAP.put("Light Brown","Light Brown");
		COLOR_MAP.put("Lake Blue","Light Blue");
		COLOR_MAP.put("Dark Wash Denim","Medium Blue");
		COLOR_MAP.put("Classic Tan","Light Brown");
		COLOR_MAP.put("Dutch Blue","Light Blue");
		COLOR_MAP.put("Leaf","Medium Green");
		COLOR_MAP.put("Black-Bone","Multi Color");
		COLOR_MAP.put("Bright Red-Black","Multi Color");
		COLOR_MAP.put("French Blue-Black","Multi Color");
		COLOR_MAP.put("Navy-White","Multi Color");
		COLOR_MAP.put("Bright Red-White","Multi Color");
		COLOR_MAP.put("Baltic-White","Multi Color");
		COLOR_MAP.put("Lawn-White","Multi Color");
		COLOR_MAP.put("White-Navy","Multi Color");
		COLOR_MAP.put("Black-Stone","Multi Color");
		COLOR_MAP.put("Carolina Blue-White","Multi Color");
		COLOR_MAP.put("Sea Breeze","Light Blue");
		COLOR_MAP.put("Spring Green","Medium Green");
		COLOR_MAP.put("Onyx","Medium Black");
		COLOR_MAP.put("Periwinkle","Light Purple");
		COLOR_MAP.put("Blue Check","Medium Blue");
		COLOR_MAP.put("Silver","Silver Metal");
		COLOR_MAP.put("Waxy Canvas","Medium Brown");
		COLOR_MAP.put("Taupe","Light Brown");
		COLOR_MAP.put("Dark Khaki","Medium Brown");
		COLOR_MAP.put("Dark Olive","Medium Green");
		COLOR_MAP.put("Mud","Medium Brown");
		COLOR_MAP.put("Silver Gray Chine","Other");
		COLOR_MAP.put("Prussian Blue","Medium Blue");
		COLOR_MAP.put("Dark Oxford","Light Gray");
		COLOR_MAP.put("Classic Green","Medium Green");
		COLOR_MAP.put("Amber Gold","Gold Metal");
		COLOR_MAP.put("Loden","Medium Green");
		COLOR_MAP.put("Midnight-Natural","Multi Color");
		COLOR_MAP.put("Black-Natural","Multi Color");
		COLOR_MAP.put("Wine-Natural","Multi Color");
		COLOR_MAP.put("Classic Green-Natural","Multi Color");
		COLOR_MAP.put("Loden-Natural","Multi Color");
		COLOR_MAP.put("Beet","Medium Red");
		COLOR_MAP.put("Dark Compass","Medium Blue");
		COLOR_MAP.put("Quill","Medium Purple");
		COLOR_MAP.put("Mirage Blue","Medium Blue");
		COLOR_MAP.put("Mountain Gray","Other");
		COLOR_MAP.put("Khaki-Navy","Multi Color");
		COLOR_MAP.put("Navy-Stone","Multi Color");
		COLOR_MAP.put("Black-Ash","Medium Black");
		COLOR_MAP.put("True Navy-Ash","Multi Color");
		COLOR_MAP.put("Cranberry","Medium Red");
		COLOR_MAP.put("Nightshade","Medium Black");
		COLOR_MAP.put("Steel Gray","Medium Gray");
		COLOR_MAP.put("Estate Blue-Horizon Blue","Medium Blue");
		COLOR_MAP.put("Estate Blue","Medium Blue");
		COLOR_MAP.put("Sport Red","Medium Red");
		COLOR_MAP.put("Chili Pepper Red","Medium Red");
		COLOR_MAP.put("Midnight Blue","Medium Blue");
		COLOR_MAP.put("Citron Yellow","Medium Yellow");
		COLOR_MAP.put("Clemantis Blue","Medium Blue");
		COLOR_MAP.put("Pink Glo","Medium Pink");
		COLOR_MAP.put("Tech Blue","Medium Blue");
		COLOR_MAP.put("Tobacco Brown","Medium Brown");
		COLOR_MAP.put("Hyper Purple","Medium Purple");
		COLOR_MAP.put("Groovy Pink","Medium Pink");
		COLOR_MAP.put("Federal Blue","Medium Blue");
		COLOR_MAP.put("Field Khaki-Tobacco","Medium Brown");
		COLOR_MAP.put("Kiwi Green","Medium Green");
		COLOR_MAP.put("Blue-White","Bright Blue");
		COLOR_MAP.put("Realtree Camo","Multi Color");
		COLOR_MAP.put("Reflex Blue","Medium Blue");
		COLOR_MAP.put("Classic Brown","Medium Brown");
		COLOR_MAP.put("Custom","Assorted");
		COLOR_MAP.put("Smoke","Medium Gray");
		COLOR_MAP.put("Hunter","Dark Green");
		COLOR_MAP.put("Aztec Gold","Gold Metal");
		COLOR_MAP.put("Burnt Orange","Medium Orange");
		COLOR_MAP.put("Concord Purple","Medium Purple");
		COLOR_MAP.put("Evergreen","Medium Green");
		COLOR_MAP.put("Forged Iron","Other");
		COLOR_MAP.put("Mango","Light Orange");
		COLOR_MAP.put("Varsity Blue","Medium Blue");
		COLOR_MAP.put("Sage Green","Medium Green");
		COLOR_MAP.put("Collegiate Navy","Dark Blue");
		COLOR_MAP.put("Harbor Blue","Medium Blue");
		COLOR_MAP.put("Marine Blue","Medium Blue");
		COLOR_MAP.put("Mountain","Medium Blue");
		COLOR_MAP.put("Oatmeal Heather","Medium Yellow");
		COLOR_MAP.put("Platinum","Medium Gray");
		COLOR_MAP.put("Cinder","Medium Gray");
		COLOR_MAP.put("Bounty Blue","Light Blue");
		COLOR_MAP.put("Lilac","Light Purple");
		COLOR_MAP.put("Mint","Light Green");
		COLOR_MAP.put("White with Navy","Medium White");
		COLOR_MAP.put("Jade Lime","Medium Green");
		COLOR_MAP.put("Cool Gray","Medium Gray");
		COLOR_MAP.put("Ruby Red","Medium Red");
		COLOR_MAP.put("Carbon Heather","Medium Gray");
		COLOR_MAP.put("Punch","Medium Red");
		COLOR_MAP.put("Pink Lemonade","Medium Pink");
		COLOR_MAP.put("Wheat","Medium Brown");
		COLOR_MAP.put("Hardwoods Green","Medium Green");
		COLOR_MAP.put("Canyon","Other");
		COLOR_MAP.put("Indigo","Medium Blue");
		COLOR_MAP.put("Camo-Realtree Xtra","Multi Color");
		COLOR_MAP.put("Sail Red","Medium Red");
		COLOR_MAP.put("Ultramarine","Medium Blue");
		COLOR_MAP.put("Pink Mist","Medium Pink");
		COLOR_MAP.put("Papaya","Medium Orange");
		COLOR_MAP.put("Blue Grotto","Medium Blue");
		COLOR_MAP.put("Yellow","Medium Yellow");
		COLOR_MAP.put("Opaline Green","Medium Green");
		COLOR_MAP.put("Frost","Light Blue");
		COLOR_MAP.put("Cobalt-Ocean","Medium Blue");
		COLOR_MAP.put("Pure Orange","Medium Orange");
		COLOR_MAP.put("Bright Red Lumberjack","Medium Red");
		COLOR_MAP.put("Blue Macaw","Medium Blue");
		COLOR_MAP.put("Columbia Gray","Medium Gray");
		COLOR_MAP.put("Miami","Medium Blue");
		COLOR_MAP.put("Beacon Heather","Medium Gray");
		COLOR_MAP.put("Realtree(R) Xtra(TM)","Multi Color");
		COLOR_MAP.put("Clemantis","Medium Blue");
		COLOR_MAP.put("Geranium","Dark Pink");
		COLOR_MAP.put("Grey","Medium Gray");
		COLOR_MAP.put("Red Stripe","Medium Red");
		COLOR_MAP.put("Tradewinds Grey","Medium Gray");
		COLOR_MAP.put("Pulse","Medium Gray");

	}
	

}
